### ISSUE TITLE
Publish latest image sanity check

### ISSUE THREAD

**Issue by bryan-aguilar** [aws-observability/aws-otel-collector#1008]
A sanity check should be done on the the step [`Pull image from integration test ECR, tag as latest and push to public release ECR and DockerHub`](https://github.com/aws-observability/aws-otel-collector/blob/4c46b62f95c55464bf619dcc48e00ec2428e28ef/.github/workflows/CD.yml#L612) in the CD workflow. It is not entirely clear what would happen if we patch a previous minor version of the ADOT Collector. A high level overview of the [version checking logic](https://github.com/aws-observability/aws-otel-collector/blob/main/tools/workflow/docker-version-compare.sh) and the step conditions make it appear that the latest tag is always pushed. The latest tag should not be pushed when a patch version is not associated with the latest minor version.

**Comment by bryan-aguilar** [comment]
What about the `release-latest-s3` job?

**Comment by bryan-aguilar** [comment]
We also release to SSM. I don't think we have a latest for that but did we verify?

**Comment by bryan-aguilar** [comment]
I guess that was a bit outside of the scope of this issue since this only brings up the `image`. If you think it would be better to open a separate issue for these items then please do so. If not maybe we can change the description/title of this issue.

**Comment by Kausik-A** [comment]
As this issue was addressing one specific step of the CD workflow, I think its better we continue this discussion on another issue, while also keeping a reference to #1008. I will start a new one !
