### ISSUE TITLE
Otel-collector stopped logging to Cloudwatch

### ISSUE THREAD

**Issue by stnor** [aws-observability/aws-otel-collector#1014]
**Describe the question**
Is there a backwards-compatibility issue with the latest collector? I noticed there was a release of the collector four days ago which coincides with the lack of metrics in my end.

**Steps to reproduce if your question is related to an action**
I'm running the java otel agent 1.1 and my instances stopped pushing metrics to CloudWatch four days ago (when we did a release). I'm using "amazon/aws-otel-collector" without a version. The agent version is 1.1 with a few patches (unchanged since 8-12 months or so).

**Comment by Aneurysm9** [comment]
If you explicitly specify `amazon/aws-otel-collector:v0.16.1` do you receive the expected metrics?  If so, we'll need more information about your collector configuration before we can attempt to identify where an issue might lie.

**Comment by stnor** [comment]
I will try the v0.16.1 in a few hours and let you know.
The agent we run has a custom sampler, hence why we had to roll our own.

**Comment by stnor** [comment]
Yea. I'm getting metrics again on `[/aws/ecs/application/metrics]` using v0.16.1.

**Comment by stnor** [comment]
```json
{
  "ipcMode": null,
  "executionRoleArn": "arn:aws:iam::xxx:role/ecsTaskExecutionRole",
  "containerDefinitions": [
    {
      "dnsSearchDomains": null,
      "environmentFiles": null,
      "logConfiguration": {
        "logDriver": "awslogs",
        "secretOptions": null,
        "options": {
          "awslogs-group": "/xxx/access-log",
          "awslogs-region": "eu-west-1",
          "awslogs-stream-prefix": "admin"
        }
      },
      "entryPoint": null,
      "portMappings": [
        {
          "hostPort": 8180,
          "protocol": "tcp",
          "containerPort": 8180
        }
      ],
      "command": null,
      "linuxParameters": null,
      "cpu": 0,
      "environment": [
        {
          "name": "APPD_DISABLED",
          "value": "true"
        },
        {
          "name": "AWS_XRAY_DAEMON_ADDRESS",
          "value": "aws-otel-collector:2000"
        },
        {
          "name": "BATCH_HOST",
          "value": "true"
        }
      ],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": null,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "xxx.dkr.ecr.eu-west-1.amazonaws.com/xxx:2022-03-06-c577c916169951e3ebf726eaaa1451bf8f6a4750",
      "startTimeout": null,
      "firelensConfiguration": null,
      "dependsOn": [
        {
          "containerName": "aws-otel-collector",
          "condition": "START"
        }
      ],
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": null,
      "name": "xxx-admin"
    },
    {
      "dnsSearchDomains": null,
      "environmentFiles": null,
      "logConfiguration": {
        "logDriver": "awslogs",
        "secretOptions": null,
        "options": {
          "awslogs-group": "/ecs/xxx-ADMIN",
          "awslogs-region": "eu-west-1",
          "awslogs-stream-prefix": "ecs"
        }
      },
      "entryPoint": [],
      "portMappings": [],
      "command": [
        "--config=/etc/ecs/container-insights/otel-task-metrics-config.yaml"
      ],
      "linuxParameters": null,
      "cpu": 0,
      "environment": [],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": null,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "amazon/aws-otel-collector:v0.16.1",
      "startTimeout": null,
      "firelensConfiguration": null,
      "dependsOn": null,
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": null,
      "name": "aws-otel-collector"
    }
  ],
  "placementConstraints": [],
  "memory": "5120",
  "taskRoleArn": "arn:aws:iam::xxx:role/ecsXXXTaskRole",
  "compatibilities": [
    "EC2",
    "FARGATE"
  ],
  "taskDefinitionArn": "arn:aws:ecs:eu-west-1:xxx:task-definition/xxx-ADMIN:470",
  "family": "xxx-ADMIN",
  "requiresAttributes": [
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.ecr-auth"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.task-iam-role"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.container-ordering"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-ecr-pull"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.task-eni"
    }
  ],
  "pidMode": null,
  "requiresCompatibilities": [
    "EC2",
    "FARGATE"
  ],
  "networkMode": "awsvpc",
  "runtimePlatform": null,
  "cpu": "1024",
  "revision": 470,
  "status": "ACTIVE",
  "inferenceAccelerators": null,
  "proxyConfiguration": null,
  "volumes": []
}
```

**Comment by stnor** [comment]
I upgraded the agent to 1.11, and left the collector at 0.16.1. That broke the collection as well...

```OTEL_OPTS='-javaagent:/opt/aws-opentelemetry-agent-1.11.0-xxxx.jar -Dotel.resource.attributes=service.name=Xxxx -Dotel.instrumentation.jedis.enabled=false -Dotel.java.disabled.resource.providers=io.opentelemetry.sdk.extension.resources.ProcessResourceProvider -Dotel.traces.sampler=xxxx'```

**Comment by Aneurysm9** [comment]
> Ps. I do have premium support, so let me know if I should open a ticket.

Metrics are in public preview, so I think this is the appropriate venue to seek support unless you need to provide sensitive/confidential information.

https://github.com/open-telemetry/opentelemetry-collector/pull/4724 removed a number of long deprecated metrics messages from the OTLP receiver, which might account for `v0.17.0` not working with an older Java SDK, but shouldn't account for `v0.16.1` not working with a newer Java SDK.  

Does `v0.17.0` function as expected with agent `v1.11`?  Or do either `v0.17.0` or `v0.16.1` produce any different log messaging with the `v1.11` agent as opposed to `v1.1`?  @anuraaga are you aware of anything in the Java agent that would cause this incompatibility?

**Comment by stnor** [comment]
I couldn't get my build of the 1.11.0 agent to work with either version. I am now reverting to 1.1.0 and v0.16.1 as it's getting close to midnight here.  Let me know if there is something else I should try.

Just to be clear. Its the JVM metrics I am not seeing in the log group /aws/ecs/application/metrics
There is no "otel-stream" there unless using agent 1.1.0 and collector v.0.16.1.

Eg these:
```{
    "OTelLib": "io.opentelemetry.javaagent.shaded.instrumentation.runtimemetrics.MemoryPools",
    "_aws": {
        "CloudWatchMetrics": [
            {
                "Namespace": "ECS/AWSOTel/Application",
                "Dimensions": [
                    [
                        "pool",
                        "type",
                        "OTelLib"
                    ],
                    [
                        "OTelLib"
                    ],
                    [
                        "OTelLib",
                        "pool"
                    ],
                    [
                        "OTelLib",
                        "type"
                    ]
                ],
                "Metrics": [
                    {
                        "Name": "runtime.jvm.memory.pool",
                        "Unit": "Bytes"
                    }
                ]
            }
        ],
        "Timestamp": 1646691778469
    },
    "pool": "CodeHeap 'profiled nmethods'",
    "runtime.jvm.memory.pool": 1245184,
    "type": "committed"
}
```

**Comment by anuraaga** [comment]
Hi @stnor - more recent versions of the javaagent require explicitly enabling metrics (to opt in to potential broken behavior). Does it work when setting the env var `OTEL_METRICS_EXPORTER=otlp`?

**Comment by Aneurysm9** [comment]
To summarize, here's my understanding:

* Java Agent 1.1 and ADOT Collector v0.16.1 - Working as expected
* Java Agent 1.1 and ADOT Collector v0.17.0 - Not working, possibly due to removal of deprecated OTLP message types used by Java Agent 1.1
* Java Agent 1.11 and ADOT Collector v0.16.1 or v0.17.0 - Not working, possibly due to need to opt-in to sending metrics from newer versions of the Java Agent

If setting the environment variable proposed by @anuraaga gets the metrics flowing again, it sounds like we have mostly a documentation gap.  Is there somewhere in our documentation that you would have expected to find this information that we can improve?

**Comment by stnor** [comment]
@Aneurysm9 Sounds about right. I will try the agent environment setting ```OTEL_METRICS_EXPORTER=otlp```tonight.

FYI @anuraaga: Another breaking change I found was the package change of the ```io.opentelemetry.sdk.autoconfigure.spi.traces.ConfigurableSamplerProvider```which caused the registration of my sampler to fail at runtime since it wasn't picked up compile time (META-INF). I skimmed through the release notes of the sdk and the agent, but didn't find that breaking change.

**Comment by anuraaga** [comment]
Hi @stnor - the package didn't change but it was moved to a different artifact (autoconfigure-spi) so could that be the cause of missing it at compile time for you? 

https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.6.0

**Comment by stnor** [comment]
Are you sure? I had to rename the file in META-iNF and add ”traces”.

**Comment by anuraaga** [comment]
@stnor Ah that package rename does sound familiar - it's been a while, but indeed perhaps it wasn't properly documented in the release notes.

**Comment by stnor** [comment]
I can confirm that agent 1.11.0 creates the log streams after adding the env var `OTEL_METRICS_EXPORTER=otlp` with both 0.16.1 and 0.17.0 of the collector. Thanks for the help @anuraaga @Aneurysm9!

**Comment by stnor** [comment]
I notice now that I am not getting heap information anymore (or at least not in the same manner.
<img width="1569" alt="Screenshot 2022-03-08 at 22 04 34" src="https://user-images.githubusercontent.com/561167/157324949-7497e4aa-b71d-4b40-87f2-f7f1ca55168f.png">

Any ideas @anuraaga?

**Comment by stnor** [comment]
False alarm. I think the graphing was set to 5 min avg.
