### ISSUE TITLE
Strip down aws-otel-collector binary for AWS Lambda layer

### ISSUE THREAD

**Issue by wangzlei** [aws-observability/aws-otel-collector#102]
### Description:
This is a feature request. AWS Lambda has a hard limit that the total unzipped size of the function and all layers can't exceed the unzipped deployment package size limit of 250 MB. Besides that, the memory usage of a goLang program in Lambda is proportional to its binary size, put aws-otel-collector in Lambda directly will cause high Max memory used. So, the current aws-otel-collector is not fit to be packaged into lambda layer. We have to strip down aws-otel-collector as much as possible, create a minimized aws-otel-collector binary for Lambda.

### Solution:
Build a Lambda version aws-otel-collector which needs:
1. Remove all of receiver plugins except otlp receiver. 
2. Remove file exporter, otlp exporter
3. Remove all of processors
4. Keep health_check
5. remove output log to `/opt`
6. provide a public download url for binary

**Comment by mxiamxia** [comment]
Discussed with Lei. This is no need anymore. Closed the issue. Please feel free to reopen if anything changed
