### ISSUE TITLE
CW Metric Streams: Description of available resource attributes, metric names and metric labels

### ISSUE THREAD

**Issue by cedricziel** [aws-observability/aws-otel-collector#1036]
Hi folks,

raising an issue as recommended by @smoell. Quite possibly the wrong place, so feel free to point me somewhere else in case there's a better place.

I would like to learn more about the OpenTelemetry format provided for [CloudWatch Metric Streams](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-metric-streams-formats-opentelemetry.html).

In OpenTelemetry metrics, resources are described by 3 major components:
* resource attributes
* metric names
* metric labels

From the description on the linked docs, the resource attributes on the envelope describe the account and metric stream. - Which is great!

Then the contained instrumentation library metrics can be translated to AWS resources through a combination of metric name and label:
[amazonaws.com/AWS/DynamoDB/ConsumedReadCapacityUnits](http://amazonaws.com/AWS/DynamoDB/ConsumedReadCapacityUnits) => DynamoDB
-> label(TableName=MyTable)  => more specific resource

My question is: Is there a comprehensive overview of possible Metric Names and their labels? If not, is it possible to either publish or compile it? That would greatly help building any intelligence on it.

**Is your feature request related to a problem? Please describe.**
We want to learn more about all possible metric names and labels CW metric streams exposes.

**Describe the solution you'd like**
Ideally, a structured format suitable for automatic processing :) 

**Describe alternatives you've considered**
Creating a resource instance for every single AWS service / resource and listen to the CW metrics it emits - quite possibly a "suboptimal" solution ;) 

**Additional context**
We're looking into using such spec for interpreting AWS metrics in our observability suite with IBM/Instana

**Comment by bryan-aguilar** [comment]
Hi @cedricziel,
I have tried to answer your questions to the best of my ability below, please let me know if I may be missing some additional context.

>Is there a comprehensive overview of possible Metric Names and their labels?
No, metric and label names are user input and constrained only in that they must be composed of Unicode code points

>If not, is it possible to either publish or compile it?
No, again these are defined by users input which would be much too large of a domain. 

AWS Services do supply some metrics to CW by default but we are not aware of any type of any standardization of their naming or dimensions. 

I hope that cleared some things up, if it didn't please let us know.

**Comment by bryan-aguilar** [comment]
Also, the[ semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/metrics/semantic_conventions) _may_ help and provide a bit more context to possible metric names and their labels.

**Comment by cedricziel** [comment]
Hey Bryan;
Thanks for the prompt comment!

My questions are specifically concerning the attributes and labels AWS are applying in CloudWatch metric stream with OpenTelemetry.

From the example linked above, the platform seems to add add some semantic labels. Is that fair?

**Comment by bryan-aguilar** [comment]
I do not believe that CW Metric streams are specifically applying those metrics or labels. All of that information is provided by DynamoDB and then translated by CW to OTLP (an ancient version). We (the ADOT team) are not aware of any list that documents those but if it does exist it would exist somewhere within the CloudWatch ecosystem. 

This inquiry may be better suited for the CloudWatch team. 

@smoell may be able to direct you to the correct point of contact, if not I can ask around.
