### ISSUE TITLE
Export OTEL traces with Auth extension

### ISSUE THREAD

**Issue by Legion2** [aws-observability/aws-otel-collector#1056]
**Is your feature request related to a problem? Please describe.**
I want to send traces to a remote otel collector which is secured with the oidc extension.

**Describe the solution you'd like**
I want to use the `oauth2client` auth extension in the otel exporter to get an access token which is required to send traces to the remote collector.

**Describe alternatives you've considered**
There is no alternative, security is important and it can not be disabled.

**Additional context**
The `oauth2client` auth extension is part of the opentelemetry-collector-contrib repo https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.46.0/extension/oauth2clientauthextension

**Comment by r0mdau** [comment]
We are also interested for this feature request. More information about our context here #1081
