### ISSUE TITLE
Public SSM Parameter with Latest Release

### ISSUE THREAD

**Issue by driverpt** [aws-observability/aws-otel-collector#1074]
**Is your feature request related to a problem? Please describe.**
We want to automatically deploy a new version when available

**Describe the solution you'd like**
Use SSM + EventBridge + Lambda

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by driverpt** [comment]
No stale!

**Comment by driverpt** [comment]
No stale!

**Comment by mhausenblas** [comment]
Hi @driverpt :)

Can you detailed out a bit the feature request please?

**Comment by driverpt** [comment]
Hey @mhausenblas, this Feature request is simple. It's just for aws to publish latest ADOT Collector version on Public SSM Parameter.

What we are trying to achieve is to automatically download new Java Agent to S3 and Update Java Agents via ECS Force Redeploy and update the Collector version.

**Comment by vsakaram** [comment]
Thank you for the feedback, @driverpt , but at this time we do not have this in our roadmap.  Changes to the version of components in a working system can have significant impact and especially where we are not the operators.  Also, as Collector is a complex system that can be deployed in many different ways, we recommend having a deployment pipeline that allows for testing of changes to system component versions.

**Comment by driverpt** [comment]
@vsakaram, thank you for analyzing this request.

We know that upgrading OTEL on an infrastructure is complex. ADOT Collector + Agent is under AWS control. All we need is an SSM Public Parameter (AWS Managed) indicating the latest version of these components, we will take over from there. 

As a Engineer, I don't think it will be that hard to implement this on your side.

**Comment by Aneurysm9** [comment]
Implementation complexity is not the issue here.  Desirability and propriety are the concerns.  We understand and acknowledge the feature request you are making, but at this time it is not something we are planning to implement.  This is not a final decision and, if we hear this request repeatedly from other customers, we can reconsider in the future.

**Comment by driverpt** [comment]
Thank you for your reply. If this is not a final decision, why is this issue being closed?
