### ISSUE TITLE
Hostmetricsreceiver in ADOT

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#1098]
Hello, From which version will the Hostmetricsreceiver in ADOT be available?

**Comment by bryan-aguilar** [comment]
Hi @georges-git, we currently do not have an expected release version on which the `hostmetricsreceiver` will be integrated into ADOT. To prevent duplication of issues could you please add some context/input to this issue #556.

**Comment by georges-git** [comment]
It is very important to have hostmetrics sent via OTEL as some the those are used for SLO/SLA managament.  Updated that ticket as well.
