### ISSUE TITLE
Add routing and groupbyattrs processor from opentelemetry-collector-contrib source

### ISSUE THREAD

**Issue by akshayvadher** [aws-observability/aws-otel-collector#1100]
**Is your feature request related to a problem? Please describe.**
[OpenTelemetry Contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib) repo has `routing` and `groupbyattrs` processors but the aws otel collector does not have it.

**Describe the solution you'd like**
I want to use both processors in my otel collector

**Additional context**
Ideally AWS collector should support everything OTEL and OTEL-CONTRIB supports

**Comment by bryan-aguilar** [comment]
Hi @akshayvadher, thank you for the request. Could you please provide more context for your use case for these two processors. The team would find it helpful to understand how our users are trying to use the ADOT Collector.

**Comment by bryan-aguilar** [comment]
Here are a couple of suggestions for reducing noise 
1. Avoid instrumenting health checks by not putting a tracing handler on your health check.
2. Sampling out traces for health checks at the application so that the spans are never created and sent.

**Comment by akshayvadher** [comment]
Thanks for the reply.

For point 1 - In order to avoid health checks by not putting a tracing handler on health checks - we will have to manually build the trace and spans - which we wanted to avoid. We are using [AWS OpenTelemetry Agent](https://github.com/aws-observability/aws-otel-java-instrumentation/releases/latest/download/aws-opentelemetry-agent.jar)  to auto instrument

For point 2 - can you please point to any example or doc? I don't see any out of box way so sample out URL based spans. All I see is percentage based and memory based sampling.

**Comment by Galactic21** [comment]
Good afternoon, I would like to say that I support @akshayvadher request because it was also something that affected my work and it was advisable to add these 2 processors to the official image of aws-otel-collector. 
Best regards.
