### ISSUE TITLE
otel-fargate-container-insights configuration seems to expose a service when there is none

### ISSUE THREAD

**Issue by anuraaga** [aws-observability/aws-otel-collector#1108]
When looking through this config

https://github.com/aws-observability/aws-otel-collector/blob/main/deployment-template/eks/otel-fargate-container-insights.yaml

I noticed there is a service configured for port 8888

https://github.com/aws-observability/aws-otel-collector/blob/main/deployment-template/eks/otel-fargate-container-insights.yaml#L493

However, the collector only has a prometheus receiver so is not actually serving any port. If I'm not missing something, this service should be removed to prevent confusion.

**Comment by Aneurysm9** [comment]
The collector's self-metrics are exposed on that port.

**Comment by anuraaga** [comment]
I don't think we expect anything else to be scraping the collector in this example, do we?
