### ISSUE TITLE
Dynamic sampling in OpenTelemetry collector

### ISSUE THREAD

**Issue by ntyrewalla** [aws-observability/aws-otel-collector#111]
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1562

**Comment by otbe** [comment]
Sorry to comment in this issue but it seems quite related to a issue we were faced these days.

Does it mean that the AWS flavoured collector does not take AWS Xray Sampling rules into account? So we're running at 100% sample rate (default from what I can tell)?

**Comment by marcobazzani** [comment]
is this actively worked how can we reduce sampling honoring the X-ray UI ?

**Comment by anuraaga** [comment]
The collector and Java support for this have been added so I think we can close this out, more languages will come as they do.

https://aws-otel.github.io/docs/getting-started/remote-sampling
