### ISSUE TITLE
Requesting SumoLogic Exporter

### ISSUE THREAD

**Issue by brianmiller-kubra** [aws-observability/aws-otel-collector#1123]
**Is your feature request related to a problem? Please describe.**

Currently, SumoLogic only supports the OTLP protocol for traces. We would like to use the SumoLogic Exporter to be able to export Metrics and Logs to SumoLogic from the Adot Collector.

**Describe the solution you'd like**
A SumoLogic exporter already exists as part of the OpenTelemetry Collector Contrib project.
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/sumologicexporter
We would just like it to be included in the Adot Collector.

**Describe alternatives you've considered**
Manually building our own our Collector application that includes the SumoLogic exporter.

**Additional context**
N/A

**Comment by alolita** [comment]
Hi @brianmiller-kubra thanks for your request. We will take a look at your request and prioritize after metrics is declared stable upstream (current target is May 2022).
