### ISSUE TITLE
Support tail sampling processor

### ISSUE THREAD

**Issue by ElementalWarrior** [aws-observability/aws-otel-collector#1135]
When trying to use the tail_sampling processor, I found it was not included as one of the processors defined in AWS ADOT

**Describe the solution you'd like**
Add the tailsamplingcollector package and add it to the processor map.

**Describe alternatives you've considered**
I tried creating a PR, but it was closed. I have used the branch from the PR to self host a forked docker image. 

Effectively for my needs, I need to be able to have the collector drop spans such as health check endpoints, which can be accomplished with the tail sampling processor. But there are other uses as well

**Additional context**
[My pull request](https://github.com/aws-observability/aws-otel-collector/pull/1132)

**Comment by alexfdz** [comment]
We would like to use the `tail_sampling` processor too. In our use case we would like to limit to a specific rate the amount of successful spans.

```
processors:
  tail_sampling:
    decision_wait: 30s
    policies:
      [
        {
          name: sample_few_successful_spans,
          type: and,
          and: {
            and_sub_policy:
              [
                {
                  name: sample_successful_spans,
                  type: status_code,
                  status_code: { status_codes: [ OK ] }
                },
                {
                  name: sample_few_spans,
                  type: rate_limiting,
                  rate_limiting: { spans_per_second: 15 }
                }
              ]
          }
        }
      ]
```

**Comment by zksward** [comment]
We're looking to add ADOT to our observability efforts but tail sampling is a must have. +1 from us

**Comment by mhausenblas** [comment]
Thanks for your feedback @zksward! ADOT PM here. Can you elaborate why it's a "must have" please?

**Comment by zksward** [comment]
It allows us to estimate and control costs while having the flexibility to specify traces of interest. We have a high throughput distributed application and one of the main concerns and pushback on implementing a system wide observability solution is managing the volume of the data. Are there alternatives to the behavior of which I'm not aware?

**Comment by mhausenblas** [comment]
Thanks, again. It's not on our immediate roadmap but things can always change.

> Are there alternatives to the behavior of which I'm not aware?

You can use what the respective SDK offers, in your app.

**Comment by zksward** [comment]
Thanks for being open to the feedback! I'm excited for the possibilities ADOT brings.

**Comment by jsalinaspolo** [comment]
> You can use what the respective SDK offers, in your app.

It is really hard to manage in the app once you have to sync with many services pushing traces to the collector
Making the sampling in the collector, it can be guaranteed

Any update if it is planned for the next release in August/September?
