### ISSUE TITLE
Canary tests are marked green even when they have failures

### ISSUE THREAD

**Issue by anuraaga** [aws-observability/aws-otel-collector#1141]
https://github.com/aws-observability/aws-otel-collector/actions/runs/2158963605

**Comment by bryan-aguilar** [comment]
This is due to the [retry](https://github.com/aws-observability/aws-otel-collector/blob/8f968bf83e5d50d7edfea28457dbb8bcbb0f09f1/.github/workflows/canary.yml#L128) mechanic. Attempt 1 failed but the second attempt was successful.

**Comment by anuraaga** [comment]
Not too sure but wouldn't the retry look like "Attempt X failed. Reason: Child_process exited with error code 1", not the red x and "Terraform exited with code 1.". The otlp_metric windows one seems to be the only one with a red mark, and it is the one for an internal alarm that was raised. Perhaps still coincidence though, would need to deep dive into the graph to see what it looks like perhaps.

**Comment by bryan-aguilar** [comment]
The `Run Canary Test` job does have that in its logs which can be seen [here](https://github.com/aws-observability/aws-otel-collector/runs/6001388887?check_suite_focus=true#step:8:1558).

**Comment by bryan-aguilar** [comment]
There could possibly be something funky going on with the second attempt. Maybe it doesn't actually complete successfully despite the output saying so. I don't know if that's actually happening but I think it's possible.
