### ISSUE TITLE
[awscontainerinsightreceiver] alternative node metadata source

### ISSUE THREAD

**Issue by bryangardner** [aws-observability/aws-otel-collector#1202]
**Is your feature request related to a problem? Please describe.**
In EKS clusters running EC2 nodes with pod access to EC2 IMDS **restricted**, the awscontainerinsightreceiver fails to fetch instance ID, instance type, instance region, and instance IP address. This causes the receiver to drop all metrics.

**Describe the solution you'd like**
An alternative node metadata source for the awscontainerinsightreceiver, other than IMDS.
Some potential sources include:
1. Kubernetes node API
2. EC2 service API

This likely will require the node name to be passed into the pod, documented [here](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/).

**Describe alternatives you've considered**

**Additional context**

**Comment by bryangardner** [comment]
Commenting to remove stale label

**Comment by T0tt1** [comment]
I am having the same issue.
Please work on fixing this bug. I don't think it is a feature but a big working with IMDSv2 (Metadata service v2) on EC2.
Pods while trying to start crashes as and according to the logs of the pod, issue is:
``` EC2MetadataError: failed to make EC2Metadata request\n\n\tstatus code: 401, request id: ```

Workaround is to switch EKS Workers' EC2 instance back to IMDSv1 but for me this is not a good and permament solution.
``` aws ec2 modify-instance-metadata-options  --instance-id <instance-id> --http-tokens optional --http-endpoint enabled ```

Appreciate your assitance in advance.

**Comment by bryangardner** [comment]
Hey @T0tt1, by default the IMDSv2 response hop limit is 1. Another workaround, if you want to disable IMDSv1 and use IMDSv2, you can try to configure the `http-put-response-hop-limit` to 2.

From [EC2 IMDSv2 docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html#instance-metadata-transition-to-version-2):
> By default, the response to PUT requests has a response hop limit (time to live) of 1 at the IP protocol level. You can adjust the hop limit using the modify-instance-metadata-options command if you need to make it larger. For example, you might need a larger hop limit for backward compatibility with container services running on the instance.

**Comment by T0tt1** [comment]
> Hey @T0tt1, by default the IMDSv2 response hop limit is 1. Another workaround, if you want to disable IMDSv1 and use IMDSv2, you can try to configure the `http-put-response-hop-limit` to 2.
> 
> From [EC2 IMDSv2 docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html#instance-metadata-v2-how-it-works):
> > By default, the response to PUT requests has a response hop limit (time to live) of 1 at the IP protocol level. You can adjust the hop limit using the modify-instance-metadata-options command if you need to make it larger. For example, you might need a larger hop limit for backward compatibility with container services running on the instance.

@bryangardner do you think this will help? While deploying the ADOT OTEL Namespace, Ds, Svc, Pods, etc. I am getting HTTP 401 in pod logs and they fail to become ready.

**Comment by hammopauGSS** [comment]
Ignoring the problem does not make it go away AWS...
