### ISSUE TITLE
ECS ADOT Collector Kafka exporter

### ISSUE THREAD

**Issue by denny6389** [aws-observability/aws-otel-collector#1252]
**Describe the question**
Is it possible to setup adot collector on ecs as a sidecar and export trace data to kafka, not xray?

If so, how does the instrumentation work? Is auto-instrumentation possible?

And lastly, is there a specific guide for adot tracing in ecs environment? 

Thank you in advance.

**Comment by bryan-aguilar** [comment]
At the current point in time the Kafka exporter is not included in the ADOT Collector. 

> If so, how does the instrumentation work? Is auto-instrumentation possible?

Export from the collector is independent from application instrumentation. There should be no impact in instrumentation if you choose a different exporter. 

> And lastly, is there a specific guide for adot tracing in ecs environment?

For more information on tracing within ECS please refer to our documentation [here](https://aws-otel.github.io/docs/setup/ecs).
