### ISSUE TITLE
Tail sampling processor for ADOT

### ISSUE THREAD

**Issue by jordi-farre** [aws-observability/aws-otel-collector#1284]
**Is your feature request related to a problem? Please describe.**
We currently use ADOT to collect traces from our applications and send them to Honeycomb. We want to do some sampling on the collector to reduce the number of traces sent to Honeycomb. We want to use this processor (https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor) but it's not included in ADOT. 

**Describe the solution you'd like**
Make tail sampling processor available in ADOT. 

**Describe alternatives you've considered**
We didn't find any other alternative to do this kind of sampling in ADOT.

**Additional context**

**Comment by bryan-aguilar** [comment]
Hi @jordi-farre,

It appears that there is already a feature request for the `tail-sampling processor` at issue #1135. Would you mind providing feedback on that issue so we can have one issue for this feature request? Also, if you could provide any additional context on what type of sampling you are trying to accomplish, it would be helpful.

**Comment by jordi-farre** [comment]
Thanks Bryan, we didn't notice there was a feature request about this. We added a [comment](https://github.com/aws-observability/aws-otel-collector/issues/1135#issuecomment-1149477987) on FR #1135 and will close this one.
