### ISSUE TITLE
ADOT and host metrics

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#1287]
Hello, Seems open telemetry  (https://opentelemetry.io/blog/2022/metrics-announcement/) is now supporting host metrics as indicated in this link, is there a version available of ADOT, which can emit host level metrics? If not, from when ADOT would support host metrics.

**Comment by mhausenblas** [comment]
Hey @georges-git thanks for raising this issue.

> is there a version available of ADOT, which can emit host level metrics

If your ask is if the ADOT collector currently includes the [Host Metrics Receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver) then the answer is no.

> If not, from when ADOT would support host metrics.

This is on our mid-term roadmap and it would help in prioritizing this if you could share some more details: what's your current setup (e.g. are you using [prometheus/node_exporter](https://github.com/prometheus/node_exporter), etc.), and what are your requirements around the host metrics?

**Comment by georges-git** [comment]
Hi, Currently using Cloudwatch agent to send host metrics and ADOT collector to send traces and application metrics which means need to maintain both of these for EC2 apps and Fargate apps across all 50+ applications and 5 environments. I would like to use one agent like ADOT to collect the host metrics OR CloudWatch agent if can send the traces, application metrics and host metrics.  What is your suggestion?

**Comment by mhausenblas** [comment]
> What is your suggestion?

As I said above, for the time being, consider using the Prometheus node exporter and ADOT collector; this will allow you to handle both metrics and traces. Closing this one out now since it's a dupe and we track it in https://github.com/aws-observability/aws-otel-collector/issues/556
