### ISSUE TITLE
Give a link to the OpenTelemetry collector for reference

### ISSUE THREAD

**Issue by rakyll** [aws-observability/aws-otel-collector#130]
It's not very clear to the users that we are following the same config format. Mention that the config is compatible with the OpenTelemetry collector configuration.

**Comment by mxiamxia** [comment]
Thanks, will update.

**Comment by mxiamxia** [comment]
Merged the related updates in README 

https://github.com/aws-observability/aws-otel-collector#aws-otel-collector-configuration
