### ISSUE TITLE
Exception/Panic in adot-collector for Cloudwatch configuration.

### ISSUE THREAD

**Issue by Chetan496** [aws-observability/aws-otel-collector#1302]
Hi All

I am trying to setup the AWS OpenTelemetry distro on EKS 1.21
I followed all the steps mentioned [here](https://docs.aws.amazon.com/eks/latest/userguide/opentelemetry.html)

The adot operator was setup, the EKS addon was also enabled, the service account and the IAM role were also created.
I can see that the `adot` addon is enabled in the EKS cluster.
But, when I create the adot-collector for Cloudwatch as explained over [here](https://docs.aws.amazon.com/eks/latest/userguide/configure-cw.html), I see that the pod for cloudwatch collector starts but keeps going in a "CrashLoopBackOff"state.

```
❯ kubectl get pods
NAME                                                READY   STATUS             RESTARTS   AGE
my-collector-cloudwatch-collector-5db7d598d-f8j7c   0/1     CrashLoopBackOff   3          51s
```

When I see the pod logs, I see the following error.
I see a "segmentation violation". 
I do not understand the below error. 
Please help me understand the below error, and what steps should I take to resolve it.

```
2022/06/14 07:41:33 AWS OTel Collector version: v0.17.0
2022/06/14 07:41:33 found no extra config, skip it, err: open /opt/aws/aws-otel-collector/etc/extracfg.txt: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8a664a]

goroutine 1 [running]:
go.uber.org/zap.(*Logger).check(0x0, 0x1, {0x3610ca9, 0x1b})
        go.uber.org/zap@v1.21.0/logger.go:270 +0x6a
go.uber.org/zap.(*Logger).Warn(0x0, {0x3610ca9, 0x0}, {0xc00095a140, 0x1, 0x1})
        go.uber.org/zap@v1.21.0/logger.go:199 +0x3e
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsemfexporter.(*Config).Validate(0xc000597400)
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsemfexporter@v0.45.1/config.go:97 +0x289
go.opentelemetry.io/collector/config.(*Config).Validate(0xc00067a210)
        go.opentelemetry.io/collector@v0.45.0/config/config.go:74 +0x2a8
go.opentelemetry.io/collector/service.(*configProvider).Get(0xc000225ce0, {0x3c16150, 0xc00005e020}, {0xc00058fe60, 0xc000692150, 0xc0006923f0, 0xc00058fcb0})
        go.opentelemetry.io/collector@v0.45.0/service/config_provider.go:167 +0x2de
go.opentelemetry.io/collector/service.(*Collector).setupConfigurationComponents(0xc0000d8460, {0x3c16150, 0xc00005e020})
        go.opentelemetry.io/collector@v0.45.0/service/collector.go:171 +0xa3
go.opentelemetry.io/collector/service.(*Collector).Run(0xc0000d8460, {0x3c16150, 0xc00005e020})
        go.opentelemetry.io/collector@v0.45.0/service/collector.go:221 +0x24e
main.newCommand.func1(0xc00079ca00, {0x35d8b36, 0x1, 0x1})
        github.com/aws-observability/aws-otel-collector/cmd/awscollector/main.go:117 +0xf5
github.com/spf13/cobra.(*Command).execute(0xc00079ca00, {0xc00004c050, 0x1, 0x1})
        github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00079ca00)
        github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.3.0/command.go:902
main.runInteractive({{0xc00058fe60, 0xc000692150, 0xc0006923f0, 0xc00058fcb0}, {{0x35f3e9b, 0x12}, {0x35f29a7, 0x12}, {0x3b32b10, 0x7}}, ...})
        github.com/aws-observability/aws-otel-collector/cmd/awscollector/main.go:83 +0x5d
main.run({{0xc00058fe60, 0xc000692150, 0xc0006923f0, 0xc00058fcb0}, {{0x35f3e9b, 0x12}, {0x35f29a7, 0x12}, {0x3b32b10, 0x7}}, ...})
        github.com/aws-observability/aws-otel-collector/cmd/awscollector/main_others.go:42 +0xf8
main.main()
        github.com/aws-observability/aws-otel-collector/cmd/awscollector/main.go:76 +0x2d8

```

**Comment by Chetan496** [comment]
cc @mhausenblas, @bryan-aguilar

**Comment by bryan-aguilar** [comment]
Can you please try the [this](https://github.com/aws-observability/aws-otel-community/blob/master/sample-configs/operator/collector-config-cloudwatch.yaml) configuration instead?

**Comment by Chetan496** [comment]
> Can you please try the [this](https://github.com/aws-observability/aws-otel-community/blob/master/sample-configs/operator/collector-config-cloudwatch.yaml) configuration instead?

Hello Bryan, I tried this configuration today (I deleted old configuration first using `kubectl delete -f `). 
But I get the same error.

The only difference between this configuration and the previous one - is the service account name. I ensured that service account called `adot-demo` exists and has valid IAM role associated.
But, the error still remains..

**Comment by erichsueh3** [comment]
Hi @Chetan496, this issue should have been fixed upstream, and those changes will be included in the next addon version

**Comment by Chetan496** [comment]
> Hi @Chetan496, this issue should have been fixed upstream, and those changes will be included in the next addon version

Any idea by when the next addon version be available?

**Comment by erichsueh3** [comment]
addon version 0.51 is available now

**Comment by erichsueh3** [comment]
Hi @Chetan496, looks like there is an error in the documentation, for the `awsemf` exporter, the `metric_declarations` field is missing `metric_name_selectors`, which is required if using the metric_declarations` field, see [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ae5dec1702d157a5185f02042ded9c0b5388b4a6/exporter/awsemfexporter/metric_declaration.go#L83-L85). Documentation and configuration for CloudWatch will be updated soon

**Comment by Chetan496** [comment]
@erichsueh3  I have got the addon version 0.51 enabled (there was a minor issue with RBAC permissions which I resolved by updating RBAC in YAML for addon permissions).
But, I am unsure what needs to be set for `metric_name_selectors`.

The following is the snippet for `awsemf` exporter that I have.
Please let me know what should be specified for `metric_name_selectors` below.

```
     awsemf:
        region: "eu-west-2"
        namespace: ContainerInsights/Prometheus
        log_group_name: '/aws/containerinsights/myCluster/prometheus'
        resource_to_telemetry_conversion:
          enabled: true
        dimension_rollup_option: NoDimensionRollup
        parse_json_encoded_attr_values: [Sources, kubernetes]
        metric_declarations:
          - dimensions: [[EKS_Cluster, EKS_Namespace, EKS_PodName]]
            metric_name_selectors: <not sure what should be put here>

```

**Comment by erichsueh3** [comment]
> @erichsueh3 I have got the addon version 0.51 enabled (there was a minor issue with RBAC permissions which I resolved by updating RBAC in YAML for addon permissions). But, I am unsure what needs to be set for `metric_name_selectors`.

For now, please remove the `metric_declarations` field and it's subfields

**Comment by Chetan496** [comment]
> > @erichsueh3 I have got the addon version 0.51 enabled (there was a minor issue with RBAC permissions which I resolved by updating RBAC in YAML for addon permissions). But, I am unsure what needs to be set for `metric_name_selectors`.
> 
> For now, please remove the `metric_declarations` field and it's subfields

@erichsueh3  Yes it works if I remove `metric_declarations` field and it's subfields.  I can see it is able to create metrics in Cloudwatch and also create the log group.

But, I do not see any visualization/charts/grapgs in Cloudwatch container insights. How do I enable cloudwatch container insights with metrics from AWS OpenTel?
Will it need the `metric_declaration`?

**Comment by erichsueh3** [comment]
Hi, please take a look at the documentation about CloudWatch Container Insights [here](https://aws-otel.github.io/docs/getting-started/container-insights)
