### ISSUE TITLE
Trying to collect server metrics - Disk/CPU utilization

### ISSUE THREAD

**Issue by Godwinmoses93** [aws-observability/aws-otel-collector#1309]
@mhausenblas,
Looks like this component isn't on the ADOT distribution yet:
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver

Can someone confirm me on this, That would be a great help !!

Reference - https://github.com/aws-observability/aws-otel-collector/issues/740
https://github.com/aws-observability/aws-otel-collector/issues/1287

@alolita - Did you find any other way to get the hostmetric !!

@mhausenblas -  I am trying to collect Infrastructure/Application/Services metrics using ADOT. Please suggest me, how I can collect it and display in cloudwatch ! I am trying to collect it from EC2 instance either from a windows or any linux flavors.

Thanks in advance.

**Comment by mhausenblas** [comment]
> Looks like this component isn't on the ADOT distribution yet. Can someone confirm me on this.

That's correct and it's on our mid-term roadmap, tracked in https://github.com/aws-observability/aws-otel-collector/issues/556

> I am trying to collect Infrastructure/Application/Services metrics using ADOT

You can for the time being use the [Prometheus node exporter](https://github.com/prometheus/node_exporter) to collect system level metrics from machines and then use the ADOT collector to scrape these and use the [EMF exporter](https://aws-otel.github.io/docs/getting-started/cloudwatch-metrics) to ingest them into CW Metrics.
