### ISSUE TITLE
Source for aws-otel-emitter app referenced in eks demo docs

### ISSUE THREAD

**Issue by tvkit** [aws-observability/aws-otel-collector#133]
I hoped to review the _aws-otel-emitter_ source to better understand the side-car configuration referenced in the eks guide. Can that be made available?

**Comment by PettitWesley** [comment]
I think it might be this: https://github.com/aws-observability/aws-otel-test-framework/tree/terraform/sample-apps/spark/src/main/java/com/amazon/sampleapp
