### ISSUE TITLE
X-ray not logging stack trace

### ISSUE THREAD

**Issue by stelescuraul** [aws-observability/aws-otel-collector#1363]
I am not sure if this is the right repository to ask this question so please let me know if I should post it somewhere else. Also, I am not sure if this is a bug or simply a feature that doesn't exist.
**Describe the question**
I have been trying to add tracing with x-ray in our nodejs application using aws otel. Everything seems to be working fine, things get exported properly with one exeption: When an error occurs, I can see the Error name and description in x-ray but i cannot see the stack trace.
I am using `AWSXRayPropagator` and more or less following this guide: https://aws-otel.github.io/docs/getting-started/js-sdk/trace-manual-instr
When I use JaegerExporter the stack traces shows up properly when errors occur. Can someone point me in the right direction on how to make stack traces show up in x-ray ?

**Steps to reproduce if your question is related to an action**
The test was made in a Nestjs application in a private repository. If needed, I can create a sample where this issue occurs.

**What did you expect to see?**
I expect to see the error message, the description as well as the stack trace.

**Environment**
Everything is running locally, the aws otel collector is running in docker as per this documentation: https://aws-otel.github.io/docs/setup/docker-images
The application is a nodejs app using nestjs. 

**Additional context**
I just want to clarify that I see the errors in x-ray, I just don't see the stack trace and I can't find a way to add it. I even tried a custom span and still didn't work. 

```ts
      span.recordException({
        stack: wrappedError.stack,
        name: wrappedError.name,
        message: wrappedError.message,
        code: wrappedError.getStatus(),
      });


     span.setAttributes({
        [SemanticAttributes.EXCEPTION_MESSAGE]: wrappedError.name,
        [SemanticAttributes.EXCEPTION_TYPE]: 'Error',
        [SemanticAttributes.EXCEPTION_STACKTRACE]: wrappedError.stack,
      });
```

**Comment by tiithansen** [comment]
This workaround did a trick for us at the moment. We are using Grafana  & X-Ray datasource to view traces. 
Notice that the stacktrace is stored in EXCEPTION_MESSAGE field.

```javascript
span.addEvent('exception', {
    [SemanticAttributes.EXCEPTION_MESSAGE]: err.stack,
    [SemanticAttributes.EXCEPTION_TYPE]: err.constructor.name,
    [SemanticAttributes.EXCEPTION_STACKTRACE]: err.stack,
});
```

**Comment by stelescuraul** [comment]
Not stale.
