### ISSUE TITLE
Create awscloudwatchmetrics exporter

### ISSUE THREAD

**Issue by HudsonHumphries** [aws-observability/aws-otel-collector#1381]
**Is your feature request related to a problem? Please describe.**

Currently the main way of creating cloudwatch metrics from the collector is to use the awsemfexporter. Metrics can be created from the logs created by this emf exporter, but directly exporting to metrics would be advantageous and a preferred solution for our use case due to cost and reliability. 

**Describe the solution you'd like**

A awscloudwatchmetrics exporter to be created that uses PutMetricData for CloudWatch, directly updating metric data as an exporter rather than creating metrics from logs.

**Describe alternatives you've considered**

The main alternative is using the emfexporter that currently exists and is what we will be using until a direct metrics exporter exists

**Comment by jeromeinsf** [comment]
Why would exposing metrics be more cost effective and reliable than the awsemfexporter?
