### ISSUE TITLE
Amazon X-ray configuration for Singapore

### ISSUE THREAD

**Issue by dimitardanailov** [aws-observability/aws-otel-collector#1387]
Greetings, 

As a tutorial: I've been following:
https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/ecs-demo.md

I've several questions about the template: 
https://github.com/aws-observability/aws-otel-collector/blob/main/examples/ecs/aws-cloudwatch/ecs-fargate-sidecar.json

My personal opinion line: 
https://github.com/aws-observability/aws-otel-collector/blob/main/examples/ecs/aws-cloudwatch/ecs-fargate-sidecar.json#L58 is wrong. 
At least for me should be: aws-otel-collector

The next question is about the line 10:
https://github.com/aws-observability/aws-otel-collector/blob/main/examples/ecs/aws-cloudwatch/ecs-fargate-sidecar.json#L10

What should be the value of command. 

My client is based in Singapore. I'd like to share with you my working file

```json
{
  "family": "aws-otel-FARGATE",
  "taskRoleArn": "ECS-AWSOTel",
  "executionRoleArn": "ECS-AWSOTel",
  "networkMode": "awsvpc",
  "containerDefinitions": [
    {
      "name": "aws-otel-collector",
      "image": "amazon/aws-otel-collector",
      "command": [
        "{{command}}"
      ],
      "essential": true,
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "/ecs/ecs-aws-otel-sidecar-collector",
          "awslogs-region": "ap-southeast-1",
          "awslogs-stream-prefix": "ecs",
          "awslogs-create-group": "True"
        }
      }
    },
    {
      "name": "aws-otel-emitter",
      "image": "public.ecr.aws/aws-otel-test/aws-otel-goxray-sample-app:latest",
      "essential": false,
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "/ecs/ecs-aws-otel-sidecar-app",
          "awslogs-region": "ap-southeast-1",
          "awslogs-stream-prefix": "ecs",
          "awslogs-create-group": "True"
        }
      },
      "dependsOn": [
        {
          "containerName": "aws-otel-collector",
          "condition": "START"
        }
      ]
    },
    {
      "image": "nginx:latest",
      "name": "nginx",
      "essential": false,
      "dependsOn": [
        {
          "containerName": "aws-otel-collector",
          "condition": "START"
        }
      ]
    },
    {
      "image": "alpine/socat:latest",
      "memory": 512,
      "dependsOn": [
        {
          "containerName": "aws-otel-collector",
          "condition": "START"
        }
      ],
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-create-group": "True",
          "awslogs-region": "ap-southeast-1",
          "awslogs-stream-prefix": "ecs",
          "awslogs-group": "/ecs/statsd-emitter"
        }
      },
      "entryPoint": [
        "/bin/sh",
        "-c",
        "while true; do echo 'statsdTestMetric:1|c' | socat -v -t 0 - UDP:127.0.0.1:8125; sleep 1; done"
      ],
      "name": "aoc-statsd-emitter",
      "cpu": 256,
      "essential": false
    }
  ],
  "requiresCompatibilities": [
    "FARGATE"
  ],
  "cpu": "256",
  "memory": "512"
}
```

**Comment by mhausenblas** [comment]
Thanks for raising this issue @dimitardanailov and please do note that as per policy, we're providing support via GitHub on a best effort basis. However, if you have AWS Enterprise Support you can create a ticket and we will provide direct support within the respective SLAs.

**Comment by dimitardanailov** [comment]
@mhausenblas 

Thank you very much for the response! 

I'd like to add for my question: I can't understand the following paragraph:

View Your Metrics
You should now be able to view your metrics in your CloudWatch console. In the navigation bar, click on Metrics. The collected `AWSOTelCollector` metrics can be found in the `AWSObservability/CloudWatchOTService` namespace. Ensure that your region is set to the region set for your cluster.

I can't find: `AWSOTelCollector metrics`

**Comment by vasireddy99** [comment]
Thank you so much for providing the context. 
The command field could be used to specify the path for collector config file Eg : `--config=/etc/ecs/container-insights/otel-task-metrics-config.yaml`.

**Comment by willarmiros** [comment]
Hi @dimitardanailov - can you clarify what your questions for X-Ray in particular are per the title of this issue? It seems your questions relate to using ADOT for metrics so far.
