### ISSUE TITLE
Running on On-Premise Windows

### ISSUE THREAD

**Issue by alextranzact** [aws-observability/aws-otel-collector#1388]
**Describe the question**
Is there a way to run this on Windows on-premise? 

**Steps to reproduce if your question is related to an action**
Follow the installation and running documentation on a windows on-premise or local machine. We have tried to build the msi locally, download, wget. The installation of the OTel Collector as a windows service is successful, but is unsuccessful in starting the service. 
Other info: We have also been successful in starting this in Docker on the same machines. 

![image](https://user-images.githubusercontent.com/110183736/181568990-e9584f02-4741-46d0-b397-6e704b2ded08.png)

![image](https://user-images.githubusercontent.com/110183736/181569176-f6c2ef00-120f-48a2-bd5f-c08c9a8947e3.png)

aws-otel-collector logs:

`{"level":"error","timestamp":"2022-07-27T12:03:02.289-0500","caller":"awsutil@v0.54.0/conn.go:139","message":"Unable to retrieve the region from the EC2 instance","kind":"exporter","data_type":"metrics","name":"awsemf","error":"EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: RequestError: send request failed\ncaused by: Get \"http://169.254.169.254/latest/dynamic/instance-identity/document\": dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.","stack":"github.com/open-telemetry/opentelemetry-collector-contrib/internal/aws/awsutil.GetAWSConfigSession\n\tgithub.com/open-telemetry/opentelemetry-collector-contrib/internal/aws/awsutil@v0.54.0/conn.go:139\ngithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsemfexporter.newEmfPusher\n\tgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsemfexporter@v0.54.0/emf_exporter.go:75\ngithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsemfexporter.newEmfExporter\n\tgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsemfexporter@v0.54.0/emf_exporter.go:102\ngithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsemfexporter.createMetricsExporter\n\tgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsemfexporter@v0.54.0/factory.go:63\ngo.opentelemetry.io/collector/component.CreateMetricsExporterFunc.CreateMetricsExporter\n\tgo.opentelemetry.io/collector@v0.54.0/component/exporter.go:117\ngo.opentelemetry.io/collector/service/internal/pipelines.createExporter\n\tgo.opentelemetry.io/collector@v0.54.0/service/internal/pipelines/pipelines.go:346\ngo.opentelemetry.io/collector/service/internal/pipelines.buildExporter\n\tgo.opentelemetry.io/collector@v0.54.0/service/internal/pipelines/pipelines.go:332\ngo.opentelemetry.io/collector/service/internal/pipelines.Build\n\tgo.opentelemetry.io/collector@v0.54.0/service/internal/pipelines/pipelines.go:216\ngo.opentelemetry.io/collector/service.newService\n\tgo.opentelemetry.io/collector@v0.54.0/service/service.go:68\ngo.opentelemetry.io/collector/service.(*Collector).setupConfigurationComponents\n\tgo.opentelemetry.io/collector@v0.54.0/service/collector.go:184\ngo.opentelemetry.io/collector/service.(*Collector).Run\n\tgo.opentelemetry.io/collector@v0.54.0/service/collector.go:215\ngo.opentelemetry.io/collector/service.(*windowsService).start.func1\n\tgo.opentelemetry.io/collector@v0.54.0/service/collector_windows.go:108"}
`

**What did you expect to see?**
When running on EC2 Windows instance, the installation and running of the OTel Collector is successful. We would expect to see similar results when installing and running on a local or on-premise (non EC2) machine. 

**Environment**
Local or on-premise Windows machines.

**Additional context**

**Comment by erichsueh3** [comment]
Can you share the Collector config please?

**Comment by Aneurysm9** [comment]
Please also confirm whether the `AWS_REGION` environment variable is set.  If not, please attempt to set that to the appropriate region.  The error indicated here should not be fatal unless the region is otherwise unable to be determined.

**Comment by bryan-aguilar** [comment]
Also, can you share what version of windows you are trying to run the collector on?
