### ISSUE TITLE
Inject the aws otel trace id in Tomcat access log using logback json format

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#1397]
Hello, I am using logback json format for Tomcat access log. What is the syntax to use for Tomcat access log  to inject the aws otel trace id since %X{trace_id} does not work for tomcat access log?

**Comment by vasireddy99** [comment]
Closing this issue as a duplicate - https://github.com/aws-observability/aws-otel-java-instrumentation/issues/198
