### ISSUE TITLE
otel-collector + AWS X-Ray: large gaps in tracing blocks

### ISSUE THREAD

**Issue by toddtarsi** [aws-observability/aws-otel-collector#1439]
I asked this elsewhere, but I thought the conversation might be more relevant here:

https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1130

It's strange to me that the large gap in tracing is at the end of a request rather than the beginning (I would assume beginning is cold start type stuff).

**Comment by mhausenblas** [comment]
Hey, ADOT PM here. Thanks for raising this @toddtarsi and as you've considered in your upstream issue already, best would be a support ticket (if you have Enterprise Support) so we can dive deep and you have correct expectations around SLAs. In general, the GitHub issues help in terms of visibility, so it's not a bad thing per se but we can only provide SLAs via the appropriate support channels and support via GitHub is on a best effort basis with timelines that can reach into the weeks.

**Comment by toddtarsi** [comment]
@mhausenblas - Thanks for responding! Totally makes sense. Open source works tends to be a bit of a running-headfirst-into-burnout type of situation. I just wanted to make a touchpoint for discussion. I'm happy to treat this as a passive, long-tail, possibly-never-resolved type of things.
