### ISSUE TITLE
AWS ECS hosted RabbitMQ sending metrics to Amazon Managed Prometheus

### ISSUE THREAD

**Issue by elasticdotventures** [aws-observability/aws-otel-collector#1444]
i'm struggling with the ECS + AWS OTel documentation, i've lost several days overwhelmed sifting through the myriad of not-relevant to my situation choices.    This is clear as mud. 

Specifically trying to connect a RabbitMQ running in ECS to AWS Prometheus (AMP).  The docs are highly fragmented, presume certain aspects (i.e. sample applications) that aren't relevant to my environment.   

My organization is using terraform to create/manage the ECS and this doesn't add any clarity / is a significant impediment to testing since none of the examples can be copied over 1:1.   
I've created the AWS IAM policy & roles.
I'm trying to use the sidecar approach, and I feel like I have no idea what I'm doing. 

I think the most coherent/relevant example is here:
https://github.com/aws-observability/aws-otel-collector/blob/main/examples/ecs/aws-prometheus/

I'm presently trying to figure out how to get the `ecs-ec2-adot-config.yaml` file to load into the aws-otel-collector docker container as a sidecar (in terraform)

I am hoping the aws-otel-collector will consume & relay the rabbitmq health / stats into AWS managed prometheus. 

I can access the prometheus format metrics at:
`curl -v -H "Accept:text/plain" "http://mq:15692/metrics"`

Below is an example of relevant terraform pieces, but I really don't know what to put into the `command`, and `environment` section -- i'm 99% sure those settings are wrong.  Will update this issue as I progress. 

The suggestion to modify --command came from here:
https://aws-otel.github.io/docs/setup/ecs/task-definition-for-ecs-ec2

all these examples presume a lot about the config, but I'm not even sure how to get the .yaml file inside the container.  maximum frustration. 

```
resource "aws_ecs_task_definition" "rabbitmq" {
  container_definitions = jsonencode([
    {
      name              = "mq"
      image             = "rabbitmq:3.10-management"
      ...
     },
        {
      name = "aws-otel-collector"
      image = "public.ecr.aws/aws-observability/aws-otel-collector:latest"
      execution_role_arn = aws_iam_role.execution_role.arn
      task_role_arn = data.aws_iam_role.OTelRole.arn
      command = "--config=/etc/ecs/container-insights/otel-task-metrics-config.yaml"
      essential = true
      logConfiguration : {
        logDriver = "awslogs"
        options = {
          awslogs-group = "/ecs/ecs-aws-otel-sidecar-collector"
          awslogs-region = var.region
          awslogs-stream-prefix = "rabbitmq-otel"
          awslogs-create-group = "true"
        }
      },
      environment : [
        {
          name = "PROMETHEUS_SAMPLE_APP",
          value = "prometheus-sample-app:8080"
        }
      ],
      links: [
        "mq"
      ],
      dependsOn: [
        {
          containerName = "prometheus-sample-app",
          condition = "START"
        }
      ]
    }
  ])
```

I really don't know what to do next.

**Comment by mhausenblas** [comment]
Heya @elasticdotventures, ADOT PM here. Thanks for raising this issue and I understand. We are working on addressing the docs issues and in the mean time: can you work with your TAM/account SA to resolve this? We can unfortunately only address issues here on GitHub on a best effort basis meaning that given the team size we're talking weeks if that makes sense?

**Comment by elasticdotventures** [comment]
figured a solution, using terraform to deploy config files to sidecar containers in ECS was a chore.
