### ISSUE TITLE
unexpected content-type error when exporting metrics and traced

### ISSUE THREAD

**Issue by vishnujanardhanan** [aws-observability/aws-otel-collector#1486]
Trying to setup and run adot collector with a java agent and push metrics and traces to opensearch via data prepper.

Error seen in the collector logs as below

{"level":"error","timestamp":"2022-09-14T15:57:40.069Z","caller":"exporterhelper/queued_retry.go:395","message":"Exporting failed. The error is not retryable. Dropping data.","kind":"exporter","data_type":"metrics","name":"otlp/data-prepper","error":"Permanent error: rpc error: code = Unimplemented desc = unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type \"text/plain; charset=utf-8\"","dropped_items":53,"stack":"go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send\n\tgo.opentelemetry.io/collector@v0.58.0/exporter/exporterhelper/queued_retry.go:395\ngo.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send\n\tgo.opentelemetry.io/collector@v0.58.0/exporter/exporterhelper/metrics.go:143\ngo.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1\n\tgo.opentelemetry.io/collector@v0.58.0/exporter/exporterhelper/queued_retry.go:206\ngo.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1\n\tgo.opentelemetry.io/collector@v0.58.0/exporter/exporterhelper/internal/bounded_memory_queue.go:61"}
{"level":"error","timestamp":"2022-09-14T15:58:40.069Z","caller":"exporterhelper/queued_retry.go:395","message":"Exporting failed. The error is not retryable. Dropping data.","kind":"exporter","data_type":"metrics","name":"otlp/data-prepper","error":"Permanent error: rpc error: code = Unimplemented desc = unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type \"text/plain; charset=utf-8\"","dropped_items":53,"stack":"go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send\n\tgo.opentelemetry.io/collector@v0.58.0/exporter/exporterhelper/queued_retry.go:395\ngo.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send\n\tgo.opentelemetry.io/collector@v0.58.0/exporter/exporterhelper/metrics.go:143\ngo.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1\n\tgo.opentelemetry.io/collector@v0.58.0/exporter/exporterhelper/queued_retry.go:206\ngo.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1\n\tgo.opentelemetry.io/collector@v0.58.0/exporter/exporterhelper/internal/bounded_memory_queue.go:61"}
<Aneurysm9: removed link potentially leaking credentials>

attaching the otel-config and data prepper config for reference.
[otel-config.txt](https://github.com/aws-observability/aws-otel-collector/files/9567989/otel-config.txt)

Running java application with aws adot agent on default configs.

Kindly help

**Comment by bryan-aguilar** [comment]
Can you please review the `pipeline.txt` file to ensure that it does not contain any valid credentials. If so please rotate those credentials immediately.

**Comment by rapphil** [comment]
can you share a redacted pipeline.txt again?

did you data-prepper pipeline contain both a `otel_trace_source` and a `otel_metrics_source`?
