### ISSUE TITLE
Update ECR Public repo metadata to add arm64 architecture

### ISSUE THREAD

**Issue by otterley** [aws-observability/aws-otel-collector#1496]
In the [ECR Public gallery listing](https://gallery.ecr.aws/aws-observability/aws-otel-collector) for aws-otel-collector, the following architectural support metadata is noted:

> OS/Arch: Linux, x86-64

Can you please update the metadata to include arm64 architecture support?

**Comment by bryan-aguilar** [comment]
Updated
