### ISSUE TITLE
Include the k8sattributesprocessor as part of ADOT 

### ISSUE THREAD

**Issue by drors55** [aws-observability/aws-otel-collector#1548]
I would like AWS ADOT to include the k8sattributesprocessor 
it is included in the REDHAT open shift distribution - https://github.com/os-observability/redhat-opentelemetry-collector/blob/main/manifest.yaml

Currently the instrumentation agent cannot extract labels attached on the POD

With OpenShift i can active the k8sattributesprocessor and the processor identifies my POD and add such lables
However for AWS ADOT there is no such solution

**Comment by mhausenblas** [comment]
ADOT PM here, thanks for the input. We're continuously reviewing components that could be added to ADOT, let me add this processor to the list of candidates and in case we've questions we get back to you here @drors55.

**Comment by aravind666** [comment]
@mhausenblas , thanks for considering this as a feature request, is there anything planned on this feature request?
