### ISSUE TITLE
Fargate CFN Example Issues

### ISSUE THREAD

**Issue by PettitWesley** [aws-observability/aws-otel-collector#159]
I was going through the CFN Fargate example here: https://aws-otel.github.io/docs/setup/ecs

I will detail all of the issues I found:
1. The command has `--template-body file:///<CFN_File_Downloaded>` which does not work, it should be something like `$(pwd)/${CFN_File_Downloaded}
2. The command tells you to set CreateIAMRoles to False, but you need to set it to True for it to work.
3. Once you fix the above two, the sample service is created but then it quits shortly after task launch. Due to the following logs:
```
Exception in thread "main" java.lang.RuntimeException: s3region is empty
```
```
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 4567: Connection refused
```

It looks like the version of the sample app used is out of date, I think it should be this instead: https://hub.docker.com/r/aottestbed/aws-otel-collector-java-sample-app/tags?page=1&ordering=last_updated

**Comment by PettitWesley** [comment]
I can probably help fix these... just wanted to detail them somewhere before I forget...

**Comment by PettitWesley** [comment]
Once I switched the latest/correct testbed image and added S3_REGION then it works

**Comment by mxiamxia** [comment]
Close this issue. The sample app in the template has been updated. @PettitWesley, pls help to confirm if you're ok to close this issue
