### ISSUE TITLE
Support for awscloudwatchlogs exporter

### ISSUE THREAD

**Issue by ggallotti** [aws-observability/aws-otel-collector#1614]
The [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib) supports awscloudwatchlogs exporter.

Will AWS OTEL Collector support this exporter?

**Comment by mhausenblas** [comment]
Hi @ggallotti, ADOT PM here. We plan to work on logs support upstream for the time being and once logs are stable, consider productizing it with this exporter as one potential candidate, yes. Currently, I don't have a timeline but will update this issue when we get closer to it.

**Comment by mhausenblas** [comment]
Shipped, see https://aws.amazon.com/about-aws/whats-new/2023/11/logs-support-aws-distro-opentelemetry/
