### ISSUE TITLE
Re-enable containerinsight_ecs_prometheus test case

### ISSUE THREAD

**Issue by straussb** [aws-observability/aws-otel-collector#1636]
In https://github.com/aws-observability/aws-otel-collector/pull/653/ the `containerinsight_ecs_prometheus` test case was removed pending https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5373 .  A workaround has now been suggested there.  ADOT developers should evaluate whether the workaround is viable and implement if so, and re-enable the test case as well.

**Comment by vasireddy99** [comment]
Thanks for creating this issue to track and providing more info. The workaround suggested seems to be valid, but may not be viable for ADOT to add the test case, hence will be tracking towards the fix in upstream.

**Comment by PaurushGarg** [comment]
The relevant PR (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21680) of this scope has been merged to `opentelemetry-collector-contrib` and the feature shall be available with the next release of `contrib` and the corresponding release of ADOT Collector.

**Comment by PaurushGarg** [comment]
Closing this issue as the `ecs_observer` testcase has been enabled (https://github.com/aws-observability/aws-otel-collector/pull/2227) and the relevant PR (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21680) for the ecs_observer fix has been merged.
