### ISSUE TITLE
OTEL adot-collector stopped working "error reading processors configuration for "cumulativetodelta": 1 error(s) decoding:"

### ISSUE THREAD

**Issue by rishiporwal322** [aws-observability/aws-otel-collector#1642]
**Describe the question**
adot-collector pod suddenly stopped working for all prod and non prod environment and in crash loop back state.

no action taken from our end. All of sudden after a particular time, it stopped working for all dev, test and prod environment.

Followed steps as per below doc and applied yaml file mentioned in the article

https://aws.amazon.com/blogs/containers/introducing-amazon-cloudwatch-container-insights-for-amazon-eks-fargate-using-aws-distro-for-opentelemetry/
 

**Additional context**
When trying to restart, its failing with below error

2022/11/16 12:46:25 ADOT Collector version: v0.23.0
2022/11/16 12:46:25 found no extra config, skip it, err: open /opt/aws/aws-otel-collector/etc/extracfg.txt: no such file or directory
Error: failed to get config: cannot unmarshal the configuration: error reading processors configuration for "cumulativetodelta": 1 error(s) decoding:

* '' has invalid keys: metrics
2022/11/16 12:46:25 application run finished with error: failed to get config: cannot unmarshal the configuration: error reading processors configuration for "cumulativetodelta": 1 error(s) decoding:

* '' has invalid keys: metrics

**Comment by bryan-aguilar** [comment]
You most likely have an outdated config file. In upstream release [`v0.57.2`](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.57.2) the configuration fields for that processor were changes. See this [PR](https://github.com/aws-observability/aws-otel-collector/commit/a527132f9c432723f9c40813e13cf428305fc506) for an example on how to update your config.

**Comment by bryan-aguilar** [comment]
The upstream docs may also be helpful. [Here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/release/v0.61.x/processor/cumulativetodeltaprocessor) is the readme for the `cumulative to delta` processor at `v0.61.x`. Unfortunately the README for `v0.62.x` release , which is the release included in ADOT Col `v0.23.0`, upstream does not appear to be available.

**Comment by bryan-aguilar** [comment]
The comments above should give you the solution to fix errors in your config. Please reopen this issue or create a new one if you have additional questions.

**Comment by rishiporwal322** [comment]
Thanks alot Bryan, that was the issue. We are able to fix it using new updated config file.
