### ISSUE TITLE
AWS otel collector on EC2 

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#1693]
Hello, 
I am pushing some custom metrics using statsd and otel collector to aws cloudwatch in my custom namespace.

Case 1) When my ec2 instance host name is : hostname-test.com, i see my custom metrics getting pushed to **instanceid, host dimension** in my custom namespace.

Case 2) When my ec2 instance host name is : hostname-${aws_instanceid}-test.com, i see my custom metrics getting pushed to **instanceid dimension** in my custom namespace.

Could you clarify?

**Comment by bryan-aguilar** [comment]
Can you please share a complete collector config?
