### ISSUE TITLE
Add loadbalancing exporter

### ISSUE THREAD

**Issue by yeya24** [aws-observability/aws-otel-collector#1743]
**Is your feature request related to a problem? Please describe.**
[Loadbalancing exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/loadbalancingexporter/README.md) is usually required to enable tail sampling with multiple Otel collector replicas. 

A common scenario is that we deploy the Otel collector with multiple replicas. To make sure we route all spans of the same trace to the same Otel collector pod, we need to use the loadbalancing exporter. Otherwise we cannot achieve tail sampling.

**Describe the solution you'd like**
Add loadbalancing exporter to ADoT.

**Comment by yeya24** [comment]
not stale

**Comment by SodaDev** [comment]
Hi guys, is there any estimated time when we can expect it to be part of ADOT?

**Comment by mhausenblas** [comment]
@SodaDev with the next release

**Comment by mhausenblas** [comment]
This is now available with [v0.32.0](https://github.com/aws-observability/aws-otel-collector/releases/tag/v0.32.0), see also the docs entry https://aws-otel.github.io/docs/getting-started/advanced-sampling#scaling-with-advanced-sampling for more details.
