### ISSUE TITLE
Is there a way to watch the credentials file?

### ISSUE THREAD

**Issue by jdmarshall** [aws-observability/aws-otel-collector#1744]
**Describe the question**

For developer workflows I am finding that telemetry data gets silently dropped if your AWS session times out. While that's generally a solved problem in a deployed environment, it can cause some issues with developer sandboxes. Particularly because opentelemetry code seems to prefer failing silently rather than warning that statistics are no longer being aggregated.

**Steps to reproduce if your question is related to an action**

Let aws login expire, update meters, observe no stats reported

Log back in, update more meters, stats continue to be dropped

**What did you expect to see?**
A flag or configuration option to detect updates to the credentials file and apply them.

**Environment**
Running aws-otel-collector from a docker-compose.yml pointing at 
```
  opentelemetry:
    ...
    volumes:
      - ~/.aws:/root/.aws

```

**Additional context**

**Comment by jdmarshall** [comment]
I'm sure I can work out some clever way to run my own watch command to restart on ~/.aws modification but I'm wondering if there's a baked solution available or simple enough to implement.

**Comment by rapphil** [comment]
Hi, I wanted to clarify if you are refreshing the credentials in `~/.aws` in the host? are you?

```
    volumes:
      - ~/.aws:/root/.aws
```
This is a bind mount and therefore updates in the host should be propagated to the container.

Can you share what services your collector is interacting with?

**Comment by rapphil** [comment]
I just confirmed that it is not possible to use `~/.aws/credentials` in a workflow in which the file gets updated with new credentials. 

This is the default behavior of the AWS SDK across several languages. The issue is that `~/.aws/credentials` is supposed to store static credentials, and not temporary ones. I don't think changing the collector to work around this issue is the correct approach though.

More details can be found here: https://github.com/aws/aws-sdk-go/issues/1993

references: https://docs.aws.amazon.com/sdkref/latest/guide/feature-static-credentials.html

**Comment by rapphil** [comment]
How are you refreshing your `~/.aws/credentias`

**Comment by jdmarshall** [comment]
Yes it's in a development setup. We have a little script to call AWS login and prompt for roles.  

I may have to ask about longer lived tokens. As this code currently behaves I can't really roll it out to our dev team at large.

**Comment by rapphil** [comment]
If I understood correctly you are already using SSO. Is that correct? Can you confirm what method you are using here? https://docs.aws.amazon.com/sdkref/latest/guide/feature-sso-credentials.html ?

SSO token provider configuration 
or 
Legacy non-refreshable configuration
?

**Comment by jdmarshall** [comment]
I don't have a lot of visibility into the system, but given the behavior, it's refreshable tokens. It only asks for my password if I haven't run it in quite some time. Otherwise it just asks what role I'm after.
