### ISSUE TITLE
[ci/cd] Ensure MSI version is incremented before each release 

### ISSUE THREAD

**Issue by bryan-aguilar** [aws-observability/aws-otel-collector#1765]
The [version](https://github.com/aws-observability/aws-otel-collector/blob/44ef0a632208c8b8ff79b6a838e75c6bbb915863/tools/packaging/windows/aws-otel-collector.wxs#L6) in the MSI packaging does not reflect the actual version of the collector. This should match the version of the released collector. 

Also, this should be a check that is done during the CD process. The CD should not release assets if this version does not match the value in [VERSIONS](https://github.com/aws-observability/aws-otel-collector/blob/main/VERSION)(minus the `v`) the preflight step should be added in the CD workflow [here](https://github.com/aws-observability/aws-otel-collector/blob/44ef0a632208c8b8ff79b6a838e75c6bbb915863/.github/workflows/CD.yml#L45).

**Comment by Kausik-A** [comment]
Also make sure to introduce `delayed start time` with reference to the issue [here ](https://github.com/golang/go/issues/23479)

**Comment by Kausik-A** [comment]
Agree, tracking it in #1767
