### ISSUE TITLE
[windows][CI/CD] ADOT collector delayed start

### ISSUE THREAD

**Issue by Kausik-A** [aws-observability/aws-otel-collector#1767]
**Describe the bug**
Sets ADOT collector agent as Automatic (delayed start) services to mitigate known go windows issues with 1.9.2: https://github.com/golang/go/issues/23479

Services would not restart across reboots on Automatic services, they would timeout before coming up and the service control manager would give up spawning them. This workaround will be reverted back once's it is believed to addressed in the future golang releases

**Comment by Kausik-A** [comment]
Updates:

ADOT collector agent has been crashing sometimes at windows system reboot. This behaviour has been experienced by other projects and it seems to be a bug in golang. The issue is currently being tracked https://github.com/golang/go/issues/23479

Testing

This issue has been tough to replicate as it is a probabilistic failure which occurs to some windows instances from a large fleet of machines. This limitation on not able replicate the issue every-time has been mentioned on the linked issue too. SO we need to come up with a testing strategy to set up a mock env with these condition to run across these failures.

Proposed Solution

Out of all proposed workaround mentioned in the issue thread, one approach found that having delayed start to the application has decreased the probability of the agent failing to start up (Still not 0% but better than before ).This is implemented in #1788 .  Considering this change just delays the start of the ADOT collector, it has a comparatively low blast radius/affect on our customer.
Also additionally have some more investigation into other possible solutions.

**Comment by javasorn** [comment]
I using a  WinSW to handling service ADOTCollector service. Its working in windows-aws-ecs-fargate.

https://github.com/aws-observability/aws-otel-collector/pull/1788#issuecomment-1428855205
