### ISSUE TITLE
Ability to detect and load configuration changes at runtime

### ISSUE THREAD

**Issue by venkivijay** [aws-observability/aws-otel-collector#1774]
**Is your feature request related to a problem? Please describe.**
Collector should be able to detect changes in the configuration file at runtime. This would enable making modifications to the pipeline (like changing a processor value) while the collector is running. 

**Describe the solution you'd like**
Watch the configuration file for changes and load new values dynamically. New configs will only be applied if the config file is valid.

**Additional context**
In k8, when a change is made to configmap it will be available to the collector. But since the collector cannot detect the change, pod restart is required which is not an optimal solution. There are ways to handle this at the k8 level, but I think the collector must be smart enough to load new configs as soon as they are available.

**Comment by venkivijay** [comment]
@mhausenblas Please let us know if there are any updates on this request.

**Comment by mhausenblas** [comment]
It's something that is on our roadmap for the mid to long run. The way we want to approach this is via [OpAMP](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/opampsupervisor/specification/README.md), where the supervisor controls the collector and with it watch/hot-reloads.
