### ISSUE TITLE
Support Loki Exporter

### ISSUE THREAD

**Issue by andrewthauer** [aws-observability/aws-otel-collector#1776]
We would like to see support for the [Loki Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/lokiexporter) in the `aws-otel-collector` distribution.

**Comment by mhausenblas** [comment]
Thanks for the feature request @andrewthauer and please note that ADOT does not support logs currently (see https://github.com/aws-observability/aws-otel-community/issues/11 for details) so we will review this issue when we get to this signal type (not before H2/2023).

**Comment by andrewthauer** [comment]
Still interested in this.

**Comment by mhausenblas** [comment]
@andrewthauer still the same status, we do not yet support logs in ADOT.

**Comment by loafoe** [comment]
@mhausenblas @andrewthauer  it looks like `v0.34.0` has support for logs? At least it mentions cloudwatchlog exporter support. Should this be re-opened or can we create a new item?

**Comment by mhausenblas** [comment]
@loafoe is OTLP exporter for Loki an option?

**Comment by loafoe** [comment]
@mhausenblas yes definitely! A release with this exporter bundled would allow us to start using ADOT for our lambda setup 💯
