### ISSUE TITLE
Enable support for Service graph processor

### ISSUE THREAD

**Issue by dngferreira** [aws-observability/aws-otel-collector#1780]
**Is your feature request related to a problem? Please describe.**
We use Grafana for most of our logs and metrics, we are evaluating sending also traces to get a complete view of our distributed system.

**Describe the solution you'd like**
Import Service graph processor and enable it on adot collector

**Describe alternatives you've considered**

**Additional context**
We are currently using EKS addon

**Comment by vsakaram** [comment]
Thanks for creating this issue - please note this is not currently not in our plan but we will revisit in the future
