### ISSUE TITLE
Broken links for ECS and EKS in the docs

### ISSUE THREAD

**Issue by awsimaya** [aws-observability/aws-otel-collector#1797]
**Describe the bug**
Broken docs link for the following:
[Run it with ECS](https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/ecs-demo.md)
[Run it with EKS](https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/eks-demo.md)

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**Environment**
Describe any aspect of your environment relevant to the problem. 
If this is related to a deployment of the ADOT Collector please
provide your Collector config file. 

**Additional context**

**Comment by vasireddy99** [comment]
> @vasireddy99 I believe you had removed these docs right? 

Yes, I those docs are removed. I will edit the links to redirect to website. Assign this to me
