### ISSUE TITLE
Ability to set tags on CloudWatch log group when using awsemf exporter

### ISSUE THREAD

**Issue by lorelei-rupp-imprivata** [aws-observability/aws-otel-collector#1813]
**Is your feature request related to a problem? Please describe.**
When using awsemf exporter, aws-otel automatically creates CloudWatch Log group. The resulting log group doesn't have any tags set, for cost purposes we want to set tags on this.

**Describe the solution you'd like**
Create a field like tags on [aws emf config section](https://aws-otel.github.io/docs/getting-started/cloudwatch-metrics#cloudwatch-emf-exporter-awsemf).

**Describe alternatives you've considered**
We could manually configure this but we set a lot of tags for our environments and we have many environments

This should be very similar to implement to https://github.com/aws-observability/aws-otel-collector/issues/991 I would imagine

**Comment by vsakaram** [comment]
Thanks for creating this issue. We shall plan to work on this in upstream.

**Comment by humivo** [comment]
I am currently working on the PR for this issue [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19406), and looking to edit the PR to be merged in soon.

**Comment by humivo** [comment]
The [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19406) for this issue has just been approved and merged and so the feature will be available in the next release!
