### ISSUE TITLE
Is it possible to use S3 hosted config

### ISSUE THREAD

**Issue by hgenchev99** [aws-observability/aws-otel-collector#1814]
**Describe the question**
Is it possible to use a configuration file stored in S3 and dynamically loaded before the container is started?

**What did you expect to see?**
If the answer is `yes` then how to accomplish that? 
If the answer is `not` then why wouldn't this be a nice feature? This will allow us not to build additional images on top of this one when we need 3rd party vendors.

**Comment by mhausenblas** [comment]
@hgenchev99 thanks for creating this issue. This is currently not yet supported but on our short-term roadmap.

**Comment by jufemaiz** [comment]
💯 good move to get it going!

**Comment by rapphil** [comment]
Hi, I would like to inform that support to the S3 confmap provider was added in the ADOT collector v0.28.0

For more details, please take a look in:
https://aws-otel.github.io/docs/components/confmap-providers

**Comment by rapphil** [comment]
Closing ticket as this was addressed.
