### ISSUE TITLE
Step Function Traces 

### ISSUE THREAD

**Issue by anthonyangel** [aws-observability/aws-otel-collector#1845]
**Describe the question**
Is it possible to intercept Step Function xray traces so that they can be shipped to a 3rd party platform? (Honeycomb). It looks like the otel collector intercepts the xray traces in-flight (defaulting to UDP:2000), but the link from Step Functions to xray is something of a black box.

Presumably this would require an alternative receiver which should scrape the xray API.

**Comment by darkmastermindz** [comment]
@willarmiros Interested in learning more about this issue and figuring out a viable solution in the meantime. Looking into a viable workaround, does Step Function Traces with Xray still get shipped and exported with the previous information in XRay to OTel via ADOT lambda layer afterwards if step function calls this lambda function last?

**Comment by wangzlei** [comment]
Could you elaborate your question and idea? 
In theory, all X-Ray integrated AWS services (should) support trace context passthrough. 
For example:
Client -> AWS -> B service, if tracing is disabled in AWS, the trace context of Client will be passed to B service.

Some old X-Ray integrated AWS services may not support this true passthrough, but the new integrated services should be good.

**Comment by rberger** [comment]
So is there a way to get tracing info from Step Functions into the Otel collector? We're about to adopt Step Functions in a major way and just realized its not obvious how to have Step Functions participate in an Otel trace.

**Comment by wangzlei** [comment]
Unfortunately, AWS managed services don't support user runs an OTel collector in its instance. Alternatively, user can transfer StepFunction trace data from xray to 3rd party service.
At this moment XRay only supports X-Ray native trace data model, user has to translate xray data to match with 3rd party service. 
Translation please refer to:
XRay -> OTel  https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/awsxrayreceiver
OTel -> XRay  https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awsxrayexporter

**Comment by rberger** [comment]
Thanks, will look into that.  I had seen the XRay -> Otel [awsxrayreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/awsxrayreceiver) but I'll have to dig in to figure out how to use it. Its not clear how to get just what I want (step-function transitions) from X-Ray via that mechanism
