### ISSUE TITLE
Support for Datadog Receiver - OpenTelementry contrib 0.71.0

### ISSUE THREAD

**Issue by Arvindh-Mojo** [aws-observability/aws-otel-collector#1852]
**Describe the question**
With the recent opentelementry release 0.71.0, it supports `datadog` receivers. Was wondering if you guys have plan to support that as once of the receiver in the aws-otel-collector distribution. 

**What did you expect to see?**
`aws-otel-collector` to support `datadog receiver`

**Comment by mhausenblas** [comment]
Thanks for the feature request, noted. Currently we don't have plans to add this receiver to the collector.
