### ISSUE TITLE
Docker-demo doesn't work

### ISSUE THREAD

**Issue by losnappas** [aws-observability/aws-otel-collector#187]
Hello,

https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/docker-demo.md isn't working

`Pulling ot-sample-app (mxiamxia/aws-otel-collector-java-sample-app:0.4.0)...
ERROR: pull access denied for mxiamxia/aws-otel-collector-java-sample-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

On docker hub I can find `aottestbed/aws-otel-collector-java-sample-app`, is that legit? Not gonna bleed my aws credentials to someone with that, am I?

**Comment by mxiamxia** [comment]
Hi @losnappas , I updated our Docker example. The right test sample image should be  `aottestbed/aws-otel-collector-java-sample-app:0.4.0`. 

The  image source code is below. It's a pretty simple sample app. You can also take a look the code and build your own image if you have the concern. Any feedback would be appreciated. Thanks.
* https://github.com/aws-observability/aws-otel-test-framework/tree/terraform/sample-apps/spark
