### ISSUE TITLE
Health check command on ECS

### ISSUE THREAD

**Issue by dtykocki** [aws-observability/aws-otel-collector#2034]
For deploying the otel-collector to ECS, should the `healthCheck` `command` config be `["/healthcheck"]` or `["CMD-SHELL", "curl -f http://127.0.0.1:13133/ || exit 1"]`. Can either be used? Is there a difference between them? I couldn't find any documentation on this aspect so I'm little bit confused as to what config should be used.

❤️ ❤️ Appreciate the work you all are doing on this project ❤️ ❤️

**Comment by bryan-aguilar** [comment]
For deploying on ECS specifically the health check command should be set to `["/healtcheck"]`. The second option cannot be used because the collector docker image is built with a `SCRATCH` base image and thus does not contain a shell or curl.

**Comment by dtykocki** [comment]
That makes sense. Thank you very much!
