### ISSUE TITLE
Warning: ADOT Collector v0.31.0 breaking change

### ISSUE THREAD

**Issue by bryan-aguilar** [aws-observability/aws-otel-collector#2043]
The ADOT team is aware of a breaking change made in [`v0.76.3`](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.76.3) of the upstream OpenTelemetry collector-contrib package. This breaking change affects users of the `prometheus` and `prometheusremotewrite` exporter. Starting in version `v0.76.3` the `pkg.translator.prometheus.NormalizeName` feature gate is enabled by default. The enabling of this feature gate results in the exporter using full prometheus metric name normalization rather than simple normalization. To read more about metric name normalization please refer to the normalization package documentation [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/translator/prometheus). 

The enabling of this feature gate could result in a change to the metric names exported by Collector metric pipelines using the `prometheus` receiver,`prometheusremotewrite` exporter, or `prometheus` exporter. 

The ADOT team has made the decision to return the default state of this feature gate to disabled in ADOT Collector minor versions `v0.29.x` and `v0.30.x`. This will set the prometheus and prometheusremotewrite exporter to use simple metric name normalization by default. 

Full metric name normalization can still be enabled by providing the `--feature-gates=+pkg.translator.prometheus.NormalizeName` flag at startup. 

We **highly advise** that testing is done to determine if you are affected by this change before ADOT Collector release `v0.31.0` is released. 

Please feel free to ask any questions!

**Comment by bryan-aguilar** [comment]
The ADOT team is actively investigating on whether or not this should be a configurable behavior in the listed components. Please see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21743 issue upstream on updates.

**Comment by rapphil** [comment]
To enable the feature flag in ec2 instances, you have to update the `/opt/aws/aws-otel-collector/etc/.env` manually to add the `--feature-gates=+pkg.translator.prometheus.NormalizeName`

The content should look like 
```
config="--config /opt/aws/aws-otel-collector/etc/config.yaml --feature-gates=+pkg.translator.prometheus.NormalizeName" 
```

To enable the feature flag in EC2 and ECS, you can pass the `--feature-gates=+pkg.translator.prometheus.NormalizeName` as a container argument/command line parameter.
