### ISSUE TITLE
More detailed error output on Windows wrapper

### ISSUE THREAD

**Issue by jlosito** [aws-observability/aws-otel-collector#2092]
**Is your feature request related to a problem? Please describe.**
I'm trying to figure out why ADOT won't start on a Windows machines. The output doesn't tell me much information as to why it isn't starting. When it fails, all that is stated is that the service could not be started without detailed information.

**Describe the solution you'd like**
It would much nicer if the output stated why the service failed to start. For example, it would be helpful to know whether it's a configuration issue, a lack of privileges, etc.

**Comment by rapphil** [comment]
Hi, 

The logs of the collector on windows are located on:
```
C:\ProgramData\Amazon\AWSOTelCollector\Logs
```

Can you check if the log contains any errors indicating why the collector won't start for you?
