### ISSUE TITLE
[AWS Lambda Java] How to use custom collectors with aws-otel-collector

### ISSUE THREAD

**Issue by pradeepkusingh** [aws-observability/aws-otel-collector#2134]
**Describe the question**
A clear and concise description of what the question is.
I am using java and nodejs to build my AWS serverless lambdas, and trying to use a custom Kinesisexport collector to process the OTEL data. I would like to understand how to use custom exporters with the AWS Otel collectors or AWS hotel collector already provided the Kinesis exporters?

**Steps to reproduce if your question is related to an action**
If possible, provide a recipe for reproducing the what the question relates to.

- How to export the hotel metrics to Kinesis using an existing or custom exporters?

**What did you expect to see?**
Data being ingested in Kinesis.

**Environment**
Describe any aspect of your environment.
If this is related to a deployment of the ADOT Collector please
provide your Collector config file. 

**Additional context**

**Comment by vsakaram** [comment]
Thanks for reaching out however ADOT currently does not support Kinesis Exporter.
