### ISSUE TITLE
XRAY Status: error

### ISSUE THREAD

**Issue by atnsun** [aws-observability/aws-otel-collector#2138]
Xray 1.6.4 (Xray, Penetrates Everything.) 2942f56 (go1.19.3 linux/amd64)
A unified platform for anti-censorship.
[Info] infra/conf/serial: Reading config: bin/config.json
Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: unable to listen on domain address: 1

Are you able to tell me what shoud we do?

**Comment by vsakaram** [comment]
Please create above issue in this repo - https://github.com/XTLS/Xray-core, thanks.
