### ISSUE TITLE
Tools Packaging windows create_msi.ps1 fails to run successfully

### ISSUE THREAD

**Issue by JaieParker** [aws-observability/aws-otel-collector#2139]
**Describe the bug**
I tried following instructions here: https://aws-otel.github.io/docs/setup/build-collector-on-windows

![image](https://github.com/aws-observability/aws-otel-collector/assets/6509093/2c2af2c9-3934-4834-8f54-67cb36503ed2)

**Steps to reproduce**
Try following the steps: https://aws-otel.github.io/docs/setup/build-collector-on-windows

Note: I had another error re create_msi.ps1 "mkdir -p .\build\packages\windows\amd64\" which said it was abiguous, but this is fixed by by changing the script to "mkdir -path .\build\packages\windows\amd64\" which I assume is the intended action
I dont know anything about WiX so not sure how to fix the second error.

**What did you expect to see?**
A successful install and creation of a msi.

**What did you see instead?**
C:\Program Files\Git\aws-otel-collector\tools\packaging\windows\aws-otel-collect
or.wxs(62) : error LGHT0103 : The system cannot find the file './build/windows/a
md64/aoc'.
mv : Cannot find path 'C:\Program
Files\Git\aws-otel-collector\aws-otel-collector.msi' because it does not exist.
At C:\Program
Files\Git\aws-otel-collector\tools\packaging\windows\create_msi.ps1:24 char:1
+ mv aws-otel-collector.msi .\build\packages\windows\amd64\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...l-collector.m
   si:String) [Move-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveI
   temCommand

**Environment**
AWS EC2 instance t2.medium

**Additional context**
First time install on enviroment

**Comment by rapphil** [comment]
Hi, 

Using the pre built and published msi would work for you? https://github.com/aws-observability/aws-otel-collector/releases/tag/v0.30.0

Regarding your question, 
What is wrong with the script is that it expects the binary for the collector to exist. Unfortunately you can only build the windows version of the collector on a Linux machine. So to build it locally for windows, you need to first compile the binary on Linux with
```
make build
```
And then switch copy over the binary to the windows machine in the directory expected by the script.
```

**Comment by fibanez** [comment]
Hi, 
If you still need to build this yourself, you are able to do it on windows.  Here are the steps: 

# Install Chocolatey if not already installed 
choco install make git go 
git clone https://github.com/aws-observability/aws-otel-collector.git  
cd aws-otel-collector
make windows-build
.\tools\packaging\windows\create_msi.ps1
