### ISSUE TITLE
otel-fargate-container-insights.yaml is missing coverage for built-in Container Insights Dashboards

### ISSUE THREAD

**Issue by apmclean** [aws-observability/aws-otel-collector#2161]
**Describe the bug**
otel-fargate-container-insights.yaml is missing coverage for built-in Container Insights Dashboards.

**Steps to reproduce**
- Follow: https://aws-otel.github.io/docs/getting-started/container-insights/eks-fargate.
- Load `Container Insights` from the CloudWatch console.  About 80% of dashboards have no data.  As a simple example - built-in container insights dashboards uses metric name `pod_cpu_utilization` which is not produced by `otel-fargate-container-insights.yaml`.

**What did you expect to see?**
Expect all Dashboards in Container Insights within the AWS Console to have populated data.

**What did you see instead?**
Network Traffic populates along with cluster level CPU and Memory utilization.  Everything else is empty with no data.

**Environment**
Fargate-only EKS cluster with https://aws-otel.github.io/docs/getting-started/container-insights/eks-fargate applied.

**Additional context**
None

**Comment by apmclean** [comment]
Comment to remove staleness.

**Comment by gkontos-st** [comment]
I've seen the same issue.  Applying [otel-fargate-container-insights.yaml](https://raw.githubusercontent.com/aws-observability/aws-otel-collector/main/deployment-template/eks/otel-fargate-container-insights.yaml) several metrics are empty on the insights dashboard.  On the Performance Monitoring -> EKS Pods dashboard the pod_cpu_utilization and pod_memory_utilization are empty.  On the Performance Monitoring -> EKS Nodes dashboard, all are empty.  

It seems that the node level metrics are missing so the pod_cpu_utilization cannot be calculated.

**Comment by apmclean** [comment]
> It seems that the node level metrics are missing so the pod_cpu_utilization cannot be calculated.

According to this blog cAdvisor is running on EKS Fargate Nodes and could supply the information needed for the calculation if scraped by OTEL.

[https://aws.amazon.com/blogs/containers/monitoring-amazon-eks-on-aws-fargate-using-prometheus-and-grafana/](https://aws.amazon.com/blogs/containers/monitoring-amazon-eks-on-aws-fargate-using-prometheus-and-grafana/)
