### ISSUE TITLE
ecs-demo.md references missing CloudFormation templates

### ISSUE THREAD

**Issue by rbeede** [aws-observability/aws-otel-collector#218]
https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/ecs-demo.md

References under Install AWSOTelCollector on ECS EC2 to use the curl command but the .template files just result in a 404.

`curl -O https://github.com/mxiamxia/aws-opentelemetry-collector/blob/master/deployment-template/ecs/aws-otel-ec2-sidecar-deployment-cfn.template`

`curl -O https://github.com/mxiamxia/aws-opentelemetry-collector/blob/master/deployment-template/ecs/aws-otel-fargate-sidecar-deployment-cfn.template`

**Comment by JohnWu20** [comment]
Updated the file:
https://github.com/aws-observability/aws-otel-collector/pull/220
