### ISSUE TITLE
Unable to get the "otelcol" service to start while using ADOT base docker image

### ISSUE THREAD

**Issue by sap-ray** [aws-observability/aws-otel-collector#2180]
**Describe the question**
Unable to get the "otelcol" service to start while using Debian base docker image.

**Steps to reproduce if your question is related to an action**
root@xxxxx:/etc/otelcol# systemctl status otelcol
otelcol.service - OpenTelemetry Collector
    Loaded: loaded (/usr/lib/systemd/system/otelcol.service, enabled)
**Active: inactive (dead)**
root@a6338ad015e4:/etc/otelcol# systemctl start  otelcol
root@a6338ad015e4:/etc/otelcol# systemctl status otelcol
otelcol.service - OpenTelemetry Collector
    Loaded: loaded (/usr/lib/systemd/system/otelcol.service, enabled)
**Active: active (running)**

**What did you expect to see?**
Expect otelcol to be active/running while we build it using Dockerfile.
[config.txt](https://github.com/aws-observability/aws-otel-collector/files/11887186/config.txt)

**Environment**
Describe any aspect of your environment.
config.yaml attached
If this is related to a deployment of the ADOT Collector please
provide your Collector config file. 

**Additional context**
```[tasklist]
### Tasks
```

**Comment by rapphil** [comment]
Hi,

Can you clarify what you are trying to achieve?  Why do you need to use a debian image and install the collector on top of it? Can't you use the image that we publish and maintain and create a separated container?


If you really need to use the Debian base docker image:
* Can you share what image are you using?
* Can you show how did you install the collector in this case?

**Comment by sap-ray** [comment]
Our plan/intention is to send metrics to backend Dynatrace using OTEL collector.
We created ECS fargate implementation, while using the default aws-otel-collector image the ECS TASK stays stable.
While using "Dockerfile" to pass the "otel-config.yaml " we are getting error and the TASK's are draining out/flapping.
Receiving error in ESC TASK logs: ====unknown command "/bin/sh" for "otelcol-contrib"===
We are unable to shell into the aws-otel-collector to check the logs therefore tried to use Debian implementation.

Do let us know suitable implementation pattern for our use case.

Content of Dockerfile:
=========================
FROM aws-otel-collector:v0.27.1
COPY otel-config.yaml /etc
ENV RUN_IN_CONTAINER="True"
# aws-sdk-go needs $HOME to look up shared credentials
ENV HOME=/root
ENTRYPOINT ["/awscollector"]
CMD ["--config=/etc/otel-config.yaml"]
EXPOSE 4317 55681 2000

**Comment by sap-ray** [comment]
Also how we can send metrics to the collector from things we can't put an endpoint on? We would like to report response times from portions of code within a synthetic canary. We also need to send metrics to the collector from other things that can't support an endpoint like SaaS vendors and other custom metrics from application programs.
We are looking for a use case to cater above requirements.

**Comment by bryan-aguilar** [comment]
Hi, 

It is still not clear why you are trying to define a custom dockerfile instead of using the supported ADOT Images. When using the official ADOT images what errors were you receiving? How were you providing your custom configuration? 

Have you seen the ADOT Docs on providing a [custom configuration through an SSM Parameter](https://aws-otel.github.io/docs/setup/ecs/config-through-ssm)?

**Comment by sap-ray** [comment]
Thanks for the above link, I am now trying with the guidelines provided in the link.

**Comment by sap-ray** [comment]
I was able to implement the steps mentioned in link : https://aws-otel.github.io/docs/setup/ecs/config-through-ssm
However when I provision the ECS-Fargate using the AWS ADOT image my ECS TASK flaps continiously with below message: 
2023-07-10T11:34:16.102Z	info	otelcol/collector.go:236	Received signal from OS	{
    "signal": "terminated"
}
2023-07-10T11:34:16.103Z	info	service/service.go:166	Starting shutdown...
2023-07-10T11:34:16.103Z	info	extensions/extensions.go:55	Stopping extensions...
2023-07-10T11:34:16.103Z	info	service/service.go:180	Shutdown complete.
