### ISSUE TITLE
Example Prometheus config does not set "instance" metric label properly

### ISSUE THREAD

**Issue by JensRantil** [aws-observability/aws-otel-collector#2182]
**Describe the bug**
The [example Prometheus config](https://github.com/aws-observability/aws-otel-collector/blob/031cafa99b3b10ff24d93d9fbafc09604e98bce4/config/ecs/ecs-amp-prometheus.yaml) does not set "instance" metric label properly when submitting to Prometheus. This means that the config isn't useful if you have more than once ECS instance.

**Steps to reproduce**
Start the collector with the linked config above.

**What did you expect to see?**
That each metric from every sidecar has a unique "instance" metric label. Could task ID, task ARN, IP adress or something else.

**What did you see instead?**
The "instance" metric label is always set to `$AWS_PROMETHEUS_SCRAPING_ENDPOINT`.

**Environment**
Config file: https://github.com/aws-observability/aws-otel-collector/blob/031cafa99b3b10ff24d93d9fbafc09604e98bce4/config/ecs/ecs-amp-prometheus.yaml

**Comment by rapphil** [comment]
Hi,

Adding an `instance` label will lead to high cardinality metrics, which will lead to high cost in the storage. That is why we usually don't include a label that identify the instance that wrote that metric to the backend.

Can you share why it is important for you to identify the instance that generated a metric?

**Comment by Aneurysm9** [comment]
> The "instance" metric label is always set to $AWS_PROMETHEUS_SCRAPING_ENDPOINT.

Do you mean the literal string `$AWS_PROMETHEUS_SCRAPING_ENDPOINT` or the value of the environment variable `AWS_PROMETHEUS_SCRAPING_ENDPOINT`?  The former sounds like the correct behavior for a static configuration targeting that endpoint.  If you're running the collector as a sidecar and using `127.0.0.1` in that environment variable then you will need to provide additional uniquely identifying information such as the task ARN via a relabeling rule or through another mechanism such as the `ecs` resource detector and `resource_to_telemetry_conversion` in the PRW exporter.  The resource detector-based approach is used in the linked configuration.  Is that not functioning as expected?
