### ISSUE TITLE
Send metrics to the ADOT collector 

### ISSUE THREAD

**Issue by sap-ray** [aws-observability/aws-otel-collector#2192]
**Is your feature request related to a problem? Please describe.**
How we can send metrics to the collector from things we can't put an endpoint on? 

**Describe the solution you'd like**
We would like to report response times from portions of code within a synthetic canary. We also need to send metrics to the collector from other things that can't support an endpoint like SaaS vendors and other custom metrics from application programs.

**Describe alternatives you've considered**
We plan to use ADOT

**Additional context**

**Comment by sap-ray** [comment]
**Use Case:**
Method Timing from Python program -> aws-otel-collector -> Dynatrace
Method Timing from C++ program -> aws-otel-collector -> Dynatrace and Splunk and Elastic
AJAX interaction in NodeJS Synthetic -> aws-otel-collector -> Dynatrace
Plutora (SaaS) transaction timing -> aws-otel-collector -> Dynatrace

**Comment by mhausenblas** [comment]
Thanks for raising this issue @sap-ray! Concerning your question "How we can send metrics to the collector from things we can't put an endpoint on?" the short answer is: use instrumentation. In ADOT, we support [Java](https://aws-otel.github.io/docs/getting-started/java-sdk), [JavaScript](https://aws-otel.github.io/docs/getting-started/javascript-sdk), [Python](https://aws-otel.github.io/docs/getting-started/python-sdk), and [.NET](https://aws-otel.github.io/docs/getting-started/dotnet-sdk) in GA.
