### ISSUE TITLE
ECR cannot scan docker image

### ISSUE THREAD

**Issue by tallpaul-embark** [aws-observability/aws-otel-collector#2193]
**Describe the bug**

When trying to scan the docker image with ECR's image scan tool a failed scan occurs with the message saying operating system is not supported.

**What did you expect to see?**
A successful image scan result

**What did you see instead?**
`"imageScanStatus":{"status":"FAILED","description":"UnsupportedImageError: The operating system and/or package manager are not supported."}}` 

**Additional context**
Based on some digging in seems that this issue is due to the [dockerfile](https://github.com/aws-observability/aws-otel-collector/blob/main/cmd/awscollector/Dockerfile) for this project using the `FROM scratch` [command that ECR states Amazon ECR does not support scanning images built from the Docker scratch image.](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning-troubleshooting.html#:~:text=Amazon%20ECR%20does,image.). 

I opened a bug report as well with [aws containers roadmap](https://github.com/aws/containers-roadmap/issues/2066)

**Comment by mhausenblas** [comment]
Thanks and this is tracked in the ECR queue so closing this here. Please note that you can see our dependencies via [dependabot](https://github.com/aws-observability/aws-otel-collector/blob/main/.github/dependabot.yml).
