### ISSUE TITLE
Ability to run the otel collector as non root user

### ISSUE THREAD

**Issue by massi-ang** [aws-observability/aws-otel-collector#2222]
**Is your feature request related to a problem? Please describe.**
I would like to run the AWS OTEL collector as non root user, which is possible with the OpenTelemetry stock collector
I am trying to manually run the collector as non-root user, but the process exits with an exit code
`1` error (`2023/07/27 08:14:45 ADOT Collector version: v0.31.0` is printed on the console, and the error is accessed via `echo $?`)

**Describe the solution you'd like**
I would like to be able to run the command as non root user and also would like to be able to override the currently hardcoded path for extraconfig:
`"/opt/aws/aws-otel-collector/etc/extracfg.txt"`

**Describe alternatives you've considered**

**Additional context**

When running the stock otel collector with a non-root user I get:
```
# bin/otelcorecol_linux_arm64 --config ./examples/local/otel-config.yaml 
2023-07-27T08:02:49.963Z        info    service/telemetry.go:84 Setting up own telemetry...
...
```

A similar output is obtained from AWS otel collector when running with sudo:

```
# sudo ~/aws-otel-collector/bin/aws-otel-collector --config /tmp/config.yaml 
2023/07/27 08:17:06 ADOT Collector version: v0.31.0
2023-07-27T08:17:06.548Z        info    service/telemetry.go:81 Setting up own telemetry...
...
```

But when running aws collector without sudo, I get:

```
# ~/aws-otel-collector/bin/aws-otel-collector --config /tmp/config.yaml 
2023/07/27 08:20:02 ADOT Collector version: v0.31.0
# echo $?
1
```

## WORKAROUND

You can run the aws otel collector with whatever user, by setting the env variable `RUN_IN_CONTAINER=True`

eg:

```
# RUN_IN_CONTAINER=True ~/aws-otel-collector/bin/aws-otel-collector --config /tmp/config.yaml 
```

**Comment by mhausenblas** [comment]
Thanks for creating this feature request @massi-ang and this is certainly something we have on our radar.

**Comment by massi-ang** [comment]
Hi @mhausenblas, I just found a valid workaround. Maybe it is enough to add this information to the documentation without any code change

**Comment by PaurushGarg** [comment]
Closing this issue as the ADOT Collector [v0.35.0](https://github.com/aws-observability/aws-otel-collector/releases/tag/v0.35.0) has been released with non-root user image.
