### ISSUE TITLE
Make the `extraconfig.txt` path configurable

### ISSUE THREAD

**Issue by massi-ang** [aws-observability/aws-otel-collector#2223]
**Is your feature request related to a problem? Please describe.**
I would like to execute the otel collector as a non root user and to install the binaries in my folders of choice. This is currently not possible because the `extraconfig.txt` path is hardcoded.

**Describe the solution you'd like**
Have the option to provide an alternative path to the `extraconfig.txt` file via a command line or env variable parameter.

**Describe alternatives you've considered**
No alternative possible

**Additional context**

**Comment by mhausenblas** [comment]
Thanks for raising this issue @massi-ang, this is on our long-term roadmap.
