### ISSUE TITLE
Change LogLevel through EnvVar or AOT_CONFIG_CONTENT

### ISSUE THREAD

**Issue by f0o** [aws-observability/aws-otel-collector#2327]
**Is your feature request related to a problem? Please describe.**
Currently aws-otel-collector spams logs like hell; this increases storage and processing costs for no good reason.

**Describe the solution you'd like**
A simple way to configure log severity (such as errors only) through either an Environment Variable or in worst-case through the AOT configuration file

**Describe alternatives you've considered**
Build an own image to override https://github.com/aws-observability/aws-otel-collector/blob/main/extracfg.txt#L2 - this will add ops-cost because somebody on my staff will have to maintenance this which seems unreasonable

**Additional context**
./.

**Comment by bryan-aguilar** [comment]
> Currently aws-otel-collector spams logs like hell
What config is being used that is spamming logs? 

> Build an own image to override https://github.com/aws-observability/aws-otel-collector/blob/main/extracfg.txt#L2 
An `extracfg` file is not present by default in our container image. Also, in the file you linked all the possible configuration values are commented out. This is noted by the `#` prefix.

Logging level can be controlled through the collector configuration. See the [service section documenation](https://opentelemetry.io/docs/collector/configuration/#service) for information on configuring the logging level.

**Comment by f0o** [comment]
Config used was https://github.com/aws-observability/aws-otel-collector/blob/main/config/ecs/ecs-default-config.yaml

We noticed after turning off metrics collection the log emissions stopped dramatically (from 1k/sec to barely anything)

We'll check the logging settings in your linked docs, thanks!

**Comment by bryan-aguilar** [comment]
I see, I was under the impression that you were filling an issue that the collector spams logs to `stdout`. Is your issue that too many logs are being written to cloudwatch? 

The config you linked uses the default settings for `emf_exporter`. EMF Exporter exports logs in Cloudwatch EMF format which are then translated into Cloudwatch metrics. You can see review the configuration options for the EMF Exporter in it's [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awsemfexporter).
