### ISSUE TITLE
ECS not able to pull public.ecr.aws/aws-observability/aws-otel-collector:v0.33.0

### ISSUE THREAD

**Issue by TarunPaga** [aws-observability/aws-otel-collector#2347]
I Am trying to set up metrics and logs collection using AWS Distro for OpenTelemetry the issue is i have enabled logs and metrics collection in ecs task defination but its not able to launch service because of the following issue
<img width="660" alt="image" src="https://github.com/aws-observability/aws-otel-collector/assets/26666920/c145c7d5-c3cf-4f05-93c7-9dd571d81f3d">

**Comment by bryan-aguilar** [comment]
Have you made any changes to the Root CA on your host? Or possibly a proxy that is not handling certificates properly?

Executing `docker pull public.ecr.aws/aws-observability/aws-otel-collector:v0.33.0` works without error for me.

**Comment by LH8PPL** [comment]
is there a way to tell the addon to pull images from a private repository?
