### ISSUE TITLE
Watch/monitor for config changes in S3 Confmap provider at runtime (hot reload)

### ISSUE THREAD

**Issue by armanerfani** [aws-observability/aws-otel-collector#2402]
**Is your feature request related to a problem? Please describe.**
We are utilizing ADOT on a Fargate service to collect telemetry data. For the configuration, S3 ConfMap Provider is used, which works fine on service startup. But when there is a change on the config file (in S3) it is required to restart the service to load the changes.

**Describe the solution you'd like**
Implementing the requirements for ADOT to watch for file changes at runtime.

**Additional context**
Here are some references that could help clarifying my request:
https://aws-otel.github.io/docs/components/confmap-providers#s3-provider
https://github.com/open-telemetry/opentelemetry-collector/blob/main/confmap/README.md#watching-for-updates

**Comment by mhausenblas** [comment]
ADOT PM here. Thanks for proposing this feature @armanerfani!

Would you mind completing the sentence "The plan is to enable"? I'm sure there was more you wanted to write ;)

**Comment by armanerfani** [comment]
> ADOT PM here. Thanks for proposing this feature @armanerfani!
> 
> Would you mind completing the sentence "The plan is to enable"? I'm sure there was more you wanted to write ;)

Thank you @mhausenblas for quick response.
Actually there was nothing more to add, we have no "plan" as of now :) other that restarting the ADOT container when there is a change to the s3 config file.
I hope the request is clear as is. But please let me know if you need me to elaborate more.

**Comment by mhausenblas** [comment]
Thanks again for raising this issue! We discussed it and certainly something that is on our roadmap for the mid to long run. The way we want to approach this is via [OpAMP](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/opampsupervisor/specification/README.md), where the supervisor controls the collector and with it hotreloads.

**Comment by armanerfani** [comment]
Hi, 
Any update for this issue?
