### ISSUE TITLE
Support Snyk for vulnerability scanning

### ISSUE THREAD

**Issue by Ben-Mark** [aws-observability/aws-otel-collector#2430]
**Describe the bug**
I ran snyk on the latest release v0.34.0
snyk test --docker amazon/aws-otel-collector:v0.34.0 --severity-threshold=high

it resulted with:

Testing amazon/aws-otel-collector:v0.34.0...
--
441 |  
442 | ✗ High severity vulnerability found in google.golang.org/grpc
443 | Description: Denial of Service (DoS)
444 | Info: https://security.snyk.io/vuln/SNYK-GOLANG-GOOGLEGOLANGORGGRPC-5953328
445 | Introduced through: google.golang.org/grpc@v1.58.1
446 | From: google.golang.org/grpc@v1.58.1
447 | Fixed in: 1.56.3, 1.57.1, 1.58.3

**Steps to reproduce**
snyk test --docker amazon/aws-otel-collector:v0.34.0 --severity-threshold=high

**What did you expect to see?**
for the aws official otel collector image to pass snyk

**What did you see instead?**
that snyk failed..

**Environment**
all environments.

**Comment by mhausenblas** [comment]
@Ben-Mark did you see our [Security Policy](https://github.com/aws-observability/aws-otel-collector/security/policy)?

**Comment by Ben-Mark** [comment]
@mhausenblas this issue is opened  because AWS official side-car image isn't running snyk.
Not because of a high severity vulnerability.

if i report this vulnerability and tomorrow someone will create a new vulnerability.
This will never end.

So please add snyk to this project.

**Comment by mhausenblas** [comment]
We've addressed the underlying issue and changing the title of the issue to reflect its nature now.
