### ISSUE TITLE
AWS ADOT W3C traceparent Specification divergence when integrating with X-Ray

### ISSUE THREAD

**Issue by ithompson-gp** [aws-observability/aws-otel-collector#2442]
**Describe the question**
Considering [AWS X-Ray now supports W3C format trace IDs for distributed tracing](https://aws.amazon.com/about-aws/whats-new/2023/10/aws-x-ray-w3c-format-trace-ids-distributed-tracing/) we can see that this change means the W3C standard has diverged (when using ADOT Collector).

The standard is broken according to [this comment in the X-Ray docs](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-sendingdata.html#xray-api-traceids:~:text=X%2DRay%20now,X%2DRay%20format.). The comment states that the W3C standard is **required** to be manipulated to become non-standard to suit the X-Ray system.

In practice, what does this mean for OTEL standard library users and those wishing to propagate OTEL trace context **by default** through AWS services for those wishing to stay W3C compliant?

**Steps to reproduce if your question is related to an action**
N/A

**What did you expect to see?**
An option for AWS to provide the means to choose X-Ray trace context or OTEL trace context as the default context propagation mechanism. This would allow non-divergence from being wholly W3C and OTEL compliant.

At the very least, AWS should honour the customer context propagation requirement (if using W3C).

**Environment**
N/A

**Additional context**
N/A

**Comment by atshaw43** [comment]
Thanks for this question Ian.

We now support trace ids generated by W3C. This means the creation time does not need to be used for the first 32 bits of the trace id. They can be completely random like the W3C standard. Before, we dropped segments that were too old based on that encoding.


We do, however, need the trace context's in the X-Ray format. That is, they must contain the dashes where appropriate. We recommend users use the X-Ray propagator when sending trace contexts to AWS integrations.

I hope that clears things up. Let me know if you have any other questions.

Best,
Adam

**Comment by ithompson-gp** [comment]
> "...creation time does not need to be used for the first 32 bits of the trace id.."
Hi @atshaw43 and thanks for getting back on this. The above quote makes sense to me now. The documentation at the time was eluding to the need for the user to break the standard to conform to the time format, but your clarification makes sense from the ingest PoV (not the User PoV). Thank you
