### ISSUE TITLE
Python support for "OpenTelemetry Collector for X-Ray Remote Sampling"

### ISSUE THREAD

**Issue by yogabbagabb** [aws-observability/aws-otel-collector#2446]
**Is your feature request related to a problem? Please describe.**

OpenTelemetry Collector for X-Ray remote Sampling is not currently available for Python. I believe this is true, having read this URL: https://aws-otel.github.io/docs/getting-started/remote-sampling

**Describe the solution you'd like**
Please endow the ADOT Python distribution with the ability to use X-ray remote sampling.

**Describe alternatives you've considered**
I could install `xray-sdk-python` and set up a local rule (as opposed to a central rule) as per this document: https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-python-configuration.html#xray-sdk-python-configuration-sampling

I would rather not do this, however. I would rather wholely use ADOT or wholely use the SDK.

**Additional context**
None.

**Comment by jj22ee** [comment]
Remote Sampling is on the roadmap for OTel Python.

For a current workaround, to use locally-based sampling rules in OTel (not using `xray-sdk-python`), you may look into using TraceIdRatioBased (see here - https://opentelemetry-python.readthedocs.io/en/latest/sdk/trace.sampling.html)
