### ISSUE TITLE
Filter processor for multiple namespaces not working, with exclude filter it is working fine

### ISSUE THREAD

**Issue by Bharaniev** [aws-observability/aws-otel-collector#2447]
Hi team , 

I have deployed adot and i m trying to filter with include for multiple namespaces for my infra  charts, but it was not working. I  m adding my configuration  as a reference to you  as an example

Example:

    processors:
      batch/metrics:
        timeout: 60s
      filter/metrics_to_include:
        metrics:
          include:
            match_type: regexp
            metric_names:
            - ^pod_.*
      
      filter/namespace_to_kubesystem:
        metrics:
          include:
            match_type: regexp
            resource_attributes:
            - key: Namespace
              value: "^kube-system$"
               
      
      filter/namespace_to_ingressnginx:
        metrics:
          include:
            match_type: regexp
            resource_attributes:
            - key: Namespace
              value: "^ingress-nginx$"

If i use this processors filter with 2 different section , it wasnt working ,but for  exclude it is working .

**Comment by vasireddy99** [comment]
Hello @Bharaniev, Can you please add more details like the `expected`  and `actual`, create an issue in this [repo please](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues).
