### ISSUE TITLE
How to enter the container

### ISSUE THREAD

**Issue by namePeterWang** [aws-observability/aws-otel-collector#2464]
**Describe the question**

I want to view the configuration file template.
How to enter the container through 'docker exec -it containerName sh'?
I encountered the following error message.
'OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown'

Thanks,
Peter

**Comment by StefanPrintezis** [comment]
I'd just try and find the configuration template you're using over here https://github.com/aws-observability/aws-otel-collector/tree/main/config

The reason you cannot enter the container by executing sh is because there is no shell present in the image, since it's distroless
