### ISSUE TITLE
Debug exporter is not available in the image yet. This is the replacement for the deprecated logging exporter

### ISSUE THREAD

**Issue by jennerm** [aws-observability/aws-otel-collector#2470]
The latest version of the otel-collector chart [opentelemetry-collector-0.73.1](https://github.com/open-telemetry/opentelemetry-helm-charts/releases/tag/opentelemetry-collector-0.73.1)

Now includes the `debug` exporter in the values.yaml as a replacement for the `logging` exporter which is now deprecated:
```
config:
  exporters:
    debug: {}
    # Will be removed in a future release.
    # Use the debug exporter instead.
    logging: {}
```

However, the latest version of the `aws-otel-collector` (v0.35.0 at the time of writting) does not include the `debug` exporter and fails when used with this chart:
```
Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
* error decoding 'exporters': unknown type: "debug" for id: "debug" (valid values: [kafka awsemf dynatrace sapm awsxray prometheusremotewrite file signalfx logzio logging otlp prometheus datadog otlphttp loadbalancing awscloudwatchlogs])
```

Since `config.exporters` is a map which we add all our other exporter config to, it is not easy to remove the debug key and stop the debug exporter from being added to the configmap.

Since it is clear that the direction of travel is that `logging` is being replaced, can the `debug` exporter please be added now?

**Comment by jennerm** [comment]
> Since config.exporters is a map which we add all our other exporter config to, it is not easy to remove the debug key

Someone showed me this in the [helm values documentation,](https://helm.sh/docs/chart_template_guide/values_files/) which might work around it:
> Deleting a default key
> If you need to delete a key from the default values, you may override the value of the key to be null, in which case Helm will remove the key from the overridden values merge.

**Comment by XanderXAJ** [comment]
I stumbled across the same issue of using the `debug` exporter [as the OTel Collector docs suggest when troubleshooting](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#local-exporters), only to find I needed to use the older `logging` exporter with the ADOT image instead.

When running the current ADOT Collector (v0.36.0), you'll see the following warnings in the logs when using the `logging` collector:

```
info	exporter@v0.90.1/exporter.go:275	Deprecated component. Will be removed in future releases.	{"kind": "exporter", "data_type": "metrics", "name": "logging"}
info	exporter@v0.90.1/exporter.go:275	Deprecated component. Will be removed in future releases.	{"kind": "exporter", "data_type": "traces", "name": "logging"}
info	exporter@v0.90.1/exporter.go:275	Deprecated component. Will be removed in future releases.	{"kind": "exporter", "data_type": "logs", "name": "logging"}
```

I'd love to fix them, however, users of the image can't act on those deprecations until the `debug` exporter is included. 😅

**Comment by jennerm** [comment]
It would be good to update the debug exporter added to the image.

**Comment by jennerm** [comment]
Keeping this alive, I think it is still relevant.

**Comment by benny-yamagata** [comment]
Very much relevant, cant really debug right now.
