### ISSUE TITLE
scope.name parameter missing in cloudwatch logs exporter

### ISSUE THREAD

**Issue by MaGaudin** [aws-observability/aws-otel-collector#2550]
**Describe the bug**
Our ADOT Collector is receiving this log:
{
"resourceLogs": [
{
"resource": {
"attributes": [...]
},
"scopeLogs": [
{
"scope": {
"name": "xxxxxxx"
},
"logRecords": [
{
"timeUnixNano": "xxx",
"observedTimeUnixNano": "xxxx",
"severityNumber": 9,
"severityText": "Information",
"body": {
"stringValue": "GET / \r\n"
},
"attributes": [...],
"traceId": "xxxx",
"spanId": "xxxx"
}
]
}
]
}
]
}

but in AWS Cloudwatch we are not able to see the field scope.name. We saw from the file exporter.go (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/awscloudwatchlogsexporter/exporter.go) that is missing the logic to retrieve the field from line 143-146.

**What did you expect to see?**
We would like to have this field in our cloudwatch logs.

**What did you see instead?**
We cannot see this field in cloudwatch logs

**Additional context**

**Comment by sgarzo10** [comment]
I have the same problem

**Comment by vsakaram** [comment]
this feature will be released in version 38 - please refer to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29884
