### ISSUE TITLE
vulnerabilities in v0.30.0 reported by Trivy

### ISSUE THREAD

**Issue by serajushsalekin** [aws-observability/aws-otel-collector#2551]
After scanning the aws-otel-collector I found the following securities issue that related to golang packages.
Resource |Resource Path|Type|Version|Format
------------- | ------------- | ------------- | ------------- | -------------
github.com/docker/docker|awscollector|PACKAGE|v24.0.2+incompatible|go
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp|awscollector|PACKAGE|v0.41.1|go
golang.org/x/net|awscollector|PACKAGE|v0.10.0|go
google.golang.org/grpc|awscollector|PACKAGE|v1.55.0|go

**Comment by bryan-aguilar** [comment]
ADOT Collector v0.30.0 is no longer supported [per our supported version policy](https://github.com/aws-observability/aws-otel-collector#supported-versions). Please upgrade to a supported version.
