### ISSUE TITLE
Document how to start with docker run

### ISSUE THREAD

**Issue by rakyll** [aws-observability/aws-otel-collector#258]
The examples and documentation is not mentioning how to start the collector with the `docker run` command. Add a section to https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/docker-demo.md before the demo to document how to start the collector with the right configuration.

**Comment by mxiamxia** [comment]
Added a section for starting the collector with `docker run`. It will bring up the collector with the default config. 
https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/docker-demo.md#run-a-single-aws-otel-collector-instance-in-docker
