### ISSUE TITLE
Transform Processor for ADOT Collector

### ISSUE THREAD

**Issue by MaGaudin** [aws-observability/aws-otel-collector#2580]
**Is your feature request related to a problem? Please describe.**
We need a way to transform some fields of a log that are not part of attributes and resources. For example, we would like to rename severity_text field in "level"

**Describe the solution you'd like**
Availability of Transform processor (already available for OTEL collecotr) for ADOT collector.

**Describe alternatives you've considered**
We have no alternatives. It's not possibile to modify fields outside attrubutes and resources.

**Additional context**

**Comment by jangaraj** [comment]
This is duplication of https://github.com/aws-observability/aws-otel-collector/issues/2300

**Comment by MaGaudin** [comment]
@jangaraj have you an idea of when it will be introduced for the ADOT?

**Comment by jangaraj** [comment]
nope

**Comment by MaGaudin** [comment]
Is there any update on this?

**Comment by mhausenblas** [comment]
@MaGaudin no and it's tracked in #2300

**Comment by mhausenblas** [comment]
Tracked in #2300
