### ISSUE TITLE
ADOT ECS Fargate example shows no traces

### ISSUE THREAD

**Issue by JonasNuvibit** [aws-observability/aws-otel-collector#2585]
Hello Everyone

After deploying the go-xray sample app with the adot collector sidecar I don't see any x-ray traces.

**Steps to reproduce if your question is related to an action**
I followed the documentation to deploy ADOT as sidecar on ECS Fargate with the go-xray sample app via taskdefinition (https://aws-otel.github.io/docs/setup/ecs#22-setup-using-ecs-task-definition). 

**What did you expect to see?**
I expected to see x-ray traces but there were none. Everything else works fine:
- statsd metrics 
- container metrics
- instance metrics

**Environment**
Standard config file included in the collector image: --config=/etc/ecs/container-insights/otel-task-metrics-config.yaml"

**Additional context**
IAM Policies also done according to the documentation. 

Also the go-xray container does not produce any logs.

**Comment by Poliziano** [comment]
I am also having this issue; I used the CloudFormation template provided for the ECS/Fargate example but I am not seeing X-Ray traces.
