### ISSUE TITLE
Please include Signalfx receiver in the ADOT collector receivers list 

### ISSUE THREAD

**Issue by macadminrohit** [aws-observability/aws-otel-collector#2594]
**Is your feature request related to a problem? We are using ADOT collector as a sidecar on our ECS cluster and instrumenting our JAVA applications using Splunk OTEL java agent and also emitting the JVM metrics through the same agent (Default metrics subsystem is micrometer ) , but since ADOT doesnt have any signalfx receiver to receive the metrics on 9943 , we have to send the metrics to `otlp` and need to change the metrics subsystem to `opentelemetry` which breaks our metric structure and stops some of the expected metrics to come in .

**Describe the solution you'd like**
Please add the signalfx receiver in the ADOT distro for OTEL . https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/signalfxreceiver 
**Describe alternatives you've considered**
Tried sending the metrics to `otlp` receiver 

**Additional context**

**Comment by dil-zmohai** [comment]
This would be a useful feature during migration to AWS.
