### ISSUE TITLE
Add support for MSK IAM authentication

### ISSUE THREAD

**Issue by bpalermo** [aws-observability/aws-otel-collector#2595]
**Is your feature request related to a problem? Please describe.**
Currently Kafka receiver and exporter don't support IAM authentication for AWS MSK.

**Describe the solution you'd like**
Add support for IAM authentication using, https://github.com/aws/aws-msk-iam-sasl-signer-go, since it should be supported by Sarama.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by mechastorm** [comment]
I am confused if this feature is still not supported. In the Kafka receiver configuration, it seems to have configs for MSK IAM auth - https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/de3cc54e9210e10c5ad9f60c7baf9f73cc3af2bf/receiver/kafkareceiver/README.md?plain=1#L53

Does it mean it is now supported?

**Comment by bpalermo** [comment]
keep open

**Comment by amal-v** [comment]
It's happening over here https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32500
