### ISSUE TITLE
Expose Fargate pod readiness metrics

### ISSUE THREAD

**Issue by vtgspk** [aws-observability/aws-otel-collector#2607]
**Is your feature request related to a problem? Please describe.**
Currently pod_status_failed and pod_status_ready metrics for Fargate pod are not available when we implement Container Insights EKS Fargate[1]. Please help to collect these metrics for Fargate pod as well

 [1] https://aws-otel.github.io/docs/getting-started/container-insights/eks-fargate

**Describe the solution you'd like**
According to [1], in EKS Fargate networking architecture, a pod is not allowed to directly reach the kubelet on that worker node. Hence, the ADOT Collector calls the Kubernetes API Server to proxy the connection to the kubelet on a worker node, and collect kubelet’s cAdvisor metrics for workloads on that node.

Can we also collect the metrics from /metrics/probes endpoint of kubelet like we now collect from /metrics/cadvisor?

Confirmed Kubelet emitting these readiness metrics on /metrics/probes in my EC2
[root@ip-192-168-46-145 bin]# curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" https://localhost:10250/metrics/probes
HELP prober_probe_duration_seconds [ALPHA] Duration in seconds for a probe response.
TYPE prober_probe_duration_seconds histogram
prober_probe_duration_seconds_bucket{container="aws-node",namespace="kube-system",pod="aws-node-9mrbq",probe_type="Liveness",le="0.005"} 0
prober_probe_duration_seconds_bucket{container="aws-node",namespace="kube-system",pod="aws-node-9mrbq",probe_type="Liveness",le="0.01"} 0

**Describe alternatives you've considered**

**Additional context**

**Comment by dehypnosis** [comment]
Anybody here?
