### ISSUE TITLE
OTEL Client missing AwsXRayIdGenerator silently fails

### ISSUE THREAD

**Issue by mjpowersjr** [aws-observability/aws-otel-collector#261]
When using the javascript otel libraries in combination with the aws-otel-collector, it's important that you override the default otel span id generator. While the documentation does highlight this, if mis-configured no errors are logged. 

In troubleshooting the issue I turned log levels up to debug on both the javascript otel exporter and the aws-otel-collector, and it was not obvious that an actual error was occuring - only a lack of traces showing up in x-ray. :-)

Ideally I would have liked to see the aws-otel-collector detect the invalid span ids and log an error.

I've included a simple example if you would like to re-create the scenario:
```js
const api = require("@opentelemetry/api");
const { NodeTracerProvider } = require("@opentelemetry/node");
const { SimpleSpanProcessor, ConsoleSpanExporter } = require("@opentelemetry/tracing");
const { CollectorTraceExporter } = require('@opentelemetry/exporter-collector');

const { AWSXRayPropagator } = require('@aws/otel-aws-xray-propagator');
const { AwsXRayIdGenerator } = require('@aws/otel-aws-xray-id-generator');

const SERVICE_NAME = 'otel-test';
const SERVICE_VERSION = '0.1.0';
const OTEL_COLLECTOR_ENDPOINT = 'http://localhost:55681/v1/traces';

// AWS X-Ray support
const idGenerator = new AwsXRayIdGenerator();
const propagator = new AWSXRayPropagator();
api.propagation.setGlobalPropagator(propagator);

// configure tracer provider
const tracerProvider = new NodeTracerProvider({
    // IMPORTANT - Notice I've commented out the idGenerator? 
    // This will result in a silent failure!
    // idGenerator,
});

// otel exporter
const otlpExporter = new CollectorTraceExporter({
    SERVICE_NAME,
    url: OTEL_COLLECTOR_ENDPOINT,
    protocolNode: 2,
    logger: console
});
tracerProvider.addSpanProcessor(new SimpleSpanProcessor(otlpExporter));

// console exporter
const consoleExporter = new ConsoleSpanExporter();
tracerProvider.addSpanProcessor(new SimpleSpanProcessor(consoleExporter));

// register tracerProvider global reference
tracerProvider.register();



async function main() {
    const tracer = api.trace.getTracer(SERVICE_NAME, SERVICE_VERSION);

    // AWS X-Ray OTEL Collector only supports CLIENT, SERVER
    // for the root span at the moment, maybe a bug?
    const rootSpan = tracer.startSpan('main', {
        parent: null,
        kind: api.SpanKind.SERVER 
    });

    await tracer.withSpan(rootSpan, async () => {
        const childSpan = tracer.startSpan('op', { parent: tracer.getCurrentSpan() });
        await sleep(2000);
        childSpan.end();
    });

    rootSpan.end();
}

function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

main().catch(console.error);
```

**Comment by alolita** [comment]
Thanks for the example code. @mjpowersjr We will take a look.

cc: @awssandra @KKelvinLo

**Comment by anuraaga** [comment]
Thanks @mjpowersjr! I filed https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1809 to log a debug message for translation errors (most of which will be related to the trace ID).

This is the error that will be logged - https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/exporter/awsxrayexporter/translator/segment.go#L308

**Comment by mjpowersjr** [comment]
@anuraaga Thanks for the speedy response!  I was able to make good progress on using X-Ray w. the AWS OTEL Collector over the weekend. I hit some other snags along the way, but most of them where not collector related. :-)

 In case you are interested, I posted my finding over at: https://github.com/aws-observability/aws-otel-community/issues/4

**Comment by mxiamxia** [comment]
Thanks @mjpowersjr . we'll track the trace request silently fails in [open-telemetry/opentelemetry-collector-contrib#1809](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1809 ) and other finding in otel-community repo.
