### ISSUE TITLE
How do I configure the XRay Exporter when deploying the ADOT Collector to EKS?

### ISSUE THREAD

**Issue by murshed-panorama** [aws-observability/aws-otel-collector#2618]
**Describe the question**
I have the ADOT Collector installed in my EKS cluster as an EKS Add On. When installing this Add On, how can I set configurations for the XRay Exporter?

[The documentation](https://aws-otel.github.io/docs/getting-started/x-ray#configuring-the-aws-x-ray-exporter) mentions setting configuration values in a YAML file, but it does not say how to supply the YAML file when installing the Add On.

**What did you expect to see?**
I expected the documentation to mention how to configure the XRay exporter when installing the EKS Add On.

**Environment**

The `adot` Add On is installed with the following commands

```bash
# Required but not well documented
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.7/cert-manager.yaml

aws eks create-addon \
    --cluster-name my-cluster \
    --addon-name adot \
    --configuration-values file://configuration-values.json \
    --resolve-conflicts=OVERWRITE
```

The contents of `configuration-values.json`:

```json
{
  "collector": {
    "otlpIngest": {
      "pipelines": {
        "traces": {
          "xray": {
            "enabled": true
          }
        }
      },
      "serviceAccount": {
        "annotations": {
          "eks.amazonaws.com/role-arn": "arn:aws:iam::123456789012:role/role-with-xray-write-access"
        }
      }
    }
  }
}
```

**Additional context**

I would like to specifically enable the `index_all_attributes` or `index_attributes` configuration field for XRay because all my OpenTelemetry attributes are translated to metadata and are not searchable unless they are annotations.

I want to automate the installation process and don't want to edit configuration files with `kubectl` manually after the installation.

**Comment by bryan-aguilar** [comment]
You can provide configurations to the collector by using config map providers at startup. https://aws-otel.github.io/docs/components/confmap-providers

**Comment by jatinmehrotra** [comment]
@murshed-panorama 

IMO there is no helm package. 

> My issue is that there are no instructions on how to apply this configuration when installing the adot EKS addon. Can it be packaged with the adot add on?

I think you are looking for this particular information that will help you to deploy the collector during add-on installation. But I should also tell you that `as per docs` you will lose the ability to add the iam_role(for assume role) option in case you want to send traces to the central monitoring account. Perhaps that is why I have chose to deploy my collector manually using yaml configuration.

https://aws-otel.github.io/docs/getting-started/adot-eks-add-on/add-on-configuration-collector-deployment
https://aws-otel.github.io/docs/getting-started/adot-eks-add-on/config-otlp-ingest
