### ISSUE TITLE
Does this collector supports Python Lambda container images? 

### ISSUE THREAD

**Issue by sasha-wing** [aws-observability/aws-otel-collector#2646]
**Describe the question**
The lambda integration guide does not specify how to integrate otel collection inside lambdas configured with container images as lambda layers are not supported with container image lambdas.

**What did you expect to see?**
Documentation stating the support of the feature.

**Comment by roger-collins-self** [comment]
You just need to extract the layer .zip to `/opt`:

```
RUN curl $(aws lambda get-layer-version-by-arn --arn arn:aws:lambda:${REGION}:901920570463:layer:aws-otel-python-${ARCH}-ver-1-25-0:1 --query 'Content.Location' --output text --region ${REGION}) --output layer.zip
RUN unzip layer.zip -d /opt
```

**Comment by mtvx** [comment]
> You just need to extract the layer .zip to `/opt`:
> 
> ```
> RUN curl $(aws lambda get-layer-version-by-arn --arn arn:aws:lambda:${REGION}:901920570463:layer:aws-otel-python-${ARCH}-ver-1-25-0:1 --query 'Content.Location' --output text --region ${REGION}) --output layer.zip
> RUN unzip layer.zip -d /opt
> ```

This is the legacy Lambda layer, though. Not part of this repository, in specific.
