### ISSUE TITLE
/healthcheck doesn't work in ECS

### ISSUE THREAD

**Issue by louislatreille-cb** [aws-observability/aws-otel-collector#2655]
**Describe the bug**
As per the documentation and the examples in this [repository](https://github.com/aws-observability/aws-otel-collector/blob/main/examples/ecs/aws-cloudwatch/ecs-fargate-sidecar.json), we can set the ECS `healthCheck` to the "/healthcheck" command.

After deploying the ADOT collector with this, the container remains unhealthy in ECS

**Steps to reproduce**
Deploy the ADOT collector with a `healthcheck` command as described in the documentation

**What did you expect to see?**
The container is becomes healthy after a few seconds

**What did you see instead?**
The container stays unhealthy forever

**Environment**
I'm using AWS CDK. Here's my container definition:

```
const adotContainer = taskDefinition.addContainer(`${id}-adot-container`, {
    image: ContainerImage.fromRegistry("amazon/aws-otel-collector:v0.37.0"),
    command: ["--config=/etc/ecs/ecs-cloudwatch-xray.yaml"],
    logging: LogDriver.awsLogs({
      logGroup: new LogGroup(scope, `${id}-adot-logs`, {
        logGroupName: `${id}-adot-logs`,
      }),
      streamPrefix: `${id}-adot-container`,
    }),
    healthCheck: {
      command: ["/healthcheck"],
    },
  });
```

**Additional context**

**Comment by louislatreille** [comment]
Thanks for the hint @zehsor, it worked!
