### ISSUE TITLE
Not getting AWS Lambda service and the AWS Lambda function trace in custom OTEL collector

### ISSUE THREAD

**Issue by abhishekbubun30** [aws-observability/aws-otel-collector#2707]
In our AWS Lambda(coded in python) we have added ADOT extension which is seamlessly generating and sending traces to X-Ray. but when we have enabled config.yaml to send traces to a centralized collector we are observing that AWS Lambda service and the AWS Lambda function trace are not being sent. Are we missing any specific configuration or is this the expected behavior?

**Comment by arun-annamalai** [comment]
AWS traces are only able to be sent to the service applications account x-ray service. Third party trace storage and cross account amazon x-ray trace emission is not possible
