### ISSUE TITLE
Add support for windowseventlog receiver for ADOT collector

### ISSUE THREAD

**Issue by git-jayj** [aws-observability/aws-otel-collector#2723]
**Is your feature request related to a problem? Please describe.**
It is very common use case to collect Windows Event Logs from EC2 instances running Windows workload and forward them to CloudWatch log groups for further analysis/alerting. 

**Describe the solution you'd like**
Now that we have support for logs in ADOT collector this can be a useful enhancement to support [windowseventlog](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/windowseventlogreceiver/README.md) receiver so that customer can collect and send the events to CloudWatch Log groups using `awscloudwatchlogsexporter`.

**Describe alternatives you've considered**
Alternative is to use [CloudWatch agent](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html) instead of ADOT collector as it already supports this. Building a custom collector is another option, but it could introduce additional complexity and maintenance overhead for users.

**Additional context**
I see that most of the other vendors(e.g. splunk, honeycomb etc.) supports `windowseventlog` receiver.

**Comment by mhausenblas** [comment]
Thanks a lot for your feedback
