### ISSUE TITLE
Provide arm64 docker images in dockerhub

### ISSUE THREAD

**Issue by lkinley-rythmos** [aws-observability/aws-otel-collector#274]
There are only amd64 images available so we cannot run this on Graviton instances without building our own.

**Comment by khanhntd** [comment]
Hi @lkinley-rythmos, thanks for notifying us the issues. I will notify our team about this issues; but for good updates, currently we have opened a PR to support [arm64 docker images on dockerhub](https://github.com/aws-observability/aws-otel-collector/pull/860). Therefore, I will notify you and update ASAP when we will support these.

**Comment by khanhntd** [comment]
Hi @lkinley-rythmos, thanks for waiting so long for us to provide support. Good news is we have [v0.16.0](https://github.com/aws-observability/aws-otel-collector/releases/tag/v0.16.0). This will include ARM64 image for both [DockerHub](https://hub.docker.com/r/amazon/aws-otel-collector/tags) and [ECR Public.](https://gallery.ecr.aws/aws-observability/aws-otel-collector). I will close this issue for now and if you have any issues with the new image, please open up a new one and we will discuss about it.
