### ISSUE TITLE
AWS Distro for OpenTelemetry EKS add-on for kubernetes 1.31?

### ISSUE THREAD

**Issue by zodilib** [aws-observability/aws-otel-collector#2873]
**Describe the question**
EKS is now supporting and suggesting upgrades to Kubernetes 1.31, but the AWS Distro for OpenTelemetry EKS add-on is not supported.

[Here](https://github.com/aws-observability/aws-otel-collector/issues/2745) is the link to the similar issue opened for EKS 1.30, which took it almost 6 months to resolve. I am hoping as per your last statement the internal process improvement would help this one get resolved sooner. 

**Steps to reproduce if your question is related to an action**
Launch an EKS instance with Kubernetes 1.31, then try to add the add-on, you'll not be able to due so:

<img width="1364" alt="image" src="https://github.com/user-attachments/assets/b7044f60-a94c-4ee5-b552-6bdd31fca827">

**What did you expect to see?**
I expected to use the add-on with EKS 1.31.

**Additional context**
Link to the previous issue related to 1.30. - https://github.com/aws-observability/aws-otel-collector/issues/2745

**Comment by mhausenblas** [comment]
Thanks for creating this issue and I can confirm that we're working on it.

**Comment by JamesBelchamber** [comment]
Can you share with us what is holding back release? Is there an upstream issue (and can you share the report in the upstream tracker), is there an issue specific to ADOT/EKS (and where is that being tracked)?

Of particular interest: is there something your team knows that makes upgrading a bad idea for any other OpenTelemetry distributions on EKS or Kubernetes? If so then it would be good to share that with the community.

I'm sorry if this appears short but I think many of us are gasping for information. We don't necessarily need the release - if we know _why_ you're not releasing then it empowers us as engineers to make better decisions, and to provide better reporting to our stakeholders.

**Comment by sidick** [comment]
To be honest, the impression it leaves me is that the adot addon is a second class addon, especially as almost all the others have working versions either at launch or very soon afterwards

**Comment by mhausenblas** [comment]
@JamesBelchamber thanks for your question. It's not an upstream issue but something internal we need to resolve. I'll keep this thread posted.

**Comment by JamesBelchamber** [comment]
> @JamesBelchamber thanks for your question. It's not an upstream issue but something internal we need to resolve. I'll keep this thread posted.

In the spirit of community can you share more details of this issue? For example, would it affect people deploying the Operator directly (i.e. without using the EKS add-on flow)? I appreciate you would not support such a deployment.

**Comment by mhausenblas** [comment]
> For example, would it affect people deploying the Operator directly (i.e. without using the EKS add-on flow)

That's an excellent question. I don't have the answer, let me verify and report back here.

**Comment by mhausenblas** [comment]
@JamesBelchamber just to close the loop: this was on our end, so there should be no negative impact deploying the operator directly.

**Comment by mhausenblas** [comment]
FYI: support for Kubernetes 1.31 is now available, see the [launch blog post](https://aws-otel.github.io/docs/ReleaseBlogs/aws-distro-for-opentelemetry-eks-add-on-v0.109.0) for details.
