### ISSUE TITLE
EKS Collector vs Auto Instrumentation Agent port mismatch (4317 vs 55680)

### ISSUE THREAD

**Issue by christopher-wong** [aws-observability/aws-otel-collector#289]
I have the `aws-otel-collector` deployed in my EKS cluster using the `amazon/aws-otel-collector:latest` image and noticed it listens on port `55680` by default.

When I added the AWS Auto Instrumentation Agent per the docs https://aws-otel.github.io/docs/getting-started/java-sdk/trace-auto-instr here, the agent started up trying to connect on port `4317` (port is documented here https://aws-otel.github.io/docs/getting-started/java-sdk/trace-auto-instr#advanced-configuration-of-the-auto-instrumentation-agent).

Which one of these is the correct port?

**Comment by mxiamxia** [comment]
Hi @christopher-wong , the default port should be `55680`. We'll correct it in the documentation website. Thanks.
