### ISSUE TITLE
Wrong sidecar manifest URL

### ISSUE THREAD

**Issue by dustnic** [aws-observability/aws-otel-collector#306]
I believe the link here: https://aws-otel.github.io/docs/setup/eks for
`kubectl apply -f https://raw.githubusercontent.com/aws-observability/aws-otel-collector/main/examples/eks/eks-sidecar.yaml` is broken and points to a path that isn't there anymore.

**Comment by pingleig** [comment]
The new path is https://github.com/aws-observability/aws-otel-collector/blob/main/deployment-template/eks/eks-sidecar.yaml and we should update the doc

**Comment by mxiamxia** [comment]
The following link is also back now. Thanks for reporting.
https://raw.githubusercontent.com/aws-observability/aws-otel-collector/main/examples/eks/eks-sidecar.yaml

**Comment by mentos1386** [comment]
@mxiamxia the link is broken again. New link seems to be https://github.com/aws-observability/aws-otel-collector/blob/main/examples/eks/aws-cloudwatch/otel-sidecar.yaml

**Comment by pingleig** [comment]
We changed examples recently but https://github.com/aws-otel/aws-otel.github.io is not updated.
