### ISSUE TITLE
Tagging support on traces

### ISSUE THREAD

**Issue by ajones-miovision** [aws-observability/aws-otel-collector#310]
We are migrating from using DataDog APM to aws opentracing distro + xray. One missing piece from otel seems to be having the ability for the collector to augment all requests with additional top-level metadata such as an environment tag. That way, we could filter our traces in xray by tag. We currently run the otel-collector as a daemon on each of our ecs cluster machines and all services pass their traces through the daemon up to xray.

Would it be possible to add tagging support to the collector so that it can augment all traces with metadata?

**Comment by mxiamxia** [comment]
Hi @ajones-miovision, Thanks for reaching out us.

Have you tried to enable `resourcedetectionprocessor` processor in your configuration, it should add the ECS environment tags in your trace for filtering.

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/processor/resourcedetectionprocessor

**Comment by mxiamxia** [comment]
Hi @ajones-miovision, thanks for reaching out. Have your tried to enable `resourcedetectionprocessor` in your configuration and it should add some ECS env tags for you for the filtering. Or are you looking for a way to add the customized tags?

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/processor/resourcedetectionprocessor

**Comment by ajones-miovision** [comment]
Oh, does the aws otel collector support the "contrib" set of processors out of the box or will I have to build a custom otel collector?

**Comment by mxiamxia** [comment]
Yes, we don't support contrib components yet, but if we support `resourcedetectionprocessor` will it solve your use case. if so we can plan for adding it in.

**Comment by ajones-miovision** [comment]
What is the recommendation/best practice for getting top-level attributes added to all traces so that i can filter them in x-ray?

Having the collector append filterable metadata seems like a good idea and it certainly looks like this is supported via processors, however, it's difficult to determine which (if any) of the standard processors will result in adding data that x-ray can filter on. It's possible this this is an issue with x-ray more than it is with the open tracing collector.

For the time being, I am going to deploy the opentracing-collector-contrib with a custom config yaml into my environment and see if it adds the data I need.

**Comment by ajones-miovision** [comment]
I resolved my issue. My problem was that I had to configure the x-ray exporter to include certain metadata fields as indexed annotations.

**Comment by avocadomaster** [comment]
> Yes, we don't support all of the contrib components yet, but if we support `resourcedetectionprocessor` will it solve your use case. if so we can plan for adding it in.

I am currently experimenting with migrating some services to use aws otel collector. Supporting `resourcedetectionprocessor` out of the box would be an easy solution to solve our use case for adding this context to xray traces.

@mxiamxia
