### ISSUE TITLE
[bug] log does not write to stderr when running in container

### ISSUE THREAD

**Issue by pingleig** [aws-observability/aws-otel-collector#339]
## Behaviour

When running the collector as a container, its log does NOT show up in stdout/stderr. Making it hard to debug issues like  #340 

## Expected

Write all log to stderr when running in container.

## Root Cause

The log file path is determined by runtime OS and is always non empty.

https://github.com/aws-observability/aws-otel-collector/blob/94015373a37231d8678d115fe05e90d662c555a7/pkg/logger/logger.go#L34

https://github.com/aws-observability/aws-otel-collector/blob/94015373a37231d8678d115fe05e90d662c555a7/pkg/logger/logger.go#L58-L81

**Comment by anuraaga** [comment]
@pingleig Thanks for finding this, we were looking into why the log message doesn't go to stderr just today, related to #340. @mxiamxia
