### ISSUE TITLE
[emf exporter]Weird results after setting the metric_declarations: dimensions: after dimension roll up

### ISSUE THREAD

**Issue by JohnWu20** [aws-observability/aws-otel-collector#342]
**Is your feature request related to a problem? Please describe.**
My config file is:
[config.txt](https://github.com/aws-observability/aws-otel-collector/files/5930857/config.txt)

However, here is what I got from the cloudformation log group:

<img width="428" alt="Screen Shot 2021-02-04 at 10 20 10 PM" src="https://user-images.githubusercontent.com/59711343/106997117-2960bd00-6737-11eb-8bf9-55eff1d45211.png">

[One sample log from emf exporter ](https://github.com/aws-observability/aws-otel-collector/files/5930929/aws.ecs.containerinsights.test200.performance.test07.txt)

And also from the matrics:

<img width="1357" alt="Screen Shot 2021-02-04 at 10 20 56 PM" src="https://user-images.githubusercontent.com/59711343/106997171-439a9b00-6737-11eb-87ca-18d6f5bd2099.png">

The result is weird after rollup with the dimension I selected. And it works well without dimension rollup.

**The result expected to see is:**
Based on my understanding, the result should be the rollup result of the selected dimensions:

"Dimensions": [
                    [
                        "aws.ecs.cluster.name",
                        "aws.ecs.task.arn",
                    ],
                    [
                        "aws.ecs.cluster.name"
                    ],
                    [
                        aws.ecs.task.arn"
                    ],
                    [
                    ]
   ]

**Comment by shaochengwang** [comment]
The MetricDeclarations create a list of dimension sets that matches the given `metric`. This list is then aggregated together with the rolled-up dimensions. Your selected dimensions are processed in addition to the original rollup logic, as a result you are seeing more dimension sets in the result.
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/65673ad3657b2f609dcfea87d0acf62a5d8f6d83/exporter/awsemfexporter/metric_declaration.go#L220-L223

**Comment by JohnWu20** [comment]
Thanks @shaochengwang , if this is the rule of MetricDeclarations, it's not a bug, I will close this issue.

**Comment by JohnWu20** [comment]
@shaochengwang I reopen this issue, because it doesn't make sense to our customers. When they use the dimensions without rollup, they can only see the dimensions in the cloudwatch what they put in the dimensions list . The same logic should work when they rollup the dimensions.  
What if the customer just want to see the dimensions they choose to rollup without other dimensions? How can they wirte the config file to make it?

**Comment by mxiamxia** [comment]
@JohnWu20 , can you share the collector logs with log exporter enabled here? I want to see the raw data of the metrics. It seems all resources have been split into each metric instead of one metric has a group of resource as dimensions together.  @hossain-rayhan is it the expected behavior how you done `resource_to_label` converson?

**Comment by JohnWu20** [comment]
@mxiamxia I updated the doc to add one metrics data there. And it is that one metric has a group of resource together.

**Comment by mxiamxia** [comment]
Thanks @JohnWu20 for updating the doc.
To your question,
>What if the customer just want to see the dimensions they choose to rollup without other dimensions? How can they wirte the config file to make it?

The dimension selector in EMFExportor is not used to filter/remove the labels for the incoming metrics. it is adding a new metric based on the incoming metrics. if customers want to filter the labels they can rely on `metricstransformprocessor` processor which can delete the labels first and then enable the rollup options.

As @shaochengwang mentioned, the result you got is per design because single dimension rollup is based on the raw incoming metrics.

**Comment by JohnWu20** [comment]
Thanks @mxiamxia , I checked the [metricstransformprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor) processor doc, there is no delete label keys operations, just have the delete label value operations. 
I will appreciate if you can tell me how customer use the processor to just get the dimensions they want.

**Comment by hossain-rayhan** [comment]
@JohnWu20 , we are already doing this work in our config. We can delete the resource attributes instead of metrics label. Point to be noted- our metric labels are generated from resource attributes. 
```
 resource:
    attributes:
      - key: ClusterName
        from_attribute: aws.ecs.cluster.name
        action: insert
      - key: aws.ecs.cluster.name
        action: delete
```

**Comment by JohnWu20** [comment]
Oh, I see, thanks @hossain-rayhan , @mxiamxia and @shaochengwang.
