### ISSUE TITLE
Exporter for AWS Elastic Search 

### ISSUE THREAD

**Issue by kuberkaul** [aws-observability/aws-otel-collector#343]
Just a question as I could not find, **are there any plans for exporter for traces to AWS elastic search** ? The otel-contrib container seems to throw errors if configured to push traces out to AWS managed elastic search.

**Comment by alolita** [comment]
Hi @kuberkaul thanks for your interest in using Elasticsearch with OpenTelemetry. Can you provide more detail on your use cases? Are you interested in an exporter for Amazon Elasticsearch Service (AES) specifically? Let me know and set up a time to chat if that works for you.

**Comment by kuberkaul** [comment]
yes ofcourse !

Heres our detailed use case, We use jaeger for collecting our traces from Istio(Service mesh)+ AWS EKS and our applications.In this setup traces are sent by the EKS+Istio and our application to jaeger which then pushes these traces out to AWS ES. 

We would now like to switch to open telemetry and bypass jaeger completely. Our design to have Istio+EKS and our apps send the traces (Reciever zipkin/jaeger format ~ http/grpc ) straight to Elastic Search (Exporter) in our AWS account. This would remove the need of jaeger and prometheus to sit between open telemetry and our backend storage for both metrics and traces (S3 and ES)

**Comment by kuberkaul** [comment]
and yes for chat!

**Comment by kowshikn** [comment]
@kuberkaul The elasticexporter in otel-contrib connects to elastic apm server, that will not work with AWS Elasticsearch service. AWS Elasticsearch team does have  plans to support OpenTelemetry trace data through [Data Prepper](https://opendistro.github.io/for-elasticsearch-docs/docs/trace/). Data Prepper in the current [release](https://github.com/opendistro-for-elasticsearch/data-prepper/blob/v0.7.x/docs/readme/trace_overview.md) currently can send data only to Open Distro for Elasticsearch. 

We do have a roadmap planned to make Data Prepper as a AWS feature. We can discuss that in the chat. I will work with @alolita to setup up a chat.

**Comment by kuberkaul** [comment]
@kowshikn that would be great, I did find the data prepper just before I saw your comment and am giving this a try. I would also like to talk about the possibility of prometheus/time series metrics being received by the collector and sent over to S3 sink. This so it can then be leveraged by a tool like thanos/cortex. Something similar to what AWS did with managed prometheus except this can be used by many other tools.

**Comment by alolita** [comment]
@kuberkaul following up on this thread, did you have a chance to try out the dataprepper? Let me know what works best to set up a time to chat more on your use cases.

**Comment by kuberkaul** [comment]
Thanks @alolita. Ill be giving it a shot this week !

**Comment by jayasai470** [comment]
Our use case is we need to send logs in EKS to aws OSS ideally through otel collector. Last time i have checked there is no ES exporter, any plans to include this ? Public otel exporter for ES uses incompatible client https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/elasticsearchexporter/go.mod#L7. 
Any insights about this feature or timelines if this is already considered ?

**Comment by jayasai470** [comment]
@alolita any insights on the above comment
