### ISSUE TITLE
AWS OTel Collector hardcodes log file paths

### ISSUE THREAD

**Issue by nmeyerhans** [aws-observability/aws-otel-collector#369]
In `pkg/logger/logger.go`, there are hardcoded references to paths under `/opt/aws`. This is problematic reasons including:

1. It restricts the administrator's ability to apply their own configuration to their system. They may prefer, for example, to have `/opt` on a read-only filesystem.
2. Because the tests in `logger_test.go` test the ability to write messages to log files (see specifically `TestGetLumberHook()`), running your test suite modifies files outside the source tree. This means that your test suite, which should not normally run as a privileged user, must run as a user explicitly granted write permission to directories under `/opt`, or it will fail.

**Comment by kurvatch** [comment]
This is causing issues while deploying in PaaS solution where we don't have control on file path and permissions.
1) Provide a way to override the log path information in configuration.
2) Write it to Standard output and log scrappers can ship the logs to desired destination.

**Comment by mxiamxia** [comment]
Currently, the hardcoded `directory` only applies to non-container running collectors(EC2, On-Prem). We create the default directories (`/opt/aws/aws-otel-collector/`) as root user when the collector package(rpm, msi, deb) is being installed. And when the collector is started as root, we will change the collector process owner and the collector related directory owner from `root to` `awsotel` user. 
My assumption is that if we don't havethe permission to install the collector package, we shouldn’t have permission issue on log path. 
 
For the container running collectors, we’re writing the logs to STD output.

**Comment by kurvatch** [comment]
How about extracting the `awscollector` from container and running it as a process in `PaaS `solution where we don't have to install with root privileges and hence no permissions to log directories as well. This process doesn't even start because of this dependencies.

**Comment by mxiamxia** [comment]
In that case, if you can set environment variable `RUN_IN_CONTAINER=True` in your PaaS environment, it will not create the hardcoded log directory and only write logs to STD output. 

Please let us know if this could work for you.

**Comment by kurvatch** [comment]
Hi @mxiamxia I see this is not working when `RUN_IN_CONTAINER=True` in PaaS environment. I get below error
ERR 2021-03-24 14:10:18.800510482 +0000 UTC m=+0.044061508 write error: can't make directories for new logfile: mkdir /opt/aws: permission denied
looks like it is still looking to create directory with path `/opt/aws/`

Env Variable Set
`RUN_IN_CONTAINER: True`

**Comment by cprice404-aws** [comment]
I see the same behavior as @kurvatch described - process dies if it can't `mkdir /opt/aws` regardless of the env var.

**Comment by mxiamxia** [comment]
This bug has been fixed in the latest ADOT collector. Close the issue. Pls feel free to reopen if your issue is still existed.
