### ISSUE TITLE
ServiceLen View Logs feature is disabled on X-Ray traces instrumented by ADOT

### ISSUE THREAD

**Issue by mxiamxia** [aws-observability/aws-otel-collector#376]
**Is your feature request related to a problem? Please describe.**
Run sample application in ECS with Java Auto Agent and AWS OTel Collector setup. We expect in CloudWatch ServiceLen console, View Logs button should be enabled, but it is disabled with the setup. 
Setup instructions,
* https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/ecs-demo.md#install-awsotelcollector-on-ecs-ec2
![image](https://user-images.githubusercontent.com/5331577/109079582-fe251a00-76b3-11eb-9583-33158ca0e15b.png)

**Comment by mxiamxia** [comment]
@willarmiros , can you please help to dig why does `View Logs` button is disabled when run Java service in ECS with OTEL.  OTel Java SDK has in-process resource detector enabled.

**Comment by willarmiros** [comment]
@mxiamxia Can you please provide a sample X-Ray trace from this service? I believe you need the Collector's ECS resource detector enabled, since it records the application's log group in the `cloudwatch_logs` field of the ECS segment (as long as you're running it as a sidecar). I don't think the java resource detector records that field yet, which is a gap in the in-process detectors.

**Comment by willarmiros** [comment]
![Screen Shot 2021-03-16 at 10 12 08 AM](https://user-images.githubusercontent.com/54150514/111351378-bce7b080-8648-11eb-94bf-26d50a1bc45f.png)

I was able to reproduce this issue using an ECS Fargate app. The correlated logs are available in the trace details page, but at the top of the trace detail page, where the mini-service map is located, the "View Logs" button is still disabled.

**Comment by willarmiros** [comment]
Here is the full trace data for that request:

```
{
    "Id": "1-6050e132-e30c44e50796a67aab6c5f8f",
    "Duration": 0.008,
    "LimitExceeded": false,
    "Segments": [
        {
            "Id": "53ded5e7ba043110",
            "Document": {
                "id": "53ded5e7ba043110",
                "name": "MyInstrumentedService",
                "start_time": 1615913266.051,
                "trace_id": "1-6050e132-e30c44e50796a67aab6c5f8f",
                "end_time": 1615913266.059,
                "http": {
                    "request": {
                        "url": "REDACTED",
                        "method": "GET",
                        "user_agent": "REDACTED",
                        "client_ip": "REDACTED"
                    },
                    "response": {
                        "status": 200
                    }
                },
                "aws": {
                    "ecs": {
                        "container": "REDACTED",
                        "container_id": "4593b2e94019ab82461b/d6a28ca7516e4593b2e94019ab82461b-2779064798",
                        "container_arn": "arn:aws:ecs:us-west-2:REDACTED:container/753a1d1b-d869-4953-affe-f11fee652af3"
                    },
                    "xray": {
                        "auto_instrumentation": true,
                        "sdk_version": "2.8.0-dev.28.uncommitted+ecs.metadata.e3dadf0",
                        "sdk": "X-Ray for Java"
                    },
                    "cloudwatch_logs": [
                        {
                            "log_group": "/ecs/demo-trace-id-injection",
                            "arn": "arn:aws:logs:us-west-2:REDACTED:log-group:/ecs/demo-trace-id-injection"
                        }
                    ]
                },
                "service": {
                    "runtime": "OpenJDK 64-Bit Server VM",
                    "runtime_version": "11.0.9.1"
                },
                "origin": "AWS::ECS::Container"
            }
        }
    ]
}

**Comment by rcooper85** [comment]
May I ask how you managed to get the logs correlated in the first place? I'm currently sending my logs to cloudwatch and i've configured Logback to add the trace and span ids to each console log. I can see these logs in cloudwatch but when I view the traces in X-Ray or ServiceLens, I don't see any associated logging. I'm running a basic java springboot app in ECS with the aws distro collector as a sidecar with the default config. The log driver I am using is awsfirelens.

**Comment by jackpowers** [comment]
I am facing this exact issue using the SDK. Any additional help would be appreciated
