### ISSUE TITLE
Prometheus histograms, summary and counters

### ISSUE THREAD

**Issue by vishiy** [aws-observability/aws-otel-collector#382]
Hi Is Prometheus histograms delta (rather than cumulative) when collected thru adot? Looking at otel prom receiver all of counters, histograms and (sum & count) series for summary are delta, where as Prometheus representation of them are cumulative time series.

**Comment by alolita** [comment]
Hi @vishiy ADOT is a downstream distribution of the OTel Collector so the implementation of the Collector components are the same as in OTel. The Prometheus remote write exporter exports cumulative values as expected by Prometheus. Hth.

**Comment by vishiy** [comment]
Thanks @alolita . I took a counter to check. I don’t see deltas converted to cumulative in exporter. Is this a known thing?

**Comment by rakyll** [comment]
@vishiy Prometheus doesn't have support for deltas and OpenTelemetry project doesn't have a path to export deltas to Prometheus at this point. There is a long-term plan to possibly build cumulatives from deltas to export to Prometheus but there are a lot of technical challenges and missing pieces in OTLP at this point. If you can file an issue at https://github.com/open-telemetry/opentelemetry-specification explaining your case, we'd like to track this in the spec.
