### ISSUE TITLE
Populate stack trace for exceptions captured in OTel .Net span

### ISSUE THREAD

**Issue by srprash** [aws-observability/aws-otel-collector#383]
Currently if a span (Activity in .Net terminology) from the .Net instrumented application has an exception recorded, the aws exporter would only capture its `exceptionType` and `message` in the `cause` construct. The cause will not have the stack trace for the exception recorded because the exporter currently [only supports stack trace translation for Java, Python, and JS](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/awsxrayexporter/translator/cause.go#L149-L156). 
A similar support is required for the population of stack trace from .Net language.

**Comment by bhautikpip** [comment]
I can help adding stack trace capture support for .NET

**Comment by bhautikpip** [comment]
PR is merged upstream. It should be out in the next release of collector.

**Comment by bhautikpip** [comment]
upstream PR is merged and released so resolving.
