### ISSUE TITLE
Include cloud.platform in AWS Lambda resource attributes

### ISSUE THREAD

**Issue by pmm-sumo** [aws-observability/aws-otel-collector#385]
**Is your feature request related to a problem? Please describe.**

Semantic conventions describe [`cloud.platform`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/cloud.md) that contains the type of the resource. Among listed possible values, there's `aws_lambda`. However, none of the instrumentation libraries currently emits it along the traces. Also, there's no lambda-specific resource detector that could attach this data.

**Describe the solution you'd like**
Preferably, there could be two-fold solution for putting this tag automatically when running in AWS Lambda:

1. In specific SDK's, e.g. for Python somewhere around the [initialization](https://github.com/aws-observability/aws-otel-lambda/blob/main/sample-apps/python-lambda/aws_observability/aws_observability_sdk/opentelemetry/instrumentation/aws_lambda/__init__.py#L109)
2. If feasible, as a new lambda resourcedetection [plugin](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor/internal/aws) within OpenTelemetry Collector

**Describe alternatives you've considered**
The field could be also set statically or manually by the user, but it's not that convenient

**Additional context**
Values currently used by EC2, ECS and Elastic BeansTalk resource detectors are actually not in accordance to the specification. I opened a [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2556) to fix it.

Other cloud-related tags could be also filled-in (`cloud.provider`, etc.)

**Comment by mxiamxia** [comment]
Hi @pmm-sumo , thanks for the suggestion. @wangzlei , could you pls take a look?
