### ISSUE TITLE
Incompatible issue between the latest OT collector version 0.22 with AOC

### ISSUE THREAD

**Issue by JohnWu20** [aws-observability/aws-otel-collector#391]
**Background**
The[ contrib repo ](https://github.com/open-telemetry/opentelemetry-collector-contrib) just updated the newest version 0.22.0 yesterday. And it seems that there are some breaking compatibility updates made for version 0.22.0 compared to V 0.21.0.

**Issues**

When I updated all components version from V0.21.0 to V0.22.0, AOC failed to build with below error:
```
pkg/defaultcomponents/defaults.go:99:35: CombineErrors not declared by package componenterror (compile)
pkg/config/config_factory_test.go:24:2: module go.opentelemetry.io/collector@latest found (v0.22.0), but does not contain package go.opentelemetry.io/collector/service/builder (compile)

make: *** [lint-static-check] Error 1
```
From https://pkg.go.dev/go.opentelemetry.io/collector/service,  the builder package moved to internal, and we can't import internal package.

**Describe the solution you'd like**
The AOC repo should make some changes for the latest version 0.22.0.

**Additional context**
Here is the go.mod file I used to update to the latest version:
https://paste.amazon.com/show/jialiawu/1615412749

**Comment by mxiamxia** [comment]
Issue resolved. Closed
