### ISSUE TITLE
Build failing on Raspbian OS

### ISSUE THREAD

**Issue by navsinha5** [aws-observability/aws-otel-collector#402]
Tried building the binary as instructed but the build process is failing with a compilation error.

Steps:

1. git clone 
2.  make package-deb
3. failed

![image](https://user-images.githubusercontent.com/26867096/111460819-6e1e4180-8742-11eb-9566-a8dcc8705257.png)

**Comment by vastin** [comment]
It is never tested to build on Raspbian OS. It seems like a golang tool chain problem. Probably you could try to upgrade golang.
It supports cross-compiling on x86_64 Linux machine and the arm64 deb file is build/linux/debian/bin/aws-otel-collector-arm64.deb.
