### ISSUE TITLE
Issue with documentation

### ISSUE THREAD

**Issue by navsinha5** [aws-observability/aws-otel-collector#403]
This [link](https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/debian-deb-demo.md) is for Debian based systems but instead instructs to download ".rpm" file in step 1. Also in step 2 it instructs to install a ".deb" file which should be mentioned in step 1.

**Comment by mxiamxia** [comment]
Hi @navsinha5 , thanks for reporting the issue.
