### ISSUE TITLE
Need the application binary for Arm CPUs (Raspberry Pi)

### ISSUE THREAD

**Issue by navsinha5** [aws-observability/aws-otel-collector#406]
**Is your feature request related to a problem? Please describe.**
Need this feature for local testing of the setup

**Describe the solution you'd like**
A standalone binary will help a lot. Additionally a container image that can run on Arm CPUs.

**Describe alternatives you've considered**
No alternative for ARM CPUs as of now

**Comment by vastin** [comment]
If Raspberry Pi runs 64bit Linux OS, the static-linked standalone binary for arm64 Linux could be found at build/linux/aoc_linux_aarch64 after running "make build" on x84_64 Linux machine. Please let us know if this binary works on Raspberry Pi.

The request of arm64 docker image is duplicated with https://github.com/aws-observability/aws-otel-collector/issues/274.
