### ISSUE TITLE
Support k8sprocessor

### ISSUE THREAD

**Issue by rakyll** [aws-observability/aws-otel-collector#415]
Feedback from Eric Mustin:

>  it would be nice to see the k8s processor eventually gain support by aws, otherwise it's not always possible to determine which node a trace was emitted from afaik

Not sure if we are already tracking this but it might be a critically missing component if k8processor is the only way to automatically support some of the resource attributes.  

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sprocessor

**Comment by ericmustin** [comment]
@rakyll happy to chat or sync with anyone on this! cc my co-worker @mx-psi

**Comment by alolita** [comment]
Hi @ericmustin @mx-psi It would be great to chat with you about your requirements for the k8sprocessor. We've looked at the existing code, issues handling resource attributes and labeling. Let's discuss. Will reach out :-)

**Comment by mx-psi** [comment]
Any chance this gets reopened? We still would like to see this happen :)
