### ISSUE TITLE
[sync] Breaking change in upstream since v0.23

### ISSUE THREAD

**Issue by pingleig** [aws-observability/aws-otel-collector#417]
List of items that we need to fix before next release

- [x] viper is removed from config factory [diff](https://github.com/pingleig/aws-otel-collector/commit/1017f984a22624f26a873311ac4e2be741e15b96)
- [x]  `consumererror.CombineErrors` is renamed to `consumererror.Combine`

**Comment by alolita** [comment]
Hi @pingleig @mxiamxia why are these changes breaking changes for you downstream? I'd like to better understand. These are part of the ongoing Collector work upstream towards 1.0 stability. Let's sync up.

**Comment by mxiamxia** [comment]
Hi @alolita , aws-otel-collector wraps upstream collector with a few customization logic. The code links below are examples why upstream API breaking changes hurt us. 

* `viper` is removed from config factory
https://github.com/aws-observability/aws-otel-collector/blob/main/pkg/config/config_factory.go#L34

* `consumererror.CombineErrors` is renamed to `consumererror.Combine`
https://github.com/aws-observability/aws-otel-collector/blob/main/pkg/defaultcomponents/defaults.go#L101

**Comment by alolita** [comment]
Hi @mxiamxia I see. Let's chat about what the upstream fixes should look like in order to not break our logic downstream.
