### ISSUE TITLE
failed to shutdown exporter

### ISSUE THREAD

**Issue by sammy22** [aws-observability/aws-otel-collector#419]
I ran the Otel-collector image locally. 
docker run --rm -p 4317:4317 -p 55680:55680 -p 8889:8888       -e AWS_REGION=us-west-2   -v ${PWD}/config.yaml:/otel-local-config.yaml -v ~/.aws:/root/.aws  --name awscollector public.ecr.aws/aws-observability/aws-otel-collector:v0.8.0   --config otel-local-config.yaml;

when I just stop the container 
I get the error 
2021-03-30T07:11:05.119Z	INFO	service/service.go:469	Shutdown complete.
Error: failed to shutdown pipelines: failed to shutdown exporters: sync /dev/stderr: invalid argument

I get the same error when I run this in ecs task as well.

**Comment by pingleig** [comment]
I think the error might come from the logger when flushing https://github.com/uber-go/zap/issues/328

**Comment by sammy22** [comment]
This error occurs only when i use x-ray exporter. the error is because of logger.Sync(). according to the discussion here uber-go/zap#328. sync errors can be safely ignored. I did the same and recreated the image . Can this be fixed in x-ray exporter ? 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/21914fa0deb8fcb87b6eb5f72825feb54d1fce49/exporter/awsxrayexporter/awsxray.go#L93

**Comment by pingleig** [comment]
@sammy22 sure, we can fix it in the contrib repo cc @mxiamxia @awssandra
