### ISSUE TITLE
aws-otel-collector when run in container gives a permission denied error to create directory

### ISSUE THREAD

**Issue by AnuPrabath** [aws-observability/aws-otel-collector#451]
We are able to run aws-otel-collector in Cloud foundry but binary still tries to create a directory /opt/aws – Will there be any update to suppress this error when RUN_IN_CONTAINER env variable is set ?
ERR 2021-03-24 20:34:51.659421625 +0000 UTC m=+0.053561495 write error: can't make directories for new logfile: mkdir /opt/aws: permission denied

**Comment by mxiamxia** [comment]
Can you pls tell which version of AWS OTel Collector you were running? After v0.8.0 it shouldn't ask you to create directly for logs.

https://github.com/aws-observability/aws-otel-collector/blob/main/pkg/logger/logger.go#L64

**Comment by AnuPrabath** [comment]
@mxiamxia  - We are using v0.8.0 Collector with RUN_IN_CONTAINER flag set to True. I still see directory creation errors both in Cloud foundry and in EKS, we do run applications as non root users and I believe awscollector runs with awsotel user in v0.8.0 image not sure whether this might be the issue.

**Comment by pingleig** [comment]
@AnuPrabath we found the problem,  my bad in https://github.com/aws-observability/aws-otel-collector/pull/341 there are two redirect to file logic in our distro, one is standard library's `log` package, another is a hook for `zap` (used by all otel components). I only disabled the redirect for first one, so the collector still tries to create the folder and failed when running as non root user.

https://github.com/aws-observability/aws-otel-collector/blob/5e1bcb2a6979144c87a6afe8abc7b8ed00552b2a/pkg/logger/logger.go#L36-L44
