### ISSUE TITLE
Publish the Docker image

### ISSUE THREAD

**Issue by rakyll** [aws-observability/aws-otel-collector#47]
We can publish the Docker image for the connivence and add `docker run` instructions to the README.

```
docker run -d --volume=config.yaml:/etc/otel-config.yaml -p 55680:55680 -p 55861:55681 aws-observability/aws-otel-collector 
```

**Comment by mxiamxia** [comment]
Dup with https://github.com/aws-observability/aws-otel-collector/issues/258. Closed
