### ISSUE TITLE
ECS resource labels are not exported to prometheus using awsprometheusremotewrite exporter

### ISSUE THREAD

**Issue by petrokashlikov** [aws-observability/aws-otel-collector#472]
I've setup aws-otel-collector with sample app and using  awsprometheusremotewrite exporter to export metrics to AWS Managed Prometheus. When I check metrics in Prometheus they don't have any labels. 

Here is example for query 

`Object
request:Object
url:"api/datasources/proxy/1/api/v1/query_range?query=ecs_task_cpu_reserved&start=1619216715&end=1619220315&step=15"
method:"GET"
hideFromInspector:false
response:Object
status:"success"
data:Object
resultType:"matrix"
result:Array[1]
0:Object
metric:Object
__name__:"ecs_task_cpu_reserved"
values:Array[204]`

And here is my aws-otel-collector config:

`receivers:
  prometheus:
    config:
      global:
        scrape_interval: 15s
        scrape_timeout: 10s
      scrape_configs:
      - job_name: "test-prometheus-sample-app"
        static_configs:
        - targets: [ 0.0.0.0:8080 ]
  awsecscontainermetrics:
    collection_interval: 20s

processors:
  filter:
    metrics:
      include:
        match_type: strict
        metric_names:
          - ecs.task.memory.utilized
          - ecs.task.memory.reserved
          - ecs.task.cpu.utilized
          - ecs.task.cpu.reserved
          - ecs.task.network.rate.rx
          - ecs.task.network.rate.tx
          - ecs.task.storage.read_bytes
          - ecs.task.storage.write_bytes
  metricstransform: # update metric names
    transforms:
      - metric_name: ecs.task.memory.utilized
        action: update
        new_name: MemoryUtilized
      - metric_name: ecs.task.memory.reserved
        action: update
        new_name: MemoryReserved
      - metric_name: ecs.task.cpu.utilized
        action: update
        new_name: CpuUtilized
      - metric_name: ecs.task.cpu.reserved
        action: update
        new_name: CpuReserved
      - metric_name: ecs.task.network.rate.rx
        action: update
        new_name: NetworkRxBytes
      - metric_name: ecs.task.network.rate.tx
        action: update
        new_name: NetworkTxBytes
      - metric_name: ecs.task.storage.read_bytes
        action: update
        new_name: StorageReadBytes
      - metric_name: ecs.task.storage.write_bytes
        action: update
        new_name: StorageWriteBytes

  resource:
    attributes: # rename resource attributes which will be used as dimensions
      - key: ClusterName
        from_attribute: aws.ecs.cluster.name
        action: insert
      - key: aws.ecs.cluster.name
        action: delete
      - key: ServiceName
        from_attribute: aws.ecs.service.name
        action: insert
      - key: aws.ecs.service.name
        action: delete
      - key: TaskId
        from_attribute: aws.ecs.task.id
        action: insert
      - key: aws.ecs.task.id
        action: delete
      - key: TaskDefinitionFamily
        from_attribute: aws.ecs.task.family
        action: insert
      - key: aws.ecs.task.family
        action: delete

exporters:
  awsprometheusremotewrite:
    endpoint: "https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-647c2794-32a4-4ded-95e1-59bc7ecd633c/api/v1/remote_write"
    aws_auth:
      region: "us-east-1"
      service: "aps"
  logging:
    loglevel: debug
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
    
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [logging, awsprometheusremotewrite]
    metrics/ecs:
      receivers: [awsecscontainermetrics]
      processors: [filter]
      exporters: [logging, awsprometheusremotewrite]`

**Comment by mxiamxia** [comment]
Hi, are you running aws-otel-collector in ECS? Can you share the collector logs here?

**Comment by petrokashlikov** [comment]
@mxiamxia yep, I'm running it in ECS as per example here https://aws-otel.github.io/docs/getting-started/prometheus-remote-write-exporter/ecs
[otel-collector-logs.zip](https://github.com/aws-observability/aws-otel-collector/files/6377719/otel-collector-logs.zip)

**Comment by mxiamxia** [comment]
Hi @petrokashlikov , there are 2 issues for your use cases. 
1. All your metrics requests are failed to be sent due to the following error and [issue](https://github.com/open-telemetry/wg-prometheus/issues/10). It has been fixed recently and will be included in ADOT collector release by the end of this week.
```
{"component_kind": "exporter", "component_type": "awsprometheusremotewrite", "component_name": "awsprometheusremotewrite", "error": "Permanent error: server returned HTTP status 400 Bad Request: user=257528440878_ws-647c2794-32a4-4ded-95e1-59bc7ecd633c: err: duplicate sample for timestamp. timestamp=2021-04-23T22:27:56.215Z, series={__name__=\"ecs_task_network_rate_tx\"} ", "dropped_items": 8}
```

2. AMP exporter doesn't support to convert resource attributes to metrics labels yet. We're WIP to add the support in AMP exporter for it. it should be released in May (a month from now)
