### ISSUE TITLE
Collector not capturing Resource Attribute ServiceName

### ISSUE THREAD

**Issue by davekant** [aws-observability/aws-otel-collector#483]
The exporter log-stream shows that the ServiceName is undefined.

According to [https://aws-otel.github.io/docs/components/ecs-metrics-receiver#full-configuration-for-task--and-container-level-metrics](full-configuration) the resource attribute aws.ecs.service.name has been defined. 

Our configuration file is 
[otel-container-metrics-config.yaml.txt](https://github.com/aws-observability/aws-otel-collector/files/6392586/otel-container-metrics-config.yaml.txt)

           - key: ServiceName
              from_attribute: aws.ecs.service.name
              action: insert
            - key: aws.ecs.service.name
              action: delete

![otel-log-servicename](https://user-images.githubusercontent.com/1510723/116421221-8d76b700-a836-11eb-9e81-37949288692f.PNG)

**Comment by pingleig** [comment]
It's hard coded as undefined https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/84952e210f4469393e39a8ddbf8cd556d2a79169/receiver/awsecscontainermetricsreceiver/awsecscontainermetrics/resource.go#L52

I think you can use the resource detector processor to add it, the ecs metrics receiver only queries metadata api so it does not have service name.

cc @JohnWu20

**Comment by JohnWu20** [comment]
Yea, it's correct. The current ECS container receiver doesn't support the ServiceName yet.  We are working on supporting it.
