### ISSUE TITLE
AWS Collector build process is inconsistent with OTel Collector build process

### ISSUE THREAD

**Issue by NickSulistio** [aws-observability/aws-otel-collector#494]
**Is your feature request related to a problem? Please describe.**
Hi everyone! For some context on this issue, I'm working on some new features for the upstream `otel-collector` as well as the `otel-collector-contrib`, and wanted to test some of these changes using the `adot-collector`. 

When looking at the `Dockerfile` of the `adot-collector`, it is clear that the binary is built within the container, as evidenced by the line `RUN make amd64-build`. This isn't a problem itself, but it makes it slightly more complicated when replacing packages with local versions in the `go.mod` file.

Since the binary is built within the container, _it won't understand the references to your local directory_. This became an issue when I tried replacing the upstream collector with a line similar to something like:
`replace go.opentelemetry.io/collector => /Users/sulisti/git/o11y/opentelemetry-collector`

**Describe the solution you'd like**
The `otel-collector` as well as the `otel-contrib-collector` do not suffer from the same issue because in their build process, the binaries are made locally first **THEN** copied over to the new container. 

I was wondering if there were any differences between the `adot-collector` and the `otel-collector` that make this complicated or difficult to do. If there aren't any issues with building the `adot-collector` in a similar fashion to the upstream collector, would it be possible to change that?

**Describe alternatives you've considered**

- Tried copying over the local files into the container
   - Gives issues with the `go.mod` file
   - Bloats the container
- Tried pointing the `replace` lines in the `go.mod` file to github repositories
   - Lots of trouble with finding specific version and hash of private repos
   - Is a little bit unnecessary if we're able to point to our local directory

**Additional context**
I have built the `adot-collector` using the solution I've described above and it built/runs fine (at least from what I can tell). I've also chatted with @alolita and @Aneurysm9 about this topic and they are also interested in the differences!

**Comment by pingleig** [comment]
I think we can have two `Dockerfile` I normally call `amd64-build-only` and use a different `Dockerfile` to copy the binary and build the image. 

https://github.com/aws-observability/aws-otel-collector/blob/0f1f82776b2aa20a50fe7277fa621bf8aaccff7d/Makefile#L67-L70

The build everything in docker logic can be changed to build multi arch docker image like [cwagent](https://github.com/aws/amazon-cloudwatch-agent/tree/master/amazon-cloudwatch-container-insights/cloudwatch-agent-dockerfile) to support arm64 #274 

Though actually as long as your updates works in otelcontrib, it should works in adot out of box as long as all the required components are included... The only major different thing is adot can use env var as config, which is pretty useful when working with ECS.

**Comment by mxiamxia** [comment]
It is intended to build the binary in Dockerfile to reduce the external dependencies.  We don't want users to run some pre-steps to build the docker image.

**Comment by anuraaga** [comment]
The Dockerfile can actually branch based on whether a prebuilt binary is available which is a pretty good approach too I think

https://github.com/aws/aws-xray-daemon/blob/master/Tool/src/build-in-docker.sh#L7

Are you generating release binaries by building in Docker? If so, that doesn't seem good, a release binary should only be built once and packaged in all the different formats to ensure there is one ground truth on published binaries.
