### ISSUE TITLE
Support FirehoseCustomHttpsEndpointRequest receiver

### ISSUE THREAD

**Issue by discordianfish** [aws-observability/aws-otel-collector#500]
**Is your feature request related to a problem? Please describe.**
I want to receive Cloudwatch Metric Streams and send it to self-hosted Prometheus/Cortex.

From what I can tell (please correct me if I'm wrong), the only option is to:
- Create a metric stream sending to Kinesis Data Firehose (in otel format)
- Configure the Kinesis Data Firehose to send metrics to an Custom HTTPS Endpoint
- Unwrap the records in the FirehoseCustomHttpsEndpointRequest and forward it to otel-collector (or translate right away to Prometheus remote write format)

**Describe the solution you'd like**
- otel-collector should have a receiver that can receive FirehoseCustomHttpsEndpointRequest
- it should also support validating X-Amz-Firehose-Access-Key

**Describe alternatives you've considered**
- Creating our custom otel distribution which is quite involved
- Creating a proxy between otel and Firehose, but then we'd rather side-step otel completely to avoid that additional hop

**Comment by mxiamxia** [comment]
cc @ntyrewalla @alolita

**Comment by discordianfish** [comment]
Any update? @ntyrewalla @alolita

**Comment by alolita** [comment]
Hi @discordianfish we're looking at implementations to support this pipeline currently. Will post more as we narrow possible solution.

**Comment by tman77** [comment]
Also following, and am interested in any updates.

**Comment by mchene** [comment]
@discordianfish, why not send the metrics directly to a Prometheus-compatible remote write endpoint as described in this recipe, https://github.com/aws-observability/aws-o11y-recipes/tree/main/sandbox/CWMetricStreamExporter?  Could this solve your problem?
