### ISSUE TITLE
Include Batch processor

### ISSUE THREAD

**Issue by pmm-sumo** [aws-observability/aws-otel-collector#502]
**Is your feature request related to a problem? Please describe.**

Currently, Batch processor is not included on the list of [enabled processors](https://github.com/aws-observability/aws-otel-collector/blob/main/pkg/defaultcomponents/defaults.go). Missing it in the pipeline causes some issues, such as causing sending not-efficient batches by the exporter or not being able to limit maximum batch size

**Describe the solution you'd like**

Enable Batch processor

**Comment by at15** [comment]
batch processor is in core collector, and we are appending processors from contrib repo

https://github.com/aws-observability/aws-otel-collector/blob/7f9ec404610ff0d28539796068a56b7299355e44/pkg/defaultcomponents/defaults.go#L50

https://github.com/aws-observability/aws-otel-collector/blob/7f9ec404610ff0d28539796068a56b7299355e44/pkg/defaultcomponents/defaults.go#L69-L81

https://github.com/open-telemetry/opentelemetry-collector/blob/c1e3d479ca759284a08b2570d6ececc58980813e/service/defaultcomponents/defaults.go#L101

```go
	processors, err := component.MakeProcessorFactoryMap(
		attributesprocessor.NewFactory(),
		resourceprocessor.NewFactory(),
		batchprocessor.NewFactory(),
		memorylimiter.NewFactory(),
		probabilisticsamplerprocessor.NewFactory(),
		spanprocessor.NewFactory(),
		filterprocessor.NewFactory(),
	)
```

**Comment by pmm-sumo** [comment]
Thank you @at15 for pointing this out, of course, you are correct. I mixed up the collectors and should have opened the issue against [OpenTelemetry Lambda Collector](https://github.com/open-telemetry/opentelemetry-lambda/tree/main/collector)

**Comment by pmm-sumo** [comment]
Apologies for the mess up. Here's the issue against other repository: https://github.com/open-telemetry/opentelemetry-lambda/issues/89
