### ISSUE TITLE
Exporter to AMP wont work

### ISSUE THREAD

**Issue by kiahmed** [aws-observability/aws-otel-collector#513]
have these in the log when ran it . it can talk receive end but looks like exporting to AMP fails with other errors . can someone help how to tune this or may be some misconfiguration ?

 2021-05-12T06:23:21.657Z        INFO    internal/metrics_adjuster.go:357        Adjust - skipping unexpected point      {"kind": "receiver", "name": "prometheus", "type": "UNSPECIFIED"}

 ERROR   exporterhelper/queued_retry.go:173      Exporting failed. Dropping data. Try enabling sending_queue to survive temporary failures.{"kind": "exporter", "name": "awsprometheusremotewrite", "dropped_items": 0}
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).send
        go.opentelemetry.io/collector@v0.25.0/exporter/exporterhelper/queued_retry.go:173
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsExporter).ConsumeMetrics
        go.opentelemetry.io/collector@v0.25.0/exporter/exporterhelper/metricshelper.go:74
go.opentelemetry.io/collector/processor/batchprocessor.(*batchMetrics).export
        go.opentelemetry.io/collector@v0.25.0/processor/batchprocessor/batch_processor.go:303
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).sendItems
        go.opentelemetry.io/collector@v0.25.0/processor/batchprocessor/batch_processor.go:208
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).startProcessingCycle
        go.opentelemetry.io/collector@v0.25.0/processor/batchprocessor/batch_processor.go:146
2021-05-12T06:02:16.912Z        WARN    batchprocessor/batch_processor.go:209   Sender failed   {"kind": "processor", "name": "batch/metrics", "error": "Permanent error: [Permanent error: invalid temporality and type combination; 

Config:
----------
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  prometheus:
    config:
      scrape_configs:
        - job_name: "app-collector"
          scrape_interval: 10s
          static_configs:
            - targets: ["app-node:12798"]

processors:
  batch/traces:
    timeout: 2s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s

exporters:
  awsprometheusremotewrite:
    endpoint: "https://aps-workspaces.eu-west-1.amazonaws.com/workspaces/********/api/v1/remote_write"
    aws_auth:
      service: "aps"
      region: "eu-west-1"
service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch/metrics]
      exporters: [awsprometheusremotewrite]

  extensions: [pprof]

**Comment by kiahmed** [comment]
made some progress . got rid of the exporter issue and receiver unspecified but still got this weird error looks like receiver not working. Is there any working example of Prometheus receiver for a static_targets ?

ERROR   scrape/scrape.go:1088   Scrape commit failed    {"kind": "receiver", "name": "prometheus", "scrape_pool": "node-collector", "target": "http://relay-node:12798/metrics", "err": "Permanent error: [Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid temporality and type combination; Permanent error: invalid tsMap: cannot be empty map]"}
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport.func1
        github.com/prometheus/prometheus@v1.8.2-0.20210217141258-a6be548dbc17/scrape/scrape.go:1088
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport
        github.com/prometheus/prometheus@v1.8.2-0.20210217141258-a6be548dbc17/scrape/scrape.go:1153
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run
        github.com/prometheus/prometheus@v1.8.2-0.20210217141258-a6be548dbc17/scrape/scrape.go:1039
[ec2-user@ip-172-31-7-205 aws-oltp-collector]$ docker logs --tail 10 aws-otc
        github.com/prometheus/prometheus@v1.8.2-0.20210217141258-a6be548dbc17/scrape/scrape.go:1153
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run
        github.com/prometheus/prometheus@v1.8.2-0.20210217141258-a6be548dbc17/scrape/scrape.go:1039

**Comment by pingleig** [comment]
In your exported metrics do you have `job` or `instance` label? It's a known issue that otel's prometheus receiver does not handle that well and result in unspecified type. 

Also which version are you using?

**Comment by kiahmed** [comment]
I dont know if it has those labels but got rid of the unspecified issue and now get the above error not even sure what it means or what to tweak from here

**Comment by khanhntd** [comment]
Hey @kiahmed, it seems that there are some changes from the "receiver side" lately and it could come from the "prometheus type". Here is the [specific line of code relates to the problem](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d133d6eae48406fe17fbc72c960ff1859a2487d2/exporter/prometheusremotewriteexporter/exporter.go#L126). Therefore, if it is good, **will you able to do these following suggestion:** 
1. Use the open-telemetry-contrib to test if the receiver is able to receive the metrics from the app?
2. Are you able to confirm what metrics have been dropped and what type it is for more easier debug?
