### ISSUE TITLE
Non-string OpenTelemetry span attributes appearing as blank strings in X-Ray UI

### ISSUE THREAD

**Issue by benlandrum** [aws-observability/aws-otel-collector#518]
The AWS OpenTelemetry collector is able to successfully receive non-string span attributes (e.g., integers, boolean variables) and print them via the logging exporter.
```
Attributes:
     -> thread.id: STRING(140441759817600)
     -> iter_int32_t: INT(986)
     -> iter_string_view: STRING(986_hi)
     -> bool_value: BOOL(true)
     -> double_value_i: DOUBLE(986.5)
```

In X-Ray, however, the non-string values show up as empty strings under Traces->[click a trace]->Metadata.  Is this related to the collector configuration, or is this not yet supported by X-Ray?

**Comment by mxiamxia** [comment]
It's an issue in XRayExporter, will make the fix in the coming release.

>Xray Segments and subsegments can include a metadata object containing one or more fields with values of any type, including objects and arrays.
https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html#api-segmentdocuments-metadata

**Comment by jefchien** [comment]
I'd like to look into making the fix for this issue.

**Comment by mxiamxia** [comment]
will have the fix released in next ADOT release.
