### ISSUE TITLE
Exporter for AMP Credential error

### ISSUE THREAD

**Issue by hiranthaPeiris** [aws-observability/aws-otel-collector#520]
Hi,
I am trying to configure AMP exporter but get NoCredentialProviders on logs of the collector as following.
`WARN batchprocessor/batch_processor.go:209 Sender failed {"kind": "processor", "name": "batch/metrics", "error": "Permanent error: Post \"https://aps-workspaces.us-east-1.<workspace>/api/v1/remote_write\": NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}`

I have set aws access key according to default AWS credentials chain and also AWS go SDK as the documentation. what I could be missing here?

Thanks

**Comment by pingleig** [comment]
Are using the collector as a container or the binary directly on your host (mac or ec2 vm etc.)?  If you are running it on your host can try some simple command from aws cli like `aws s3 ls` to see if you get any credential error.

**Comment by hiranthaPeiris** [comment]
hi @pingleig 
I am running collector binary on ec2 instance and as you said am not getting credential errors with `aws s3 ls` . credentials resides in .aws dir in users $home.

**Comment by pingleig** [comment]
I didn't find anything strange in the code https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/10790bb5affa048a61cf13ca20bae19b1eca39e8/exporter/awsprometheusremotewriteexporter/auth.go#L106-L121 The only suspicious part is [Shared Config Fields](https://docs.aws.amazon.com/sdk-for-go/api/aws/session/#:~:text=shared%20config%20fields)

Did you config your credentials in `~/.aws/credentials` can you try export those creds and env var and see if the exporter can pick it up. e.g. `export AWS_ACCESS_KEY....` etc.

**Comment by hiranthaPeiris** [comment]
I have tried with both ways still the same error log. is there a way to rebuild collector with hard coded credentials as a workaround?

**Comment by Aneurysm9** [comment]
@hiranthaPeiris can you share your collector configuration?

I wouldn't recommend attempting to hard code credentials in the collector.  Let's see what we can do to figure out where the disconnect is happening.

**Comment by alolita** [comment]
Marking as resolved.
