### ISSUE TITLE
Traces sampling Rate when using aws otel collector

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#529]
1) Which parameter in OTEL config file (/opt/aws/aws-otel-collector/etc/config.yaml) drive the sampling rate of xray traces which the OTEL agent is sending to xray?

2) Why the localhost endpoint in the X-RAY UI showing 25% throttling, how to find the root cause?

3) In the X-Ray UI, there is sampling UI item in the left navigation, after i create the custom sampling rules, they do not show any data. Why?

**Comment by mxiamxia** [comment]
Hi George,
>Which parameter in OTEL config file (/opt/aws/aws-otel-collector/etc/config.yaml) drive the sampling rate of xray traces which the OTEL agent is sending to xray?

There are two ways in OTel you can setup traces sampling,
1, via OTel Collector config, you can config [tailsamplingprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor) to setup rules on how you like to sampling the received traces data.
2. via OTel SDK, you can set system properties to config the trace sampling ratio. see https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#sampler

**Comment by mxiamxia** [comment]
For the other two questions, could you help to post the screenshots on the customized sampling rules and the pages show throttling info on UI?

**Comment by srprash** [comment]
Hi @georges-git 
The sampling rules in the X-Ray Console/UI are only picked up and processed if you're using an X-Ray SDK and OTel X-Ray receiver. Which SDK are you using and what does your OTel collector configuration look like?

**Comment by georges-git** [comment]
> Hi @georges-git
> The sampling rules in the X-Ray Console/UI are only picked up and processed if you're using an X-Ray SDK and OTel X-Ray receiver. Which SDK are you using and what does your OTel collector configuration look like?

Hello @srprash -
I am using OTEL auto instrumentation agent. Here is my config file:  

extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:55681
  awsxray:
    endpoint: 0.0.0.0:2000
    transport: udp

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s

exporters:
  awsxray:
  awsemf:

service:
  pipelines:
    traces:
      receivers: [otlp,awsxray]
      processors: [batch/traces]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      processors: [batch/metrics]
      exporters: [awsemf]

**Comment by georges-git** [comment]
> Hi George,
> 
> > Which parameter in OTEL config file (/opt/aws/aws-otel-collector/etc/config.yaml) drive the sampling rate of xray traces which the OTEL agent is sending to xray?
> 
> There are two ways in OTel you can setup traces sampling,
> 1, via OTel Collector config, you can config [tailsamplingprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor) to setup rules on how you like to sampling the received traces data.
> 2. via OTel SDK, you can set system properties to config the trace sampling ratio. see https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#sampler

Hello @mxiamxia - 
I am using auto instrumentation OTEL. Below is my otel collector config file. What is the default sampling rate when the tailsamplingprocessor is not mentioned and how do i add the tailsamplingprocessor rules in this below file. Could you insert a example in the below file?

I am using OTEL auto instrumentation agent. Here is my config file:  
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:55681
  awsxray:
    endpoint: 0.0.0.0:2000
    transport: udp

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s

exporters:
  awsxray:
  awsemf:

service:
  pipelines:
    traces:
      receivers: [otlp,awsxray]
      processors: [batch/traces]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      processors: [batch/metrics]
      exporters: [awsemf]

**Comment by georges-git** [comment]
Here is the Xray UI screen shot which shows the throttling between a service and localhost. What is the root cause of this throttling?
<img width="512" alt="Screen Shot 2021-05-26 at 11 08 26 AM" src="https://user-images.githubusercontent.com/59057062/120540388-7e3ada00-c39d-11eb-9567-4a08b1ff4984.png">

**Comment by georges-git** [comment]
> > Hi @georges-git
> > The sampling rules in the X-Ray Console/UI are only picked up and processed if you're using an X-Ray SDK and OTel X-Ray receiver. Which SDK are you using and what does your OTel collector configuration look like?
> 
> Hello @srprash -
> I am using OTEL auto instrumentation agent. Here is my config file:
> 
> extensions:
> health_check:
> 
> receivers:
> otlp:
> protocols:
> grpc:
> endpoint: 0.0.0.0:4317
> http:
> endpoint: 0.0.0.0:55681
> awsxray:
> endpoint: 0.0.0.0:2000
> transport: udp
> 
> processors:
> batch/traces:
> timeout: 1s
> send_batch_size: 50
> batch/metrics:
> timeout: 60s
> 
> exporters:
> awsxray:
> awsemf:
> 
> service:
> pipelines:
> traces:
> receivers: [otlp,awsxray]
> processors: [batch/traces]
> exporters: [awsxray]
> metrics:
> receivers: [otlp]
> processors: [batch/metrics]
> exporters: [awsemf]

Hello @srprash - What do i need to add in the above config file, so i can configure custom sampling in XRAY UI?

**Comment by georges-git** [comment]
> > Hi George,
> > > Which parameter in OTEL config file (/opt/aws/aws-otel-collector/etc/config.yaml) drive the sampling rate of xray traces which the OTEL agent is sending to xray?
> > 
> > 
> > There are two ways in OTel you can setup traces sampling,
> > 1, via OTel Collector config, you can config [tailsamplingprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor) to setup rules on how you like to sampling the received traces data.
> > 2. via OTel SDK, you can set system properties to config the trace sampling ratio. see https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#sampler
> 
> Hello @mxiamxia -
> I am using auto instrumentation OTEL. Below is my otel collector config file. What is the default sampling rate when the tailsamplingprocessor is not mentioned and how do i add the tailsamplingprocessor rules in this below file. Could you insert a example in the below file?
> 
> I am using OTEL auto instrumentation agent. Here is my config file:
> extensions:
> health_check:
> 
> receivers:
> otlp:
> protocols:
> grpc:
> endpoint: 0.0.0.0:4317
> http:
> endpoint: 0.0.0.0:55681
> awsxray:
> endpoint: 0.0.0.0:2000
> transport: udp
> 
> processors:
> batch/traces:
> timeout: 1s
> send_batch_size: 50
> batch/metrics:
> timeout: 60s
> 
> exporters:
> awsxray:
> awsemf:
> 
> service:
> pipelines:
> traces:
> receivers: [otlp,awsxray]
> processors: [batch/traces]
> exporters: [awsxray]
> metrics:
> receivers: [otlp]
> processors: [batch/metrics]
> exporters: [awsemf]

Hello @mxiamxia - Any update?

**Comment by mxiamxia** [comment]
> https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#sampler

Hi George, since you're using OTel auto instrumentation agent. you can following the instruction below to enable the sampling ratio by setting up env variables. Not suggest to use enable `tailsamplingprocessor` in the collector config which has worse performance. 
https://aws-otel.github.io/docs/getting-started/java-sdk/trace-auto-instr#advanced-configuration-of-the-auto-instrumentation-agent

**Comment by srprash** [comment]
>Hello @srprash - What do i need to add in the above config file, so i can configure custom sampling in XRAY UI?

Unfortunately, the OTel auto instrumentation agent doesn't yet support the X-Ray Sampling rules.

**Comment by georges-git** [comment]
> > https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#sampler
> 
> Hi George, since you're using OTel auto instrumentation agent. you can following the instruction below to enable the sampling ratio by setting up env variables. Not suggest to use enable `tailsamplingprocessor` in the collector config which has worse performance.
> https://aws-otel.github.io/docs/getting-started/java-sdk/trace-auto-instr#advanced-configuration-of-the-auto-instrumentation-agent

Hello @mxiamxia  - What is the default sampling rate used by auto instrumentation OTEL agent?

**Comment by mxiamxia** [comment]
> > > https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#sampler
> > 
> > 
> > Hi George, since you're using OTel auto instrumentation agent. you can following the instruction below to enable the sampling ratio by setting up env variables. Not suggest to use enable `tailsamplingprocessor` in the collector config which has worse performance.
> > https://aws-otel.github.io/docs/getting-started/java-sdk/trace-auto-instr#advanced-configuration-of-the-auto-instrumentation-agent
> 
> Hello @mxiamxia - What is the default sampling rate used by auto instrumentation OTEL agent?

There will be no sampling by default if you don't set env var `OTEL_TRACES_SAMPLER_ARG`.  Pls refer OTel SDK [code](https://github.com/open-telemetry/opentelemetry-java/blob/50408d499f85d5761d0a5ed9bf9d77d5ff01fff5/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java#L139)

**Comment by georges-git** [comment]
> > > > https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#sampler
> > > 
> > > 
> > > Hi George, since you're using OTel auto instrumentation agent. you can following the instruction below to enable the sampling ratio by setting up env variables. Not suggest to use enable `tailsamplingprocessor` in the collector config which has worse performance.
> > > https://aws-otel.github.io/docs/getting-started/java-sdk/trace-auto-instr#advanced-configuration-of-the-auto-instrumentation-agent
> > 
> > 
> > Hello @mxiamxia - What is the default sampling rate used by auto instrumentation OTEL agent?
> 
> There will be no sampling by default if you don't set env var `OTEL_TRACES_SAMPLER_ARG`. Pls refer OTel SDK [code](https://github.com/open-telemetry/opentelemetry-java/blob/50408d499f85d5761d0a5ed9bf9d77d5ff01fff5/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java#L139)

Hello @mxiamxia - When you say there is no sampling by default. Are you indicating if the "env var `OTEL_TRACES_SAMPLER_ARG` is not set, then trace is generated for 100% of the requests.

**Comment by georges-git** [comment]
Hello @mxiamxia - When you say there is no sampling by default. Are you indicating if the "env var OTEL_TRACES_SAMPLER_ARG is not set, then all traces are generated for 100% of the requests.

**Comment by mxiamxia** [comment]
> Hello @mxiamxia - When you say there is no sampling by default. Are you indicating if the "env var OTEL_TRACES_SAMPLER_ARG is not set, then all traces are generated for 100% of the requests.

Yes, you're right. As the link I posted above, you can following the instruction below to set the custom sampling ratio. 

>The agent can be configured using standard OpenTelemetry options for configuration. For example, to set the random sampling rate for creating traces, you can set the environment variables OTEL_TRACES_SAMPLER=parentbased_traceidratio and OTEL_TRACES_SAMPLER_ARG=0.3 to configure a sampling rate of 30%.

**Comment by samkahchiin** [comment]
> Hi @georges-git The sampling rules in the X-Ray Console/UI are only picked up and processed if you're using an X-Ray SDK and OTel X-Ray receiver. Which SDK are you using and what does your OTel collector configuration look like?

@srprash  , is there any documentations explaining how to use X Ray SDK and OTel X-Ray receiver?
IF I have chosen Amazon Distro to instrument my apps, does it mean I can't use the custom sampling rule in Xray console?
