### ISSUE TITLE
OTEL-Collector cloudwatch log file name

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#530]
Hello @mxiamxia ,
For some of my apps in fargate, when i execute "otel collector" as a sidecar in fargate, i provide the cloudwatch log group name, region, prefix etc.  For my apps running on EC2, when I am executing "aws-otel-collector" as a process on the EC2, where do i define the cloudwatch log group name, region, prefix etc.? If i don't specify explicitly the cloudwatch log group name for OTEL collector on my EC2, what is the default cloudwatch log group name it uses?

**Comment by mxiamxia** [comment]
If you run aws-otel-collector on EC2, the collector logs are stored on disk only `/opt/aws/aws-otel-collector/logs/aws-otel-collector.log` with 9 backups and 100mb each. 

When you deploy the Collector on ECS, the collector logs were managed and uploaded to CW by ECS with the logs group you configured in task definition, but EC2 dosen't support it as of yet.
