### ISSUE TITLE
otel collector on EC2 config parameters

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#531]
Hello @mxiamxia - Where can i get explanation of each of the below parameters in the otel collector config file on EC2 :
processors:
batch/traces:
timeout: 1s
send_batch_size: 50
batch/metrics:
timeout: 60s

**Comment by mxiamxia** [comment]
>processors:
batch/traces:
timeout: 1s
send_batch_size: 50
batch/metrics:
timeout: 60s

OTel Collector has a [batch processor](https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor) can batch the data before sending to the backend for performance and cost efficiency. 

The default value we provided is based on the batching behavior from the existing AWS products [x-ray daemon(](https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon.html)trace) and [CWAgent](https://www.google.com/search?q=cw+agent&oq=cw+agent&aqs=chrome..69i57j69i60l3.2297j0j4&sourceid=chrome&ie=UTF-8)(metrics). 

It means by default, OTel collector batch your trace data of 1 sec into one request call (or 50 trace events in one request call). For Metrics, it batches your 60s metrics data into one metric request to CW backend. 

You can always modify the parameters as you needed.
