### ISSUE TITLE
OTEL collector config when running as a sidecar in fargate

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#532]
Hello @mxiamxia -

a) Among the files below, which is the recommended config file to use which contains everything? 
b) Is there a documentation explaining the content of these files?

--config=/etc/ecs/container-insights/otel-task-metrics-config.yaml 

other configs
/etc/ecs/ecs-default-config.yaml
/etc/otel-config.yaml

**Comment by mxiamxia** [comment]
Can I understand what you mean by `everything`? You can always use your own customized configuration as you needed based on these example/default configuration.

**Comment by georges-git** [comment]
Hello @mxiamxia - Which of the above configuration files is a superset or inclusive of all otel metrics, contributor insights and any other metrics?
