### ISSUE TITLE
Docker Image support for ARM64

### ISSUE THREAD

**Issue by ulili5** [aws-observability/aws-otel-collector#536]
**Is your feature request related to a problem? Please describe.**
- The current Docker Image is available only on `ARCH=x86_64` this is a huge limitation and frustrating when working with **ARM64** for workload like Graviton 2 or Raspberry

**Describe the solution you'd like**
- Since the project is built in GoLang it's straightforward to generate a multi-architect docker image by adding **ARCH=arm64**

**Describe alternatives you've considered**
- My alternative was to clone this Repo and did a minor change on the `Make` file to generate docker image for ARM64 so we can build our Graviton 2 IKS workload. But, it would be great with the public Docker Hub or ECR Galery to add the ARM64 Docker image support

**Additional context**

**Comment by sethAmazon** [comment]
Using "docker buildx build -t $(DOCKER_NAMESPACE)/$(COMPONENT):$(VERSION) -f ./cmd/$(COMPONENT)/Dockerfile --platform=linux/arm64 --load ." for platform arm64 fails on the build step in the dockerfile both for the current amd64 and if I substitute with a arm64 build. Can you please add how you got this to build for arm64 platform.

**Comment by pingleig** [comment]
The Dockerfile under cmd is for building from source. You can build the binary for amd64 and arm64 directly using go's cross compile and build the docker image (using a different Dockerfile).  https://github.com/aws-observability/aws-otel-collector/issues/494#issuecomment-830434102 also mentioned it a bit.

**Comment by sethAmazon** [comment]
@pingleig it seems in your docker for amazon cloud watch agent you curl the deb. You not build locally. https://github.com/aws/amazon-cloudwatch-agent/blob/master/amazon-cloudwatch-container-insights/cloudwatch-agent-dockerfile/Dockerfile please confirm or deny.

**Comment by pingleig** [comment]
@sethAmazon https://github.com/aws/amazon-cloudwatch-agent/tree/master/amazon-cloudwatch-container-insights/cloudwatch-agent-dockerfile#cloudwatch-agent-dockerfiles it has more than one dockerfile, `source` folder build from source.

**Comment by anuraaga** [comment]
@pingleig Can we go ahead and add building and release the arm64 image with next collector release?

**Comment by pingleig** [comment]
@anuraaga To be honest I don't think we can make it for next release (if it's around end of this month). I  think @sethAmazon has other tasks and we don't have integration test in our test framework yet. We only test arm binary and didn't test arm container image. 

The tricky part is in releasing, we are not using docker build actions. We dump docker image as tar to private s3, then in a different release action, load the tar to push to ECR and Dockerhub.

**Comment by alolita** [comment]
@pingleig @anuraaga please sync up with me before adding this support. I'd like to see a design and maintenance proposal. Thanks!

cc: @ntyrewalla

**Comment by anuraaga** [comment]
I see - I have a feeling the release will be pushed back a bit so if that can help, it would be good to prioritize. Arm64 support is very important for AWS as a whole.

XRay daemon workflow / Dockerfile is here maybe can copy paste something.

https://github.com/aws/aws-xray-daemon/blob/master/.github/workflows/release-publish-Dockerhub.yml

Ideally you can build the image in an action but if not, the actions workflow logs show what buildx commands are run so maybe they can help for copy pasting.

**Comment by sethAmazon** [comment]
I have successfully created a sample commit of how this could work. I will be manually testing this on ecs today. After I will see about integration tests for this issue as well as talk to @alolita about maintenance of this feature.

**Comment by sethAmazon** [comment]
How I tested
https://aws-otel.github.io/docs/setup/ecs 1 and 2.2
1. Upload image to my ecr
2. Create arm64 ec2
3. Create ecs cluster and attach ec2
4. Create iam roles also add ecr read to execution role since to test you need to read from ecr
5. Create task using you will need to use jmb12686/socat instead of alpine/socat:latest since this needs to support arm64
{
  "ipcMode": null,
  "executionRoleArn": "{your execution role arn}",
  "containerDefinitions": [
    {
      "dnsSearchDomains": null,
      "environmentFiles": null,
      "logConfiguration": {
        "logDriver": "awslogs",
        "secretOptions": null,
        "options": {
          "awslogs-group": "/ecs/aws-otel-EC2",
          "awslogs-region": "{your region}",
          "awslogs-create-group": "True",
          "awslogs-stream-prefix": "ecs"
        }
      },
      "entryPoint": null,
      "portMappings": [
        {
          "hostPort": 2000,
          "protocol": "udp",
          "containerPort": 2000
        },
        {
          "hostPort": 4317,
          "protocol": "tcp",
          "containerPort": 4317
        },
        {
          "hostPort": 8125,
          "protocol": "udp",
          "containerPort": 8125
        }
      ],
      "command": [
        "{your command}"
      ],
      "linuxParameters": null,
      "cpu": 0,
      "environment": [],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": null,
      "memoryReservation": 512,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "{your image}",
      "startTimeout": null,
      "firelensConfiguration": null,
      "dependsOn": null,
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": null,
      "name": "aws-otel-collector"
    },
    {
      "dnsSearchDomains": null,
      "environmentFiles": null,
      "logConfiguration": {
        "logDriver": "awslogs",
        "secretOptions": null,
        "options": {
          "awslogs-group": "/ecs/aws-otel-EC2",
          "awslogs-region": "{your region}",
          "awslogs-create-group": "True",
          "awslogs-stream-prefix": "ecs"
        }
      },
      "entryPoint": null,
      "portMappings": [
        {
          "hostPort": 8000,
          "protocol": "tcp",
          "containerPort": 8000
        }
      ],
      "command": null,
      "linuxParameters": null,
      "cpu": 0,
      "environment": [
        {
          "name": "AWS_XRAY_DAEMON_ADDRESS",
          "value": "aws-otel-collector:2000"
        }
      ],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": null,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "611364707713.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-otel-goxray-sample-app:v0.0.1",
      "startTimeout": null,
      "firelensConfiguration": null,
      "dependsOn": [
        {
          "containerName": "aws-otel-collector",
          "condition": "START"
        }
      ],
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": false,
      "links": [
        "aws-otel-collector"
      ],
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": null,
      "name": "aws-otel-emitter"
    },
    {
      "dnsSearchDomains": null,
      "environmentFiles": null,
      "logConfiguration": null,
      "entryPoint": null,
      "portMappings": [],
      "command": null,
      "linuxParameters": null,
      "cpu": 0,
      "environment": [],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": null,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "nginx:latest",
      "startTimeout": null,
      "firelensConfiguration": null,
      "dependsOn": [
        {
          "containerName": "aws-otel-collector",
          "condition": "START"
        }
      ],
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": false,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": null,
      "name": "nginx"
    },
    {
      "dnsSearchDomains": null,
      "environmentFiles": null,
      "logConfiguration": {
        "logDriver": "awslogs",
        "secretOptions": null,
        "options": {
          "awslogs-group": "/ecs/statsd-emitter",
          "awslogs-region": "{your region}",
          "awslogs-create-group": "True",
          "awslogs-stream-prefix": "ecs"
        }
      },
      "entryPoint": [
        "/bin/sh",
        "-c",
        "while true; do echo 'statsdTestMetric:1|c' | socat -v -t 0 - UDP:127.0.0.1:8125; sleep 1; done"
      ],
      "portMappings": [],
      "command": null,
      "linuxParameters": null,
      "cpu": 0,
      "environment": [],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": null,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "jmb12686/socat",
      "startTimeout": null,
      "firelensConfiguration": null,
      "dependsOn": [
        {
          "containerName": "aws-otel-collector",
          "condition": "START"
        }
      ],
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": false,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": null,
      "name": "aoc-statsd-emitter"
    }
  ],
  "placementConstraints": [],
  "memory": "2048",
  "taskRoleArn": "{your task role arn}",
  "compatibilities": [
    "EXTERNAL",
    "EC2"
  ],
  "taskDefinitionArn": "{your task def arn}",
  "family": "aws-otel-EC2",
  "requiresAttributes": [
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.task-iam-role-network-host"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.ecr-auth"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.21"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.task-iam-role"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.container-ordering"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-ecr-pull"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.29"
    }
  ],
  "pidMode": null,
  "requiresCompatibilities": [],
  "networkMode": "host",
  "cpu": "1024",
  "revision": 4,
  "status": "ACTIVE",
  "inferenceAccelerators": null,
  "proxyConfiguration": null,
  "volumes": []
}

**Comment by sethAmazon** [comment]
<img width="1792" alt="Screen Shot 2021-06-23 at 5 14 23 PM" src="https://user-images.githubusercontent.com/81644108/123169428-4cbaa900-d447-11eb-90cf-d5b58b9b7297.png">

**Comment by ulili5** [comment]
@sethAmazon ping me on our internal Slack or Chime. I can share with you my implementation and we can evaluate it...

**Comment by rakyll** [comment]
With Fargate now supporting ARM64, I expect the demand to have ARM64 support will be critical for this image. We should help landing this if any help is needed.

**Comment by anuraaga** [comment]
As an update, we've been working on adding ARM64 support lately and should have it ready soon. Thanks for the patience.

**Comment by jefchien** [comment]
We've just released [v0.16.0](https://github.com/aws-observability/aws-otel-collector/releases/tag/v0.16.0). The new Docker images released to [DockerHub](https://hub.docker.com/r/amazon/aws-otel-collector/tags) and [ECR](https://gallery.ecr.aws/aws-observability/aws-otel-collector) include an ARM64 image.

**Comment by ulili5** [comment]
Thanks great work. @jefchien, @anuraaga and the team
