### ISSUE TITLE
OTL_EXPORTER_OTLP_ENDPOINT

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#546]
Hello @mxiamxia - I have an application running in the docker on ec2 and OTEL agent running as separate process on same ec2 instance. here is my snippet from config.yaml for OTEL agent running on ec2.
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680
      http:
        endpoint: 0.0.0.0:55681

I set OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:55680 which means the otel agent will send the traces to xray using  grpc protocol.  Is that correct understanding?

**Comment by georges-git** [comment]
Hello , Can anyone respond to my above query?

**Comment by mxiamxia** [comment]
> `OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:55680 which means the otel agent will send the traces to xray using grpc protocol. Is that correct understanding?`

Hi George, yes. `OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:55680` will go with gRPC per your setting.

**Comment by mxiamxia** [comment]
> `OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:55680 which means the otel agent will send the traces to xray using grpc protocol. Is that correct understanding?`

Hi George, yes. `OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:55680` will go with gRPC per your setting.
