### ISSUE TITLE
aws-opentelemetry-agent.jar with Springboot Admin console

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#552]
Hello @mxiamxia and AWS team - 
When using OTEL with Spring boot app, spring boot admin console wraps all actual classes with io.openteletry.javaagent.instrumentation.spring.scheduling.SpringSchedulingRunnablewrapper. I would like to see the actual classes and not have the above wrapper obfuscate the actual classes.

Sample picture is attached.   How to fix this?
![Uploading Screen Shot 2021-06-23 at 7.33.31 AM.png…]()

**Comment by mxiamxia** [comment]
I am not sure I understand the question. I realized we have a springboot sample app example that probably can be a reference to your case.

https://github.com/aws-observability/aws-otel-java-instrumentation/tree/main/sample-apps/springboot

**Comment by tedpoovey** [comment]
It is pretty simple in spring boot admin and actuator your class io.opentelemetry.javaagent.instrumentation.spring.scheduling.SpringSchedulingRunnableWrapper
Shows instead of actual class name.  How do we stop this?
