### ISSUE TITLE
Sending springboot application custom metrics using OTEL

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#553]
Hello @mxiamxia and AWS team - Could you provide sample examples (config, code) for sending springboot application custom metrics using OTEL.

**Comment by mxiamxia** [comment]
Since there is no auto-instrument on OTel metrics. you have to manually instrument you service for sending OTel metrics, so it has nothing to do with the framework. can you check the following instruction doc?

https://aws-otel.github.io/docs/getting-started/java-sdk/metric-manual-instr

**Comment by mxiamxia** [comment]
Pls see this springboot example.
https://github.com/aws-observability/aws-otel-java-instrumentation/tree/main/sample-apps/springboot
