### ISSUE TITLE
From which month AWS OTEL going to be supported in Production environment?

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#554]
Hello, From which month AWS OTEL is going to be supported in Production environment?

**Comment by mxiamxia** [comment]
We're following closely with OTel Community on the GA date. OTel Trace for production will be ready in shortly. OTel metrics GA will take a while which is planned by the end of the year.

**Comment by bforbis** [comment]
I have a followup question. Is the intention for the distributions from this repo to be used longterm, or will the configurations here be merged into upstream and users will use the normal `opentelemetry-collector` project?

**Comment by alolita** [comment]
@bforbis The AWS Distro for OpenTelemetry (ADOT) is a downstream distribution of OTEL. AWS provides support for AWS customers as well as security and perf testing for ADOT. There may be specific configurations available in ADOT for AWS service integrations which will always be available downstream unless the changes are generic enough to be integrated upstream. Hope that helps.
