### ISSUE TITLE
Build.gradle changes needed to utilize OTEL for the JAVA app running

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#557]
Hello @mxiamxia and AWS team - 

**What is the minimum additions needed in build.gradle to build auto-instrumentation OTEL with my JAVA app?**
Earlier I had the below 3.

a) runtimeOnly 'io.opentelemetry:opentelemetry-api-metrics:0.15.0-alpha'
b) implementation "io.opentelemetry:opentelemetry-api:0.15.0"
c) implementation "com.amazonaws:aws-xray-recorder-sdk-log4j:2.8.0"

**Instead of above a),b),c) -  I am planning to replace it with the below.**

implementation platform("io.opentelemetry:opentelemetry-bom:1.3.0")
  implementation('io.opentelemetry:opentelemetry-api')
 

**Do I need to include the bom:1.3.0? How to say the latest version of the bom without hardcoding the version?**

**Comment by sethAmazon** [comment]
@mxiamxia is it recommended to use the otel jars directly? I was under the assumption we should use the aws otel jars.

**Comment by sethAmazon** [comment]
"Do I need to include the bom:1.3.0" no I do not think this is possible.

https://opentelemetry.io/docs/java/manual_instrumentation/#set-up api-metrics will be required if you are using metrics and not spans.

Do you need to inject x ray trace id into your log4j j configuration? https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-log4j/src/main/java/com/amazonaws/xray/log4j/Log4JSegmentListener.java

@mxiamxia please confirm or deny any of what I have said

**Comment by mxiamxia** [comment]
Thanks Seth for the support. Added my comment on top of it. 

```
BOM means the bundled dependencies. We can find the full OTel dependency jar list in the link below. A lot of dependencies in the list is not required for setting up ADOT with x-ray and CW metrics.
 
Their latest OpenTelemety lib version is 1.3.x . can you change your 2 OTel deps to 1.3.x as below
 
a) implementation 'io.opentelemetry:opentelemetry-api-metrics:1.3.x”. 
b) implementation "io.opentelemetry:opentelemetry-api:1.3.x". 
 
https://search.maven.org/artifact/io.opentelemetry/opentelemetry-bom/1.3.0/pom
 


```

**Comment by anuraaga** [comment]
Metrics API is not stable so has a version like `1.3.0-alpha` in case you want to opt-in to the nightmare (the next version is going to be completely rewritten by scratch). You almost assuredly do not want to be using the metrics API in your application.
