### ISSUE TITLE
bug - Jaeger Receiver --> Xray Exporter not working

### ISSUE THREAD

**Issue by schanjr** [aws-observability/aws-otel-collector#562]
What is expected: 
I have a configuration like below in v0.9 OTEL collector. 
```yaml
receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint: 0.0.0.0:14268

processors:
  batch:

exporters:
  awsxray:
    region: 'us-west-2'
    indexed_attributes: ['descriptions']
    max_retries: 3

service:
  pipelines:
    traces:
      receivers: [jaeger]
      processors: [batch]
      exporters: [awsxray]

```

I am intentionally creating a Jaeger receiver to be exported as Xray into AWS Xray

What happened: 
In my code, I generated a trace id with a format of hexadecimal and 32 characters which gets sent to the Jaeger Receiver, but the collector complains 

```json
2021-06-28T10:45:49.621Z        DEBUG   awsxrayexporter@v0.25.0/awsxray.go:54   TracesExporter  {"kind": "exporter", "name": "awsxray", "type": "awsxray", "name": "awsxray", "#spans": 6}
2021-06-28T10:45:49.621Z        DEBUG   awsxrayexporter@v0.25.0/awsxray.go:65   Error translating span. {"kind": "exporter", "name": "awsxray", "error": "invalid xray traceid: 608919ac59d40d74d03e146bb342b875"}
```

When I use a receiver like OTLP ---> Xray exporter, things were fine. 

```json
2021-06-28T10:28:24.441Z        DEBUG   awsxrayexporter@v0.19.0/awsxray.go:78   request: {
  TraceSegmentDocuments: ["{\"name\":\"169.254.169.254\",\"id\":\"37718453d47fa751\",\"start_time\":1624876098.398348,\"trace_id\":\"1-60d9a442-93350ce0bd17a9f434103234\",\"end_time\":1624876099.4002655,\"http\":{\"request\":{\"method\":\"PUT\",\"url\":\"http://169.254.169.254/latest/api/token\"},\"response\":{\"status\":500,\"content_length\":0}},\"fault\":true,\"error\":false,\"cause\":{\"exceptions\":[{\"id\":\"c64981855a94d2c4\",\"message\":\"socket hang up\",\"type\":\"\"}]},\"aws\":{\"xray\":{\"sdk\":\"opentelemetry for nodejs\",\"sdk_version\":\"0.18.0\",\"auto_instrumentation\":false}},\"metadata\":{\"default\":{\"http.error_message\":\"socket hang up\",\"http.error_name\":\"Error\",\"otel.resource.service.name\":\"dt-otel-nodejs-express-reference\",\"otel.resource.telemetry.sdk.language\":\"nodejs\",\"otel.resource.telemetry.sdk.name\":\"opentelemetry\",\"otel.resource.telemetry.sdk.version\":\"0.18.0\"}},\"namespace\":\"remote\"}\n"]
}  
```

I haven't looked much into the code, but my initial suspicion is that there is something wrong between along the processing of `jaeger receiver --> xray exporter`. It should change the standard trace_id format from `608919ac59d40d74d03e146bb342b875` to `1-608919ac-59d40d74d03e146bb342b875` - at least that was the behavior for the OTLP receiver example. 

Would be glad with any feedbacks. Let me know. Thanks. 

Disclaimer, using OTLP is not an option for me in the jruby world right now due to protobuf gem is broken in jruby. I want to export traces to Xray, and Jaeger seems to be one of the only few options. 

I was able to instrument a nodejs app using OTLP --> Xray.

**Comment by sethAmazon** [comment]
@mxiamxia I would like to look at this ticket.

**Comment by sethAmazon** [comment]
Are there any logs on the span input? I want to see fi the input is any different for Jaeger and otlp.

**Comment by sethAmazon** [comment]
So there is a similar ticket https://github.com/open-telemetry/opentelemetry-collector/issues/3405. The solution given was to have the user use a proper xray trace id instead of having xray do the trace id change. Then wait until the xray will support random trace ids. @mxiamxia is this the same way we should handle this ticket?

**Comment by sethAmazon** [comment]
How to use the go id generator for otel https://aws-otel.github.io/docs/getting-started/go-sdk

**Comment by schanjr** [comment]
I got around the problem by setting the context manually. I know the JRUBY don't have a generator yet. I'm using the xray `OpenTelemetry::Propagator::XRay::TextMapPropagator.new#.inject` method and storing it into the current context. It should ideally be taking over the job of the Id Generator. 

Screenshots below with my attempt on a JRUBY repository. 
trace_id
![image](https://user-images.githubusercontent.com/8445726/123673925-9b1ade00-d873-11eb-8329-973ad018a74f.png)
span_id
![image](https://user-images.githubusercontent.com/8445726/123673936-a0782880-d873-11eb-9ec4-10ee794ab3e9.png)


This one is nodejs
![image](https://user-images.githubusercontent.com/8445726/123674421-2c8a5000-d874-11eb-9379-4c2599c6d49c.png)


Trace Ids for both  jruby and nodejs is the same length, 32 characters. 
Span Id from both the jruby and jruby, is the same length, 16 characters. 


I'll double check again in my code. But could you let me know if the jaeger receiver transforms a trace_id like `608919ac59d40d74d03e146bb342b875 to 1-608919ac-59d40d74d03e146bb342b875` ? 
@sethAmazon

**Comment by mxiamxia** [comment]
Hi, jaeger receiver doesn't do the trace_id conversion and it should not happen in the collector side.  The trace_id conversion has to happen in the application side for now and support random trace_id format in AWS X-Ray is on the roadmap but there is no ETA on it yet.

**Comment by schanjr** [comment]
thanks for the answers

**Comment by sanasz91mdev** [comment]
any update for XRAY supporting random traceid format? @mxiamxia
