### ISSUE TITLE
otel errors

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#568]
Hello @mxiamxia and aws team :  I see following errors in the log file.   How to resolve this?

[opentelemetry.auto.trace 2021-06-30 03:40:53:246 -0400] [http-nio-8080-exec-1] WARN io.opentelemetry.javaagent.instrumentation.tomcat.common.TomcatTracer - Malformed url? scheme: http, host: null, port: 8080, path: null, query: null

**Comment by sethAmazon** [comment]
I think I saw this error before. Can you try using http://localhost:{otel port} if you are using otel as the collector.
