### ISSUE TITLE
Configure Logs Group for OTEL Metrics

### ISSUE THREAD

**Issue by dentonmwood** [aws-observability/aws-otel-collector#573]
We need to be able to configure all log groups used by OTEL. Specifically, we're trying to cut down on CloudWatch costs, so we need all log groups to have an expiration date. 

Setup (stated in a separate issue, but reiterating here): we have a Java Spring app deployed as an ECS task with the OTEL collector also defined within the task. We're using the JAR for automatic configuration as defined [here](https://aws-otel.github.io/docs/getting-started/java-sdk/trace-auto-instr). The ECS task definition is deployed by a CloudFormation template. We boot the OTEL container with the ECS default config (`--ecs-default-config.yaml`).

I can configure the OTEL container within our ECS task to use a custom CloudWatch Logs group we've created with an expiration date. However, it appears that OTEL is also creating its own CloudWatch group: "/aws/ecs/application/metrics". I checked the ECS default config you all define and see it listed there. Is there any way to specify an environment variable or something to change this?

**Comment by pingleig** [comment]
You mean the log group in EMF Exporter https://github.com/aws-observability/aws-otel-collector/blob/a5c7496df7e7fd304a7d4c05f99d90cf47311849/config/ecs/ecs-default-config.yaml#L29

The default config has `statsd` and `otlp` so it may receive metrics data and export them using EMF exporter. If you only need trace, you can use a different config via env var. For ECS you can use SSM parameter to inject environment variable. See https://aws-otel.github.io/docs/setup/ecs/config-through-ssm

**Comment by mxiamxia** [comment]
You can't change log group name by env variables. But you can always lunch your ECS service and OTel sidecar with your own configuration. So you can set your own log group name, metric namespace, etc. 

The default config `--ecs-default-config.yaml` is for a general case, and we don't expect it applies to all users. 

Instructions for setup OTel in ECS with custom configuration.
https://aws-otel.github.io/docs/setup/ecs#5-custom-opentelemetry-configuration
