### ISSUE TITLE
The latest version of Logzio exporter failed to be started on EC2 and OnPremise hosts

### ISSUE THREAD

**Issue by mxiamxia** [aws-observability/aws-otel-collector#574]
**Is your feature request related to a problem? Please describe.**
OTel Collector will be failed to start on EC2 and OnPremise instances if logzioexporter is enabled in the configuration setup. 

**logzio component version**
`github.com/open-telemetry/opentelemetry-collector-contrib/exporter/logzioexporter v0.29.1-0.20210629211423-0997f3c4f429`

Errors when 
```
{2021-06-30 02:07:07.482889992 +0000 UTC m=+0.046130011, Level:info, Caller:go.opentelemetry.io/collector@v0.29.1-0.20210629183146-cbee3b39483c/service/internal/builder/exporters_builder.go:231, Message:Ignoring exporter as it is not used by any pipeline, Stack:}^M
2021/06/30 02:07:07 application run finished with error: cannot build pipelines: cannot build builtExporters: error creating logzio exporter: mkdir /home/aoc: permission denied
```

**Comment by mxiamxia** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2925

**Comment by straussb** [comment]
Do not resolve this issue until https://github.com/aws-observability/aws-otel-collector/commit/86d542ef6c9afbab2f5fc94d52a1a2e1f7b839c2 is reverted, after logzio is fixed.

**Comment by alolita** [comment]
@sethAmazon can you verify if this fix was merged upstream?

**Comment by sethAmazon** [comment]
The tests have been aded back. Closing this ticket.
