### ISSUE TITLE
latest otel collector version for ec2 and fargate

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#579]
Hello @mxiamxia and aws team:

**Question 1:  For EC2, I am getting the collector in the following way. It shows the version as 0.8.0. What is the latest version? How to get the latest version?**

wget https://aws-otel-collector.s3.amazonaws.com/amazon_linux/amd64/latest/aws-otel-collector.rpm 
sudo rpm -Uvh  ./aws-otel-collector.rpm 
sudo /opt/aws/aws-otel-collector/bin/aws-otel-collector-ctl -c /opt/aws/aws-otel-collector/etc/config.yaml -a start
sudo /opt/aws/aws-otel-collector/bin/aws-otel-collector-ctl -c /opt/aws/aws-otel-collector/etc/config.yaml -a status
{
  "status": "running",
  "starttime": "2021-07-15T12:29:26+0000",
  "version": "v0.8.0"
}

**Question 2: For ECS in fargate: when pulling the image from "public.ecr.aws/aws-observability/aws-otel-collector:latest" , what version it will pull?**

**Comment by sethAmazon** [comment]
1. V0.11.0 https://github.com/aws-observability/aws-otel-collector/releases/tag/v0.11.0 is latest

**Comment by sethAmazon** [comment]
2. It should be V0.11.0 https://gallery.ecr.aws/aws-observability/aws-otel-collector

**Comment by sethAmazon** [comment]
https://aws-otel-collector.s3.amazonaws.com/amazon_linux/amd64/v0.11.0/aws-otel-collector.rpm download the latest rpm here

**Comment by sethAmazon** [comment]
You can also pull 0.11.0 directly "docker pull public.ecr.aws/aws-observability/aws-otel-collector:v0.11.0"

**Comment by sethAmazon** [comment]
I download with the same link and I got agent version 0.11.0.
<img width="567" alt="Screen Shot 2021-07-15 at 10 44 21 AM" src="https://user-images.githubusercontent.com/81644108/125807689-13b74bac-543c-48d2-a314-dc226a5c9336.png">

**Comment by georges-git** [comment]
Hello, I don't want to hard code versions. 
1) Would "wget https://aws-otel-collector.s3.amazonaws.com/amazon_linux/amd64/latest/aws-otel-collector.rpm"  pull the lates  0.11 version when running otel on ec2 ?

2) Would this "public.ecr.aws/aws-observability/aws-otel-collector:latest" pull the lates 0.11 version for running otel as sidecar in fargate?

**Comment by khanhntd** [comment]
Question 1 and 2 will give the same answer: it will always pull the latest one and if you want to know what is the latest version, please checkout the latest tag with release: https://github.com/aws-observability/aws-otel-collector/releases. For now, I will close this issue for now and if you have any more questions, please let us know and we will support you.
