### ISSUE TITLE
Waiting for an answer: otel metrics with statsd giving configuration error when starting aws-otel-collector

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#580]
Hello @mxiamxia and aws team:

****Question 1: I am trying to send my springboot micrometer application metrics via statsd. following is my OTEL collector config.yaml. When starting the collector, it is giving following error:**
* '' has invalid keys: timer_histogram_mapping
2021/07/15 09:00:40 application run finished with error: cannot load configuration: error reading receivers configuration for statsd: 1 error(s) decoding:**

**This is the config file:**
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680
      http:
        endpoint: 0.0.0.0:55681
  awsxray:
    endpoint: 0.0.0.0:2000
    transport: udp
  statsd:
    endpoint: 0.0.0.0:8125
    aggregation_interval: 60s
    enable_metric_type: false
    timer_histogram_mapping:
      - statsd_type: "histogram"
        observer_type: "gauge"
      - statsd_type: "timer"
        observer_type: "gauge"

**Question 2: How do i configure the same kind of statsd for otel collector running as sidecar in fargate?**

**Comment by gavindoudou** [comment]
Can you include the config with indentation? I cannot check if the config is correct like that.

**Comment by georges-git** [comment]
Question: **Still waiting for an answer. How do i configure the same kind of statsd for otel collector running as sidecar in fargate?**

**Comment by georges-git** [comment]
Question: Still waiting for an answer. How do i configure the same kind of statsd for otel collector running as sidecar in fargate?

**Comment by gavindoudou** [comment]
Do you want to use ECS Fargate? Here is the link: https://aws-otel.github.io/docs/setup/ecs

**Comment by georges-git** [comment]
Hello, Where are the specific instructions on how to configure statsd for OTEL running as sidecar in ECS Fargate?

**Comment by gavindoudou** [comment]
Did you click the link I provided? That's the instruction.

**Comment by georges-git** [comment]
That does not provide i have been asking.

**Comment by gavindoudou** [comment]
Hi, do you use slack in cloud-native.slack.com workspace? We can talk there, maybe have a call.

**Comment by georges-git** [comment]
Hello, Is your slack id : Kun Yuan?

**Comment by gavindoudou** [comment]
Had the call, if you want to have some metrics collected automatically, you can take a look at this receiver: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/awscontainerinsightreceiver It has the metrics you need.

**Comment by georges-git** [comment]
I am using this for Ecs/fargate. Need EC2 standalone install host metrics via stated receiver in otel collector.
