### ISSUE TITLE
Updated traces performance test results for Datadog exporter against real backend

### ISSUE THREAD

**Issue by mx-psi** [aws-observability/aws-otel-collector#593]
Hi,

Please find the updated performance results for the `datadog` trace exporter as of commit a8603ce9fe3d030020d6cb8f21d44c4813a403b3 below. The tests were run against an internal environment following the instructions of the aws-otel-test-framework repository. 

<details>
    <summary>100 TPS</summary>

```json
{
   "testcase":"datadog_exporter_trace_mock",
   "instanceType":"m5.2xlarge",
   "receivers":[
      "otlp"
   ],
   "processors":[
      "batch"
   ],
   "exporters":[
      "datadog"
   ],
   "dataType":"otlp",
   "dataMode":"trace",
   "dataRate":100,
   "avgCpu":8.565867782510242,
   "avgMem":74.50371413333333,
   "commitId":"dummy_commit",
   "collectionPeriod":10,
   "testingAmi":"soaking_linux"
}
```

</details>

<details>
    <summary>1000 TPS</summary>

```json
{
   "testcase":"datadog_exporter_trace_mock",
   "instanceType":"m5.2xlarge",
   "receivers":[
      "otlp"
   ],
   "processors":[
      "batch"
   ],
   "exporters":[
      "datadog"
   ],
   "dataType":"otlp",
   "dataMode":"trace",
   "dataRate":1000,
   "avgCpu":28.722534286136238,
   "avgMem":75.89580799999999,
   "commitId":"dummy_commit",
   "collectionPeriod":10,
   "testingAmi":"soaking_linux"
}
```
</details>

<details>
    <summary>5000 TPS</summary>

```json
{
   "testcase":"datadog_exporter_trace_mock",
   "instanceType":"m5.2xlarge",
   "receivers":[
      "otlp"
   ],
   "processors":[
      "batch"
   ],
   "exporters":[
      "datadog"
   ],
   "dataType":"otlp",
   "dataMode":"trace",
   "dataRate":5000,
   "avgCpu":99.33122504914861,
   "avgMem":89.73421226666667,
   "commitId":"dummy_commit",
   "collectionPeriod":10,
   "testingAmi":"soaking_linux"
}
```

</details>

We also conducted end to end testing to validate the behavior.

---

cc @alolita for OTLP Tracing stability

**Comment by alolita** [comment]
Hi @mx-psi Thanks for the perf results for the trace exporter. Did you use the current Collector release (https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.31.0) for these tests?

**Comment by mx-psi** [comment]
@alolita I ran the tests using the latest available AWS OpenTelemetry Collector commit, which uses v0.30.0 of all components. I can re-run the tests with the contrib distro v0.31.0 or wait until AWS releases an updated version of their Collector. Would either of those work?

**Comment by mx-psi** [comment]
@alolita That makes sense, we can keep this issue open and I will re-run the test when that happens. Thanks for the help here.

**Comment by mx-psi** [comment]
Superseded by aws-observability/aws-otel-test-framework#340
