### ISSUE TITLE
-javaagent:/opt/aws-opentelemetry-agent.jar

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#594]
Hello,

What is a recommended practice from the below options when using this "-javaagent:/opt/aws-opentelemetry-agent.jar" for sprinboot app running in docker in Fargate container. Are both ok or is one preferred over other and why?

-javaagent:/opt/aws-opentelemetry-agent.jar in the ENTRYPOINT in Dockerfile

OR

ENV JAVA_TOOL_OPTIONS=-javaagent:/opt/aws-opentelemetry-agent.jar  in Dockerfile

**Comment by mxiamxia** [comment]
You can find the suggested configuration in java-agent user guide. I put the 2nd option in the user guide.
https://aws-otel.github.io/docs/getting-started/java-sdk/trace-auto-instr#running-the-agent-in-docker
