### ISSUE TITLE
hostmetricsreceiver

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#595]
Hello, 
1)Does this hostmetrics configuration in the below file only applies to EC2 and not fargate?
https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/hostmetricsreceiver/README.md

2) How to get the cpu, mem, disk, and network metrics from fargate task and each container running in the task. Then I would like to create alerts on them.  Which file needs to be configured? Could you provide a sample file to get these metrics.

**Comment by alolita** [comment]
@Konig-Corey We'll take a look at the hostmetricsreceiver.

**Comment by Konig-Corey** [comment]
👍
