### ISSUE TITLE
How to configure statsd receiver for OTEL collector running as fargate sidecar?

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#601]
I am running Java Sprinboot application and would like to send the application metrics, JVM metrics and host specific metrics via statsd receiver in OTEL collector. **How to configure statsd receiver for OTEL collector running as fargate sidecar?**

**Could you provide a full example and documentation link for configuring statsd receiver for OTEL collector running as fargate sidecar?**

**Comment by georges-git** [comment]
Hey AWS folks - Any update on the above question?

**Comment by georges-git** [comment]
Hello Min, and AWS team: Still waiting for an answer for the above.

**Comment by mxiamxia** [comment]
Had met with George to discuss these issues today. Closed the issue.
