### ISSUE TITLE
Host metrics receiver, statsd clarifications

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#612]
Hello Min, AWS team - Could you clarify the following:

1)	Is the following way of incorporating “Host Metrics Receiver” currently supported in AWS OTEL config.yaml? if not, when it would be?
https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/hostmetricsreceiver/README.md

2)	Regarding sending my application metrics via statsd, following is the property and some example values. What shall be the flavor value for sending to AWS statsd receiver in OTEL?
management.metrics.export.statsd.flavor=etsy # or datadog, telegraf

**Comment by georges-git** [comment]
AWS team - We are using OTEL collector for sending traces and metrics to Cloudwatch. **When will the host metrics including network metrics like number of TCP connections stats be available in OTEL collector config in metrics exporter/receiver, so i can see the host network stats in my cloudwatch metrics namespace?**

**Comment by jefchien** [comment]
Hi @georges-git,
1. We do not currently have plans to include the [HostMetricsReceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver) as part of the AWS OTel Collector. This may change, but there is no timeline for it.
2. Based on the [StatsDReceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/statsdreceiver), the messages should be in the etsy format (https://github.com/statsd/statsd/blob/master/docs/metric_types.md).
