### ISSUE TITLE
aws otel statsd receiver

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#613]
Hello Min and AWS team - 

Is there any AWS auto collection of host metrics (cpu, mem, disk, network) via config properties OR cli, sdk, cdk etc and push to it to statsd receiver in OTEL config.yaml?

**Comment by sethAmazon** [comment]
I do not think there are any auto collection of metrics for otel. @mxiamxia please confirm.

**Comment by alolita** [comment]
@georges-git auto-instrumentation is not supported for metrics yet in OTEL and downstream on ADOT.
