### ISSUE TITLE
Feature request: adds support for zipkin receiver

### ISSUE THREAD

**Issue by jcchavezs** [aws-observability/aws-otel-collector#64]
Currently there is not support for native zipkin receiver, this means people instrumenting with zipkin can't report their data?

I can come up with a PR.

**Comment by mxiamxia** [comment]
Hi @jcchavezs, thanks for reaching out. Our goal is to have all the new/supported components in AWS OTel Collector covered by [aws-otel-test-framework](https://github.com/aws-observability/aws-otel-test-framework) with end to end integration tests before enabling it. We're still WIP to improve our testing framework so all the contributors can help to add the test cases on it.

To help on implementing zipkin receiver test cases, We first need to implement a sample app which can send zipkin format of trace data to zipkin receiver so the collector can consume zipkin data. You can reference [the sample app](https://github.com/aws-observability/aws-otel-test-framework-sample-apps/blob/main/sample-apps/sdk/otel-java-sample-apps/springboot/src/main/java/com/amazon/sampleapp/DemoController.java) we have done for OTLP Receiver for Traces. Once we have this sample app ready, we can validate the data in our testing framework. 

We're still working on our integration test framework, if you're interested to contribute. Please take a look the two repos I just shared and we're happy to discuss more on it with you.

**Comment by jcchavezs** [comment]
Thanks for the quick response. I think the second link is broken but yeah I can volunteer for writing such sample app.

**Comment by pingleig** [comment]
Included https://github.com/aws-observability/aws-otel-collector/blob/0134db77f6b4f1c8263e7423179a715cb233b485/pkg/defaultcomponents/defaults.go#L43

Sample app is in https://github.com/aws-observability/aws-otel-test-framework/tree/terraform/sample-apps/jaeger-zipkin-sample-app
