### ISSUE TITLE
otel collector config.yaml

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#663]
Hello, I am using AWS otel collector config.yaml and sending metrics via stasd. I have currently following values:
statsd:
    endpoint: 0.0.0.0:8125
    aggregation_interval: 60s

Clarification:  If i want to send the metrics every 10 secs, would changing "aggregation_interval to 10 secs" do the job, or is there other parameter to configure to flush every 10 secs?

**Comment by khanhntd** [comment]
Yes. According to the document, the[ aggregation_interval is similar to the flush interval in statsD](https://aws-otel.github.io/docs/components/statsd-receiver). Therefore, changing the aggregation interval to 10s will change the setting to: for every 10 second, send the last metrics with aggregation to the workflow
