### ISSUE TITLE
OTEL_EXPORTER_OTLP_ENDPOINT, sending traces to ec2 and fargate

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#664]
Hello, 

I am running dockerized applications both in EC2 and Fargate.

 
1) If my OTEL config.yaml is listening for oltp grpc at 55680 port and oltp http at port 55681; and if I set “OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:55680” in my application Dockerfile, it is going to use grpc protocol using port 55680 to send oltp traces to cloudwatch. Is that correct?
 
2) If my OTEL config.yaml is listening for oltp grpc at 4317 port and oltp http at port 55681; and if I do not set “OTEL_EXPORTER_OTLP_ENDPOINT” in my application Dockerfile, it will automatically send the oltp traces to cloudwatch using grpc on port 4317. Is that correct?
 
 
3) If my OTEL config.yaml is listening for oltp grpc at 4317 port and oltp http at port 55681, and if I set “OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:55680 in my application Dockerfile, why are the traces still coming to cloudwatch and what protocol is being used?
 
 
4) If my OTEL config.yaml is listening for oltp grpc at 55680 port and oltp http at port 55681, and if I DO NOT set “OTEL_EXPORTER_OTLP_ENDPOINT in my application Dockerfile, why are the traces still coming to cloudwatch and what protocol is being used?

**Comment by alolita** [comment]
@georges-git can you clarify the pipeline. Is it accurate to assume you're using 

ECS on EC2 and ECS on Fargate --> ADOT Collector using OTLP --> monitoring service you use
