### ISSUE TITLE
Most of soaking tests failing or timing out

### ISSUE THREAD

**Issue by jefchien** [aws-observability/aws-otel-collector#698]
Even looking at all the [previous successful](https://github.com/aws-observability/aws-otel-collector/actions/workflows/soaking.yml?query=is%3Asuccess) soaking tests, there was never a time where all the tests passed. These need to be fixed.

Memory threshold exceeded ~Trying to remove network~
[run-soaking-test (otlp_grpc_exporter_trace_mock, soaking_linux)](https://github.com/aws-observability/aws-otel-collector/runs/4054558304?check_suite_focus=true)
```
│ validator_1  | 16:46:42.806 [main] ERROR
│ com.amazon.aoc.validators.AlarmPullingValidator - alarm
│ otel-soaking-mem-alarm-7d3d08f5833d8e05 is alarming, status is ALARM,
│ metric is [{Id: mem,MetricStat: {Metric: {Namespace:
│ AWSOtelCollector/SoakingTest,MetricName: procstat_memory_rss,Dimensions:
│ [{Name: negative_soaking,Value: false}, {Name: testing_ami,Value:
│ soaking_linux}, {Name: exe,Value: aws-otel-collector}, {Name:
│ launch_date,Value: 2021-10-30}, {Name: instance_type,Value: m5.2xlarge},
│ {Name: testcase,Value: otlp_grpc_exporter_trace_mock}, {Name:
│ InstanceId,Value: i-059b8ea9c7d581911}, {Name: process_name,Value:
│ aws-otel-collector}, {Name: commit_id,Value:
│ cc8eb315135bdfed89782ee2f1368e5445df5ed3}, {Name: data_rate,Value:
│ trace-1000}]},Period: 60,Stat: Average,},ReturnData: true,}], failing to
│ bake
```

Insufficient resources
[run-soaking-test (datadog_exporter_trace_mock, soaking_linux)](https://github.com/aws-observability/aws-otel-collector/runs/4054558489?check_suite_focus=true)
```
│ Error: Error launching source instance: InsufficientFreeAddressesInSubnet: insufficient free addresses to allocate 1 addresses in subnet subnet-036ece2ceb3d31fb1
│ 	status code: 400, request id: 0d037002-dfa5-42b5-b07b-c0cbfa00e892
│ 
│   with module.ec2_setup.module.ec2_setup.aws_instance.sidecar,
│   on ../ec2/main.tf line 88, in resource "aws_instance" "sidecar":
│   88: resource "aws_instance" "sidecar" {
│ 
```

~Soaking test not pulled
[negative-soaking-pulling-1 (sapm_exporter_trace_mock, soaking_windows)](https://github.com/aws-observability/aws-otel-collector/runs/4057114797?check_suite_focus=true)~
```
Run cd testing-framework/terraform/soaking && docker-compose -f validator_docker_compose.yml up --abort-on-container-exit
/home/runner/work/_temp/0f4615fa-7da2-49aa-a26c-8869e8e449fa.sh: line 1: cd: testing-framework/terraform/soaking: No such file or directory
```

No available runners (in progress)
```
Can't find any online and idle self-hosted runner in the current repository, account/organization and enterprise that matches the required labels: 'ubuntu-test'
Waiting for a self-hosted runner to pickup this job...
```
No available runners (timed out)
```
This request was automatically failed because there were no enabled runners online to process the request for more than 1 days.
```

**Comment by jefchien** [comment]
So it seems like the soaking test not being pulled is expected behavior since [run-negative-soaking-test (sapm_exporter_trace_mock, soaking_windows)](https://github.com/aws-observability/aws-otel-collector/runs/4054557822?check_suite_focus=true) failed and the state wasn't cached. The soaking test failed with the same network removal failure.

**Comment by jefchien** [comment]
Misunderstood the error message from the "Trying to remove network" logs. Those are actually because it reaches the memory alarm threshold and fails the test.

**Comment by jefchien** [comment]
The first test mentioned failing is to be expected as based on [previous performance tests](https://github.com/aws-observability/aws-otel-collector/blob/main/docs/performance_model.md#trace-tps-1000), it exceeds our threshold of 400MB.

**Comment by khanhntd** [comment]
The second test: Insufficient Ip Address with the subnet can be solved by [delete unused ENIS (Elastic Network Interfaces) or creating a new subnet](https://aws.amazon.com/premiumsupport/knowledge-center/subnet-insufficient-ips/). I chose the later one since there aren't any unused ENIS.

**Comment by alolita** [comment]
Any updates @khanhntd

**Comment by khanhntd** [comment]
Hey @alolita, @jefchien has opened a PR to remove the soaking test workflow so this issue will be closed when the PR is done.
