### ISSUE TITLE
AWS OTEL java agent 1.7 giving "java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0"

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#704]
Hello, Anyone else seeing this error with AWS OTEL java agent 1.7 and it does not appear with java agent 1.6.

**Comment by sethAmazon** [comment]
Is this related to the collector or the sdk?

**Comment by georges-git** [comment]
This is related to java agent (aws-opentelemetry-agent.jar). So is this a known bug with this java agent 1.7?

**Comment by sethAmazon** [comment]
You may want to ask https://github.com/aws-observability/aws-otel-java-instrumentation team

**Comment by anuraaga** [comment]
Thanks for filing, we're addressing on https://github.com/aws-observability/aws-otel-java-instrumentation/issues/106
