### ISSUE TITLE
 Configure branch protection rules 

### ISSUE THREAD

**Issue by aateeqi** [aws-observability/aws-otel-collector#734]
**Is your feature request related to a problem? Please describe.**
Comply with branch protection requirements

**Describe the solution you'd like**
Add rules that require code owners

**Describe alternatives you've considered**
None

**Additional context**
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by sethAmazon** [comment]
Can I close this @aateeqi ?

**Comment by sethAmazon** [comment]
It seems you have merged a code owners file
