### ISSUE TITLE
HOST metrics configuration in AWS OTEL config.yaml

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#740]
Hello - We are using OTEL collector for sending traces and metrics to Cloudwatch. When will the host metrics including network metrics like number of TCP connections stats be available in OTEL collector config in metrics exporter/receiver, so i can see the host network stats in my cloudwatch metrics namespace?

**Comment by sethAmazon** [comment]
I do not think https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver is supported in adot yet @alolita

**Comment by alolita** [comment]
@georges-git hostmetricsreceiver is not included in ADOT yet. Can you outline how you utilize hostmetrics which will help us prioritize. Thanks!

**Comment by bryan-aguilar** [comment]
Closing as duplicate. Will continue with feature request on #1287
