### ISSUE TITLE
Enable debug symbols

### ISSUE THREAD

**Issue by rakyll** [aws-observability/aws-otel-collector#747]
The `/awscollector` binary in the collector image contains no debug symbols (disabled by -s -w LDFLAGS on build). The lack of debug symbols make it easier to introspect the binary when running, and make it impossible to extract the symbols for profiling and debugging purposes.

**Comment by alolita** [comment]
@aateeqi are there other pros and cons that you can call out. We should consider if this should be an option that can be enabled when needed.

**Comment by aateeqi** [comment]
It appears that one of the downsides is that the build would be significantly larger. After removing -s -w LDFLAGS during build, we can see that the build size increases from ~80M to ~110M
![image](https://user-images.githubusercontent.com/22218928/149227230-8641e6cb-e5dd-48c9-91a6-4f22b0702e6c.png)

![image](https://user-images.githubusercontent.com/22218928/149227019-c2113ead-55aa-47e7-88f9-617baa24207a.png)

**Comment by aateeqi** [comment]
Hey @rakyll, considering the increase in size of the builds, would you say its still worth building with debug flags? Do you see other downsides of enabling this for builds?

**Comment by anuraaga** [comment]
FWIW I'd probably stick with being consistent with upstream. Currently it looks like they strip

https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/scripts/goreleaser-templates/builds.template.yaml#L19

We should probably check upstream if there is interest in enabling debug symbols there and follow suit if desired.

**Comment by Aneurysm9** [comment]
That's a change from what [collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/Makefile#L9) had been doing, which may explain the difference in container image sizes I observed when the releaser repo overwrote the `v0.42.0` tag created from the contrib repo.
