### ISSUE TITLE
OTEL EC2 sidecar CFN incorrectly sets container IP address

### ISSUE THREAD

**Issue by lukestoward** [aws-observability/aws-otel-collector#756]
https://github.com/aws-observability/aws-otel-collector/blob/36226a801328c9d70d415de7f2bea8149b500eaf/deployment-template/ecs/aws-otel-ec2-sidecar-deployment-cfn.yaml#L94

After trying and failing to deploy the OTEL collector as a sidecar container in ECS, I discovered my primary service container could not connect to the collector due to the environment variable containing a container IP alias, which does not work when using [`NetworkMode: awsvpc`](https://github.com/aws-observability/aws-otel-collector/blob/main/deployment-template/ecs/aws-otel-ec2-sidecar-deployment-cfn.yaml#L59). Instead I had to use the loopback address, which allowed the trace exporter to connect. Therefore I believe your example EC2 sidecar stack is incorrect.

The environment variable should be:

```yaml
environment:
    - name: AWS_XRAY_DAEMON_ADDRESS
       value: '127.0.0.1:2000'
```

**Comment by sethAmazon** [comment]
I can't seem to deploy this will cloud formation. Can you post the steps you used to deploy this as well as the inputs. Sorry I have no used cloud formation before so I probably doing something wrong.

**Comment by PaurushGarg** [comment]
This cfn template has been updated now.

**Comment by PaurushGarg** [comment]
This cfn template has been updated now. Please check if it's still give you any deployment errors.

**Comment by PaurushGarg** [comment]
Closing issue as the said template has been update to remove the deployment errors.
