### ISSUE TITLE
Datadog Exporter Key Validation Fails in latest version

### ISSUE THREAD

**Issue by mystical44** [aws-observability/aws-otel-collector#759]
**Describe the bug**
After updating to v0.14.0+, the Datadog Exporter key validation step now fails.  It works fine in v0.13.0

**Steps to reproduce**
Use a valid Datadog Exporter key in the _config.yaml_ similar to:

    datadog:
      api:
        key: "${DD_API_KEY}"

**What did you expect to see?**

    info	utils/api.go:32	Validating API key.	
    {
        "kind": "exporter",
        "name": "datadog"
    }
    info utils/api.go:32 Validating API key. {"kind": "exporter", "name": "datadog"}
    
    
    warn	utils/api.go:41	API key validation failed.	
    {
        "kind": "exporter",
        "name": "datadog"
    }

**What did you see instead?**

infio 	utils/api.go:41	API key validation successful.

**Additional context**
Again, this only occurs after updating to v.0.14.0+

**Comment by jefchien** [comment]
Hi @mystical44, the main difference between v0.13.0 and v0.14.x that would concern the Datadog Exporter is the bump of the exporter from v0.36.0 to v0.38.0 in the [upstream](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/datadogexporter). I don't see this API key issue addressed in the breaking changes in the v0.37.0...v0.38.0 [release notes](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases).

Doing a comparison of the two tags, the API key config definition/sanitization in [config.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.38.0/exporter/datadogexporter/config/config.go#L50-L69) and API key setup in [factory.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.38.0/exporter/datadogexporter/factory.go#L55-L58) appear unchanged. Same with the steps configuring the Datadog client in [metrics_exporter.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.38.0/exporter/datadogexporter/metrics_exporter.go#L96-L100) and the validation in [utils/api.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.38.0/exporter/datadogexporter/internal/utils/api.go). The hash in the [go.sum](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.38.0/exporter/datadogexporter/go.sum#L880-L881) for the go-datadog-api.v2 which contains the client that performs the validation is the same.

I'm not quite sure what would have changed between the versions that would break the API key validation. Please try it with the v0.15.0 AWS OTel Collector (uses Datadog Exporter v0.39.0) and if the issue persists, please open an issue in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues.

**Comment by jefchien** [comment]
It looks like it might be a similar issue to https://github.com/aws-observability/aws-otel-collector/issues/748.

**Comment by mystical44** [comment]
@jefchien After reviewing that issue, I that that is the problem. So it isn't specific to the Datadog Exporter, rather my use of an env variable for the key.

**Comment by jefchien** [comment]
Great! I've made a PR https://github.com/aws-observability/aws-otel-collector/pull/774 to fix the environment variable expansion. Please track the issue there.

**Comment by jefchien** [comment]
We've released [v0.14.2](https://github.com/aws-observability/aws-otel-collector/releases/tag/v0.14.2) and [v0.15.1](https://github.com/aws-observability/aws-otel-collector/releases/tag/v0.15.1) (latest). Please use one of these releases.
