### ISSUE TITLE
ARM build and dependencies

### ISSUE THREAD

**Issue by nrooney** [aws-observability/aws-otel-collector#766]
A team I've been working with has reported that the ARM build is broken, as the dependancies were not building. They rewrote the docker file to get around the issue. Apologies for lack of insight here as I haven't used the tool myself; I'll get some more info tomorrow and report back in this issue.

**Comment by rakyll** [comment]
Related to https://github.com/aws-observability/aws-otel-collector/issues/536.

**Comment by sethAmazon** [comment]
I do not think we support arm64 docker images. @alolita

**Comment by paya-cz** [comment]
There is no arm64 support, at least yet.

Compare:
https://hub.docker.com/r/amazon/aws-otel-collector/tags
With:
https://hub.docker.com/r/amazon/aws-xray-daemon/tags

Disappointing.

**Comment by alolita** [comment]
Hi @paya-cz @nrooney we'll take a look at adding support for arm64 docker images for ADOT. Can you share what your pipeline is - this may be useful for our testing. Thx.

**Comment by paya-cz** [comment]
@alolita Thank you, being able to use ADOT with Graviton2 would certainly be nice.

Please elaborate what you mean by "pipeline".

**Comment by alolita** [comment]
Hi @paya-cz could you specify the pipeline you plan to use these arm64 images for? 

i.e. specify your setup - data source(s) --> receiver (otlp or prometheus) --> exporter (otlp or custom) --> monitoring backend

**Comment by paya-cz** [comment]
@alolita I fear my pipeline is rather uninspiring.

I just follow this, to get traces from nodejs ECS container to show up in AWS XRay:
https://aws-otel.github.io/docs/getting-started/js-sdk/trace-manual-instr

**Comment by alolita** [comment]
Thanks @paya-cz we'll take a look at adding this support.

**Comment by sethAmazon** [comment]
Write up arm64 docker images

Goal

* Be able to build both adm64 and arm64 docker images

How

* Use buildx ability to build multi-platform docker images 
* Split out into 3 buildx commands
    * Why? 
        * You can only load 1 platform image outside of a registry
    * 1 amd64 in make file
    * 1 arm64 in make file
    * 1 build and push both amd64 and arm64 to ecr in ci
        * This command will be run in the ci and require a load
* If statement in dockerfile to decide to build amd64 image or arm64 image based on platform input 
* Make sure we are using a buildx by default supported version of docker
    * Some earlier versions require buildx to be create and not available by default

**Comment by Aneurysm9** [comment]
Should we look at using `goreleaser`, similar to what the upstream release repo is doing?  That seems to be building [artifacts for multiple architectures](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/.goreleaser.yaml#L23-L26), though not arm64 container images.

**Comment by anuraaga** [comment]
The key point is to make sure the qemu arm64 builder is not actually compiling any code - all archs should be built on the GitHub runner first and the Dockerfile references the built artifacts (I believe part of that was already done before). If you accidentally build in qemu itself it will be incredibly slow without benefit.

goreleaser is a good tool for generating those binaries. For the dockerfile x-ray daemon might be a useful reference

https://github.com/aws/aws-xray-daemon/blob/master/Dockerfile#L13
https://github.com/aws/aws-xray-daemon/blob/master/Tool/src/build-in-docker.sh#L9

Also just to make sure it's clear since there's mention of buildx and docker versions, we should just be able to build with the official build-and-push GitHub action with minimal steps.

**Comment by alolita** [comment]
@sethAmazon let's address how we plan to verify these images once built.

**Comment by sethAmazon** [comment]
Added to write up comment

**Comment by jefchien** [comment]
We've just released [v0.16.0](https://github.com/aws-observability/aws-otel-collector/releases/tag/v0.16.0). The new Docker images released to [DockerHub](https://hub.docker.com/r/amazon/aws-otel-collector/tags) and [ECR](https://gallery.ecr.aws/aws-observability/aws-otel-collector) include an ARM64 image.
