### ISSUE TITLE
Dockerfile should build from alpine instead of scratch

### ISSUE THREAD

**Issue by xibz** [aws-observability/aws-otel-collector#770]
Hello! So my team and I are using the `credential_process` feature in the AWS SDK for Go, and this feature allows users to specify their own way of getting credentials through the `~/.aws/credentials` file. However, the [AWS SDK for Go expects `sh`](https://github.com/aws/aws-sdk-go/blob/e2d6cb448883e4f4fcc5246650f89bde349041ec/aws/credentials/processcreds/provider.go#L304) to be present in `PATH`. However, [scratch](https://github.com/aws-observability/aws-otel-collector/blob/main/cmd/awscollector/Dockerfile#L48) does not have `sh`. This makes the feature not usable at all with the `aws-otel-collector` which is a really odd experience when using AWS credentials files.

What I would love to see is either copying `sh` to the scratch workspace or just use alpine all together

**Comment by anuraaga** [comment]
Thanks @xibz - for various reasons we would like to stick with scratch if possible but this seems like an important use case to me. I have filed https://github.com/aws/aws-sdk-go/issues/4193 as it appears to be a gap in the SDK itself, there doesn't seem to be a reason to limit credential_process to environments that have a shell installed. If that got fixed and we updated, would that solve your issue?

**Comment by xibz** [comment]
@anuraaga Yep! That works as well!

**Comment by sethAmazon** [comment]
@anuraaga may I close this ticket?

**Comment by anuraaga** [comment]
@xibz Unfortunately I don't think we will be changing our base image just for credential_process. From the linked issue you seem to have a (too tedious) workaround for now so are you comfortable closing this in favor of the SDK issue?
