### ISSUE TITLE
eks pod not coming up. Error: standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by raviteja36** [aws-observability/aws-otel-collector#784]
Hi,

I'm trying to deploy ADOT to my EKS cluster but for some reasons, not sure why I'm seeing the below error when trying to execute

# kubectl apply -f aws-otel-collector/examples/eks/aws-cloudwatch/otel-sidecar.yaml
#kubectl logs aws-otel-eks-sidecar-69d9db7876-jv6qk -n aws-otel-eks
'standard_init_linux.go:228: exec user process caused: exec format error'

Also I tried to build an image with linux platform and using that image as well getting the same error
"docker build --platform linux/amd64 -t awscollector:linux --file cmd/awscollector/Dockerfile ."
" make docker-build"
All the builds sendup with the same error. 

Please provide the steps if I'm missing anything.

Thanks,
Ravi

**Comment by jefchien** [comment]
Hi @raviteja36,

After a bit of [research](https://stackoverflow.com/questions/67361936/exec-user-process-caused-exec-format-error-in-aws-fargate-service), it looks like the `standard_init_linux.go:228: exec user process caused: exec format error` that you're seeing tends to happen when the architecture that the image was built on is different from the architecture it is running on. All of the images on [Dockerhub](https://hub.docker.com/r/amazon/aws-otel-collector/tags) are currently built for linux/amd64. Please ensure that the worker nodes in your cluster are not ARM based.

I've followed https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/eks-demo.md with a fresh cluster and confirmed that the `eks/aws-cloudwatch/otel-sidecar.yaml` is valid.

**Comment by charanjit-singh** [comment]
Same error

**Comment by bryan-aguilar** [comment]
Hi @charanjit-singh can you please reference the comment above and verify that node and image architecture match?

**Comment by bryan-aguilar** [comment]
Closing this issue as it it old. Please feel free to reopen a new issue if you continue to run into problems.

**Comment by bryan-aguilar** [comment]
@OpMilan29, If you are experiencing an error when installing the ADOT Collector can you please open a new issue.
