### ISSUE TITLE
SSL not supported on OTLP/gRPC port 4317

### ISSUE THREAD

**Issue by paya-cz** [aws-observability/aws-otel-collector#817]
**Is your feature request related to a problem? Please describe.**

Following the OpenTelemetry docs, where SSL is mentioned as a feature:
https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/opentelemetry-exporter-trace-otlp-grpc

```ts
const collectorOptions = {
  // url is optional and can be omitted - default is grpc://localhost:4317
  url: 'grpc://<collector-hostname>:<port>',
  credentials: grpc.credentials.createSsl(),
};
```

I am never able to send any traces if I enable SSL. If I however do not enable SSL, everything works fine.

**Describe the solution you'd like**

Either provide better errors/docs that SSL is not supported, or add support for SSL.

**Describe alternatives you've considered**

Disable SSL.

**Comment by sethAmazon** [comment]
If this is not an amazon specific issue can you please create an issue with the contrib.

**Comment by paya-cz** [comment]
@sethAmazon I do not know if this is amazon specific issue or not.

**Comment by alolita** [comment]
Hi @paya-cz this is an upstream JS SDK issue - please report this issue upstream at https://github.com/open-telemetry/opentelemetry-js/issues
