### ISSUE TITLE
Add steps to configure collector to send data to a different account

### ISSUE THREAD

**Issue by ntyrewalla** [aws-observability/aws-otel-collector#82]
Add steps to enable collector to send data to a different account. Provide examples of the collector config.yaml as well as update the documentation on github.

**Comment by khanhntd** [comment]
Hey @ntyrewalla ,
Here is one of the options for enable collector to send cross account: 

**- Using ECS to send:** https://aws.amazon.com/blogs/opensource/using-aws-distro-for-opentelemetry-collector-for-cross-account-metrics-collection-on-amazon-ecs/
**- Example configuration:**  https://github.com/aws-observability/aws-otel-collector/blob/main/examples/ecs/aws-prometheus/ecs-ec2-adot-config.yaml

**Comment by khanhntd** [comment]
Hi @ntyrewalla , since the documents are there for you,  I will close this issue for now and if you have any questions, please feel free to open it anytime.
