### ISSUE TITLE
Examples of ADOT collecting traces from envoy

### ISSUE THREAD

**Issue by saaish** [aws-observability/aws-otel-collector#826]
**Describe the question**
A clear and concise description of what the question is.
It would be good to have a documentation that talks about collecting traces from envoy / mesh technology using ADOT on the documentation page
**Steps to reproduce if your question is related to an action**
If possible, provide a recipe for reproducing the what the question relates to.

**What did you expect to see?**
A clear and concise description of what you expect to see.

**Environment**
Describe any aspect of your environment.

**Additional context**

**Comment by alolita** [comment]
Hi @saaish thanks for filing this issue. Can you also file this issue on our ADOT tech docs site at https://github.com/aws-otel/aws-otel.github.io/issues
