### ISSUE TITLE
Naming convention for binary

### ISSUE THREAD

**Issue by sethAmazon** [aws-observability/aws-otel-collector#880]
**Is your feature request related to a problem? 
We have to hardcode binary paths in dockerfile

**Describe the solution you'd like**
Change the names of binary paths in make create commands. The linux binary will chosen by path not name. Ex linux/amd64/aoc instead of aoc_linux_x86_64 

**Describe alternatives you've considered**
Create more make commands so as to not change anything.

**Comment by anuraaga** [comment]
We definitely don't want to change the output file within a published archive, e.g. a docker image. But just changing names of intermediate artifacts from Make commands is acceptable IMO but let's confirm together.
