### ISSUE TITLE
Using Goreleaser

### ISSUE THREAD

**Issue by aateeqi** [aws-observability/aws-otel-collector#886]
We should eventually look into using https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/.goreleaser.yaml to simplify build process and stay consistent with upstream opentelemetry-collector-releases repo.

**Comment by bryan-aguilar** [comment]
I am looking into this in preparation for the February release. @aateeqi  did you do any additional research when initially proposing this idea?

**Comment by Aneurysm9** [comment]
I don't think any further research was performed.  I asked Ameen to create this issue as a placeholder following some discussions we had that we didn't have time to continue at that point.  If you're going to pick this up let's meet briefly after you have a chance to look at how the collector releases repo and collector builder work to talk about what parts of that process make sense for us here.
