### ISSUE TITLE
It's possible that InstanceId label can be collected in task/container level metrics?

### ISSUE THREAD

**Issue by Galactic21** [aws-observability/aws-otel-collector#895]
**Describe the question**

Good morning, I would like to know if it is possible to add the "InstanceId" label in the metrics at the task/container level using the "awsecscontainermetrics" receiver. I noticed that with the "awscontainerinsightreceiver" receiver  in ECS it is possible to check this label. 

![image](https://user-images.githubusercontent.com/32776046/149770978-a93657bc-6d33-4d63-9a63-ec6cbb1d7e9b.png)

I just liked that the receiver also returns the id of the instance where the task/container is located.

**What did you expect to see?**
"InstanceId" label on the metrics collected by the "awsecscontainermetrics" receiver.

**Environment**
Ubuntu 20.04

**Comment by sethAmazon** [comment]
Have you tried https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor?

**Comment by Galactic21** [comment]
I wasn't aware of this processor. After carrying out some tests I managed to do what I wanted. 
Thank you for your guiding @sethAmazon .

Cheers.
