### ISSUE TITLE
Benchmarks - machine configuration

### ISSUE THREAD

**Issue by ssaid11** [aws-observability/aws-otel-collector#94]
The readme has some benchmarks that are useful to understand the resources consumed by the collector, however, there doesn't seem to be any instance size listed. Could you confirm that these are based on a m4.2xlarge EC2 instance as defined [here](https://github.com/aws-observability/aws-otel-collector/blob/main/deployment-template/ec2/aws-otel-ec2-deployment-cfn.yaml)? 

Thanks

**Comment by mxiamxia** [comment]
Hi @ssaid11 , the current benchmarks are provided based on the working laptops. Will provide an EC2 based benchmarks result soon. Thanks for reaching out.

**Comment by mxiamxia** [comment]
New benchmark/performance model has been updated with machine configuration and TPS.
https://github.com/aws-observability/aws-otel-collector/blob/main/docs/performance_model.md
