### ISSUE TITLE
extracfg.txt not working as expected

### ISSUE THREAD

**Issue by AustinWentz** [aws-observability/aws-otel-collector#957]
**Describe the question**
Looking through the code, os.Setenv() gets called for awsProfile and awsCredentialFile key-value pair specified in extracfg.txt, but these variables are not showing up in the running processes environment. Where am I going wrong?

For reference, loggingLevel=DEBUG in the same file does work.

I am using the following to checkout the environment
```sudo cat /proc/<pid>/environ | tr \\0 \\n```

```
LANG=en_US.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
config=--config /opt/aws/aws-otel-collector/etc/config.yaml
```

**tl;dr**
loggingLevel=DEBUG (works)

awsProfile=default (does not work)
awsCredentialFile=~/.aws/credentials (does not work)

**Steps to reproduce if your question is related to an action**
If possible, provide a recipe for reproducing the what the question relates to.
1) Set the above variables in extracfg.txt
2) Start collector with sudo /bin/aws-otel-collector-ctl -a start
3) ps -aux | grep "otel" (get process id)
4) `sudo cat /proc/<pid>/environ | tr \\0 \\n`

**What did you expect to see?**
In the process environment...
```
AWS_PROFILE=default
AWS_SHARED_CREDENTIALS_FILE=~/.aws/credentials
```

**Environment**
Amazon Linux 2, EC2
v 0.16

**Additional context**

**Comment by Aneurysm9** [comment]
I don't believe that is a valid way to check the current status of a process' environment.  Per [the documentation](https://man7.org/linux/man-pages/man5/proc.5.html), it only reports the initial environment for the process:

       /proc/[pid]/environ
              This file contains the initial environment that was set
              when the currently executing program was started via
              execve(2).  The entries are separated by null bytes
              ('\0'), and there may be a null byte at the end.  Thus, to
              print out the environment of process 1, you would do:

                  $ cat /proc/1/environ | tr '\000' '\n'

              If, after an execve(2), the process modifies its
              environment (e.g., by calling functions such as putenv(3)
              or modifying the environ(7) variable directly), this file
              will not reflect those changes.

Is there other observable behavior of the process that you expect to be affected by setting those values that is not?

**Comment by AustinWentz** [comment]
Ah, good catch.

and yes, exporting to AWS X-Ray. Credentials not found.

I might have realized the issue, ~ is resolving to the home directory of the user running the Collector, in the case 'aoc' and not the user under which I have placed the credentials. I will try placing the credentials in the correct place.

**Comment by Aneurysm9** [comment]
That sounds plausible.  Do we have documentation that led you down this path that should be updated?

**Comment by AustinWentz** [comment]
The docs only mention CloudFormation and AWS Systems Manager. I think my use case is special since we don't use either of those to deploy our EC2 instances currently. Trying to set this up for some internal usage at Amazon.

**Comment by AustinWentz** [comment]
Sure enough, putting the credentials in a file that every linux user has read access to worked. Closing.
