### ISSUE TITLE
AWS XRay service map components are disconnected

### ISSUE THREAD

**Issue by Heeminkim87** [aws-observability/aws-otel-collector#960]
hello my project used aws x-ray
and we used otel collector and used java agent

1month ago ,
service map can see connected each components
but recently
service map components are disconnected

and when i check trace Parent ID was null
like this
 https://i.stack.imgur.com/qzduR.png

my project info is here

sidecar [task definition]
public.ecr.aws/aws-observability/aws-otel-collector:latest
 ["--config","/etc/ecs/ecs-default-config.yaml"]

application Docker
ADD https://github.com/aws-observability/aws-otel-java-instrumentation/releases/latest/download/aws-opentelemetry-agent.jar /opt/aws-opentelemetry-agent.jar
ENV JAVA_TOOL_OPTIONS=-javaagent:/opt/aws-opentelemetry-agent.jar
ENV OTEL_RESOURCE_ATTRIBUTES=service.name={servicename}

java -javaagent:/opt/aws-opentelemetry-agent.jar -jar -Dotel.instrumentation.common.default-enabled=true 
-Dotel.instrumentation.opentelemetry-annotations.enabled=true 

i need help. 
could u tell me any proper solution?

thanks

**Comment by sethAmazon** [comment]
Can you turn on debug logs and post that here please.

**Comment by sethAmazon** [comment]
You can use this config 

extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:55681
  awsxray:
    endpoint: 0.0.0.0:2000
    transport: udp
  statsd:
    endpoint: 0.0.0.0:8125
    aggregation_interval: 60s

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s

exporters:
  awsxray:
  awsemf:
    namespace: ECS/AWSOTel/Application
    log_group_name: '/aws/ecs/application/metrics'
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp,awsxray]
      processors: [batch/traces]
      exporters: [awsxray]
    metrics:
      receivers: [otlp, statsd]
      processors: [batch/metrics]
      exporters: [awsemf]

  extensions: [health_check]
  telemetry:
    logs:
      level: info

**Comment by sethAmazon** [comment]
[ecs-default-config.yaml.zip](https://github.com/aws-observability/aws-otel-collector/files/8025633/ecs-default-config.yaml.zip)
You can use this config. If you need me to create a collector with this config let me know
