### ISSUE TITLE
support random trace_id format in AWS X-Ray as traces from jaeger receiver are not exported to AWS xray

### ISSUE THREAD

**Issue by sanasz91mdev** [aws-observability/aws-otel-collector#961]
**Describe the bug**
I am using ADOT collector for forwarding open telemetry traces to AWS xray via Jaeger receiver. My app uses jaeger exporter. So with zero code changes i want my application to work on AWS by just configuring collector such that Jaeger receiver forwards it to AWS Xray 

**Steps to reproduce**
Collector configuration is below

```
extensions:
  health_check:

receivers:
  # Data sources: traces
  jaeger:
    protocols:
      thrift_binary:
        endpoint: 0.0.0.0:6832

processors:
  batch:

exporters:
  awsxray:

service:
  pipelines:
    traces:
      receivers: [jaeger]
      processors: [batch]
      exporters: [awsxray]

  extensions: [health_check]

```

**What did you expect to see?**
As per documentation: [jaeger receiver is supported](https://aws-otel.github.io/docs/components/jaeger-zipkin-receiver#jaeger-receiver), so why is it that X-ray is unable to intake spans as is ? Isnt OpenTelemetry a standard format so X-Ray should support it.

**What did you see instead?**
Received following error:

Feb 03 20:20:29 ip-172-31-31-208.us-east-2.compute.internal aws-otel-collector[6456]: 2022-02-03T20:20:29.677Z        info        service/collector.go:124        Everything is ready. Begin running and processing data.
Feb 03 20:21:06 ip-172-31-31-208.us-east-2.compute.internal aws-otel-collector[6456]: 2022-02-03T20:21:06.200Z        debug        processors/thrift_processor.go:120        Span(s) received by the agent        {"kind": "receiver", "name": "jaeger", "bytes-received": 3228}
Feb 03 20:21:06 ip-172-31-31-208.us-east-2.compute.internal aws-otel-collector[6456]: 2022-02-03T20:21:06.688Z        debug        awsxrayexporter@v0.43.0/awsxray.go:54        TracesExporter        {"kind": "exporter", "name": "awsxray", "type": "awsxray", "name": "awsxray", "#spans": 1}
Feb 03 20:21:06 ip-172-31-31-208.us-east-2.compute.internal aws-otel-collector[6456]: 2022-02-03T20:21:06.688Z        debug        awsxrayexporter@v0.43.0/awsxray.go:99        Error translating span.        {"kind": "exporter", "name": "awsxray", "error": "invalid xray traceid: b04797972f4a6e04b8699a4e0209f52a"}
Feb 03 20:21:30 ip-172-31-31-208.us-east-2.compute.internal aws-otel-collector[6456]: 2022-02-03T20:21:30.916Z        debug        processors/thrift_processor.go:120        Span(s) received by the agent        {"kind": "receiver", "name": "jaeger", "bytes-received": 7827}
Feb 03 20:21:31 ip-172-31-31-208.us-east-2.compute.internal aws-otel-collector[6456]: 2022-02-03T20:21:31.413Z        debug        processors/thrift_processor.go:120        Span(s) received by the agent        {"kind": "receiver", "name": "jaeger", "bytes-received": 2986}
Feb 03 20:21:31 ip-172-31-31-208.us-east-2.compute.internal aws-otel-collector[6456]: 2022-02-03T20:21:31.696Z        debug        awsxrayexporter@v0.43.0/awsxray.go:54        TracesExporter        {"kind": "exporter", "name": "awsxray", "type": "awsxray", "name": "awsxray", "#spans": 4}
**Feb 03 20:21:31 ip-172-31-31-208.us-east-2.compute.internal aws-otel-collector[6456]: 2022-02-03T20:21:31.696Z        debug        awsxrayexporter@v0.43.0/awsxray.go:99        Error translating span.        {"kind": "exporter", "name": "awsxray", "error": "invalid xray traceid: cb2c3e7ab8afadb1886679f76a8154b4"}**

**Environment**
Node.js app on node v 14.18.1
Using Opentelemetry SDKs and APIs the app is already well instrumented.

**Comment by sethAmazon** [comment]
My understanding is this is limitation on the backend. I will track down someone from the xray team to help.

**Comment by sethAmazon** [comment]
There is similar bug here https://github.com/aws-observability/aws-otel-collector/issues/562

**Comment by sanasz91mdev** [comment]
@sethAmazon

Found a work around:

 "To use OpenTelemetry with the collector, you need to configure your app with an x-ray id generator to make sure the IDs are compatible"

at issue [#3405](https://github.com/open-telemetry/opentelemetry-collector/issues/3405)

But this unfortunately require code changes ... Cant xray support Opentelemetry SDK generated IDs? ... is this in roadmap sooner or later?

**Comment by sethAmazon** [comment]
This is on our road map and will be prioritized when available. Sorry I can't give you any more information.
