### ISSUE TITLE
docker/distribution v2.8.0 causes security error

### ISSUE THREAD

**Issue by bryan-aguilar** [aws-observability/aws-otel-collector#977]
**Describe the bug**
`go mod tidy` produces a security error after upgrading `docker/distribution`
```
go: downloading github.com/docker/distribution v2.8.0+incompatible
github.com/aws-observability/aws-otel-collector/pkg/defaultcomponents imports
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscontainerinsightreceiver imports
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscontainerinsightreceiver/internal/cadvisor imports
	github.com/google/cadvisor/container/docker imports
	github.com/docker/docker/client imports
	github.com/docker/distribution/reference: github.com/docker/distribution@v2.8.0+incompatible: verifying module: checksum mismatch
	downloaded: h1:u9vuu6qqG7nN9a735Noed0ahoUm30iipVRlhgh72N0M=
	sum.golang.org: h1:l9EaZDICImO1ngI+uTifW+ZYvvz7fKISBAKpg+MbWbY=

```

**Steps to reproduce**
Upgrade docker distribution and run `go mod tidy`

**What did you expect to see?**
No error

**What did you see instead?**
Error listed above. 

**Environment**
go 1.17

**Comment by slimdevl** [comment]
I got the same think today while trying to build a contain...
```
 > [build-go 7/9] RUN go mod download:
#29 1676.2 verifying github.com/docker/distribution@v2.8.0+incompatible: checksum mismatch
#29 1676.2 	downloaded: h1:u9vuu6qqG7nN9a735Noed0ahoUm30iipVRlhgh72N0M=
#29 1676.2 	go.sum:     h1:l9EaZDICImO1ngI+uTifW+ZYvvz7fKISBAKpg+MbWbY=
#29 1676.2
#29 1676.2 SECURITY ERROR
#29 1676.2 This download does NOT match an earlier download recorded in go.sum.
#29 1676.2 The bits may have been replaced on the origin server, or an attacker may
#29 1676.2 have intercepted the download attempt.
#29 1676.2
#29 1676.2 For more information, see 'go help module-auth'.
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c go mod download]: exit code: 1
```

This is what may docker file looks like:
```
FROM golang:1.17rc2-alpine3.14 as build-go
ENV GOPATH ""
RUN go env -w GOPROXY=direct
RUN apk add git

WORKDIR /project
#
# Speed up dependancy with a layer
ADD go.mod .
ADD go.sum .
RUN go mod download
# now add the code
COPY . .
## build the app
RUN CGO_ENABLED=0 GOOS=linux go build -installsuffix cgo -o app .
```

I am running on a MacBook Pro (2020 Intel CPU)

**Comment by anuraaga** [comment]
#981 might be a way to work around this having this dependency

**Comment by slimdevl** [comment]
Also a notable work around... I found pinning the version to 2.7.1 worked.

**Comment by bryan-aguilar** [comment]
> Also a notable work around... I found pinning the version to 2.7.1 worked.

This would work but does not address the dependabot security vulnerability that was triggered with versions < 2.8.0

**Comment by Aneurysm9** [comment]
> https://github.com/aws-observability/aws-otel-collector/issues/981 might be a way to work around this having this dependency

Unfortunately, not.  While #981 is a good idea, the dependency also comes from upstream modules used in the collector distribution.  I don't think that it would address those dependencies.

**Comment by slimdevl** [comment]
I found my root cause with this thread:

https://github.com/distribution/distribution/issues/3590

> ` I am using GOPROXY=direct and thus downloading directly from github the current state of the module. This does not agree with sum.golang.org, which must have acquired a previous state of the module with that tag. That state is still available from proxy.golang.org`

**Comment by bryan-aguilar** [comment]
> I found my root cause with this thread:
> 
> [distribution/distribution#3590](https://github.com/distribution/distribution/issues/3590)
> 
> > ` I am using GOPROXY=direct and thus downloading directly from github the current state of the module. This does not agree with sum.golang.org, which must have acquired a previous state of the module with that tag. That state is still available from proxy.golang.org`

This would also explain the issue on my end.

**Comment by bryan-aguilar** [comment]
Relevant upstream PR https://github.com/distribution/distribution/pull/3596

**Comment by dcdebug** [comment]
../../../pkg/mod/github.com/docker/distribution@v2.8.3+incompatible/reference/reference_deprecated.go:122:19: undefined: reference.SplitHostname

**Comment by mclacore** [comment]
@dcdebug are you also seeing this error? I just started seeing this error.

**Comment by BulzN** [comment]
@dcdebug @mclacore it's because the package [github.com/docker/Distribution](https://github.com/docker/Distribution) it's deprecated and moved to [github.com/distribution/reference](https://github.com/distribution/reference)

[Go Reference](https://pkg.go.dev/github.com/docker/Distribution/reference#SplitHostname)
> Deprecated: Use [reference.Domain](https://pkg.go.dev/github.com/distribution/reference#Domain) or [reference.Path](https://pkg.go.dev/github.com/distribution/reference#Path).
