### ISSUE TITLE
Jaeger Exporter

### ISSUE THREAD

**Issue by HaroonSaid** [aws-observability/aws-otel-collector#992]
**Is your feature request related to a problem? Please describe.**
We would like to use AWS image, our use case is 
Linux, Windows Containers, and EC2 Windows Servers that emit otel and jaeger spans 

We want to export metrics to AWS Managed Prometheus 
We want to use our own Jeager Infra with Kafka and Open Search.  

Do you have any plans to support the jaeger exporter? 

If not, what is the best way to use the open-source image to export metrics to AWS Prometheus 
**Describe the solution you'd like**
add jager exporter

**Comment by ericksoen** [comment]
Maybe overlap with some of the requested behavior for [Requesting Jaeger and Zipkin Receivers + Exporters](#292).

**Comment by igrayson** [comment]
> Maybe overlap with some of the requested behavior for [Requesting Jaeger and Zipkin Receivers + Exporters](#292).

Better link! https://github.com/aws-observability/aws-otel-collector/issues/292
